/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_nio_channels_spi_AbstractInterruptibleChannel
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_nio_channels_spi_AbstractInterruptibleChannel
 CFASTCALL
java_nio_channels_spi_AbstractInterruptibleChannel__this__( java_nio_channels_spi_AbstractInterruptibleChannel
 This )
{
 {
  ;
 }
 return This;
}

JCGO_NOSEP_INLINE void CFASTCALL
java_nio_channels_spi_AbstractInterruptibleChannel__begin__( java_nio_channels_spi_AbstractInterruptibleChannel
 This )
{
 {
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_nio_channels_spi_AbstractInterruptibleChannel__close__( java_nio_channels_spi_AbstractInterruptibleChannel
 This )
{
 {
  if (!JCGO_FIELD_NZACCESS(This, closed))
  {
   JCGO_FIELD_NZACCESS(This, closed)= (jboolean)jtrue;
   (JCGO_CALL_NZVFUNC(This)->implCloseChannel__(
    This));
  }
 }
}

JCGO_NOSEP_INLINE void CFASTCALL
java_nio_channels_spi_AbstractInterruptibleChannel__end__Z( java_nio_channels_spi_AbstractInterruptibleChannel
 This, jboolean completed )
{
 {
  if (JCGO_FIELD_NZACCESS(This, closed))
  {
   JCGO_THROW_EXC(java_nio_channels_AsynchronousCloseException__new__());
  }
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_nio_channels_spi_AbstractInterruptibleChannel__isOpen__( java_nio_channels_spi_AbstractInterruptibleChannel
 This )
{
 {
  return (jboolean)(!JCGO_FIELD_NZACCESS(This, closed));
 }
}

JCGO_NOSEP_DATA CONST struct jcgo_methods_s java_nio_channels_spi_AbstractInterruptibleChannel_methods=
{
 JCGO_CLASSREF_OF(java_nio_channels_spi_AbstractInterruptibleChannel__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_nio_channels_spi_AbstractInterruptibleChannel,
 0,
 NULL,
 JCGO_CLINIT_INIT(0)
 (jObject (CFASTCALL*)(jObject))java_nio_channels_spi_AbstractInterruptibleChannel__this__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_nio_channels_spi_AbstractInterruptibleChannel_class_s
 java_nio_channels_spi_AbstractInterruptibleChannel__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_nio_channels_spi_AbstractInterruptibleChannel_methods),
  JCGO_STRREF_OF(jcgo_string1_AbstInCh),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x401
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype670_Mdclnt jcgo_array2_AbstInCh=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 50,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)65/*'A'*/, (jbyte)(jchar)98/*'b'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)114/*'r'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)73/*'I'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)114/*'r'*/,
   (jbyte)(jchar)117/*'u'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)98/*'b'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)108/*'l'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_AbstInCh
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_AbstInCh),
 0, 50, (jint)0x70b142aaL
};

#ifdef CHKALL_java_nio_channels_spi_AbstractInterruptibleChannel
#include "jcgochke.h"
#endif

#endif
