/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_STATIC java_util_AbstractSet CFASTCALL
java_util_AbstractSet__this__( java_util_AbstractSet This );

JCGO_NOSEP_STATIC jboolean CFASTCALL
java_util_AbstractSet__equals__Lo( java_util_AbstractSet This, java_lang_Object
 o );

JCGO_NOSEP_STATIC jint CFASTCALL
java_util_AbstractSet__hashCode__( java_util_AbstractSet This );

struct java_util_AbstractSet_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_util_AbstractSet (CFASTCALL *jcgo_thisRtn)( java_util_AbstractSet
  This );
 jboolean (CFASTCALL *equals__Lo)( java_util_AbstractSet This, java_lang_Object
  o );
 jint (CFASTCALL *hashCode__)( java_util_AbstractSet This );
 java_lang_String (CFASTCALL *toString__)( java_util_AbstractCollection
  This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 jboolean (CFASTCALL *isEmpty__)( java_util_AbstractCollection This
  );
 java_util_Iterator (CFASTCALL *iterator__)( java_util_AbstractCollection
  This );
 jint (CFASTCALL *size__)( java_util_AbstractCollection This );
 jboolean (CFASTCALL *add__Lo)( java_util_AbstractCollection This,
  java_lang_Object o );
 jboolean (CFASTCALL *contains__Lo)( java_util_AbstractCollection This,
  java_lang_Object o );
 jboolean (CFASTCALL *containsAll__L07mt2)( java_util_AbstractCollection
  This, java_util_Collection c );
};

struct java_util_AbstractSet_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct jcgo_methods_s java_util_AbstractSet_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_util_AbstractSet_class_s
 java_util_AbstractSet__class;

struct java_util_AbstractSet_s
{
 CONST struct java_util_AbstractSet_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype2_GameMdl jcgo_array2_AbstrcSt;

JCGO_SEP_EXTERN CONST jcgo_arrtype80_GmCnnctn jcgo_array3_AbstrcSt;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_AbstrcSt;

#endif
