/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_nio_channels_spi_AbstractSelectableChannel
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE void CFASTCALL
java_nio_channels_spi_AbstractSelectableChannel__void( java_nio_channels_spi_AbstractSelectableChannel
 This )
{
 JCGO_FIELD_NZACCESS(This, blocking)= jtrue;
 JCGO_FIELD_NZACCESS(This, LOCK)= java_lang_Object__new__();
 JCGO_FIELD_NZACCESS(This, keys)= java_util_LinkedList__new__();
}

JCGO_NOSEP_INLINE java_lang_Object CFASTCALL
java_nio_channels_spi_AbstractSelectableChannel__blockingLock__( java_nio_channels_spi_AbstractSelectableChannel
 This )
{
 {
  return JCGO_FIELD_NZACCESS(This, LOCK);
 }
}

JCGO_NOSEP_INLINE java_nio_channels_spi_AbstractSelectableChannel
 CFASTCALL
java_nio_channels_spi_AbstractSelectableChannel__this__L6sfa6( java_nio_channels_spi_AbstractSelectableChannel
 This, java_nio_channels_spi_SelectorProvider provider )
{
 {
  (java_nio_channels_SelectableChannel__this__((java_nio_channels_SelectableChannel)This));
  java_nio_channels_spi_AbstractSelectableChannel__void(This);
  (void)provider;
 }
 return This;
}

JCGO_NOSEP_STATIC java_nio_channels_SelectableChannel CFASTCALL
java_nio_channels_spi_AbstractSelectableChannel__configureBlocking__Z(
 java_nio_channels_spi_AbstractSelectableChannel This, jboolean blocking
 )
{
 {
  {
   JCGO_SYNC_BLOCK((java_nio_channels_spi_AbstractSelectableChannel__blockingLock__(
    This)))
   {
    if (JCGO_FIELD_NZACCESS(This, blocking) != blocking)
    {
     (gnu_java_nio_SocketChannelImpl__implConfigureBlocking__Z(
      (gnu_java_nio_SocketChannelImpl)This, (jboolean)blocking));
     JCGO_FIELD_NZACCESS(This, blocking)= (jboolean)blocking;
    }
   }
   JCGO_SYNC_END
  }
  return (java_nio_channels_SelectableChannel)This;
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_nio_channels_spi_AbstractSelectableChannel__implCloseChannel__(
 java_nio_channels_spi_AbstractSelectableChannel This )
{
 {
  {
   JCGO_TRY_BLOCK
   {
    (gnu_java_nio_SocketChannelImpl__implCloseSelectableChannel__(
     (gnu_java_nio_SocketChannelImpl)This));
   }
   JCGO_TRY_LEAVE
   {
    jObject jcgo_rcvrL1;
    {
     java_util_Iterator it;
     it= (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, keys), JCGO_CALL_FINALF((java_util_LinkedList)jcgo_rcvrL1)
      java_util_AbstractSequentialList__iterator__(
      (java_util_AbstractSequentialList)jcgo_rcvrL1));
     for (; (JCGO_CALL_VFUNC(it)->hasNext__(
      it));)
     {
      (JCGO_CALL_FINALF(((java_lang_Object)JCGO_CAST_OBJECT0(OBJT_jboolean,
       MAXT_jboolean, (JCGO_CALL_NZVFUNC(it)->next__(
       it))))) (void)0);
     }
    }
   }
   JCGO_TRY_FINALLYEND
  }
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_nio_channels_spi_AbstractSelectableChannel__isBlocking__( java_nio_channels_spi_AbstractSelectableChannel
 This )
{
 {
  return (jboolean)JCGO_FIELD_NZACCESS(This, blocking);
 }
}

JCGO_NOSEP_DATA CONST struct jcgo_methods_s java_nio_channels_spi_AbstractSelectableChannel_methods=
{
 JCGO_CLASSREF_OF(java_nio_channels_spi_AbstractSelectableChannel__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_nio_channels_spi_AbstractSelectableChannel,
 0,
 NULL,
 JCGO_CLINIT_INIT(0)
 0
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_nio_channels_spi_AbstractSelectableChannel_class_s
 java_nio_channels_spi_AbstractSelectableChannel__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_nio_channels_spi_AbstractSelectableChannel_methods),
  JCGO_STRREF_OF(jcgo_string1_AbstSlCh),
  JCGO_CLASSREF_OF(java_nio_channels_SelectableChannel__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x401
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype109_GmCnnctn jcgo_array2_AbstSlCh=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 47,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)65/*'A'*/, (jbyte)(jchar)98/*'b'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)114/*'r'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)98/*'b'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)108/*'l'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_AbstSlCh
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_AbstSlCh),
 0, 47, (jint)0xb4fce0b1L
};

#ifdef CHKALL_java_nio_channels_spi_AbstractSelectableChannel
#include "jcgochke.h"
#endif

#endif
