/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_AbstractList
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE void CFASTCALL
java_util_AbstractList_2__void( java_util_AbstractList_2 This )
{
 JCGO_FIELD_NZACCESS(This, knownMod)= JCGO_FIELD_NZACCESS(JCGO_FIELD_NZACCESS(This,
  this_0), modCount);
 JCGO_FIELD_NZACCESS(This, position)= JCGO_FIELD_NZACCESS(This, val_index);
 JCGO_FIELD_NZACCESS(This, lastReturned)= (-(jint)1);
 JCGO_FIELD_NZACCESS(This, size)= (JCGO_CALL_NZVFUNC(JCGO_FIELD_NZACCESS(This,
  this_0))->size__(
  (java_util_AbstractCollection)JCGO_FIELD_NZACCESS(This, this_0)));
}

JCGO_NOSEP_INLINE void CFASTCALL
java_util_AbstractList_2__checkMod__( java_util_AbstractList_2 This
 )
{
 {
  if (JCGO_FIELD_NZACCESS(This, knownMod) != JCGO_FIELD_NZACCESS(JCGO_FIELD_NZACCESS(This,
   this_0), modCount))
  {
   JCGO_THROW_EXC(java_util_ConcurrentModificationException__new__());
  }
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_AbstractList_2__hasNext__( java_util_AbstractList_2 This
 )
{
 {
  return (jboolean)(JCGO_FIELD_NZACCESS(This, position) < JCGO_FIELD_NZACCESS(This,
   size));
 }
}

JCGO_NOSEP_STATIC java_lang_Object CFASTCALL
java_util_AbstractList_2__next__( java_util_AbstractList_2 This )
{
 {
  (java_util_AbstractList_2__checkMod__(
   This));
  if (JCGO_FIELD_NZACCESS(This, position) == JCGO_FIELD_NZACCESS(This,
   size))
  {
   JCGO_THROW_EXC(java_util_NoSuchElementException__new__());
  }
  JCGO_FIELD_NZACCESS(This, lastReturned)= JCGO_FIELD_NZACCESS(This,
   position);
  return (JCGO_CALL_NZVFUNC(JCGO_FIELD_NZACCESS(This, this_0))->get__I(
   JCGO_FIELD_NZACCESS(This, this_0), JCGO_FIELD_NZACCESS(This, position)++));
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_util_AbstractList_2__remove__( java_util_AbstractList_2 This
 )
{
 {
  (java_util_AbstractList_2__checkMod__(
   This));
  if (JCGO_FIELD_NZACCESS(This, lastReturned) < 0)
  {
   JCGO_THROW_EXC(java_lang_IllegalStateException__new__());
  }
  (JCGO_CALL_NZVFUNC(JCGO_FIELD_NZACCESS(This, this_0))->remove__I(
   JCGO_FIELD_NZACCESS(This, this_0), JCGO_FIELD_NZACCESS(This, lastReturned)));
  JCGO_FIELD_NZACCESS(This, size)--;
  JCGO_FIELD_NZACCESS(This, position)= JCGO_FIELD_NZACCESS(This, lastReturned);
  JCGO_FIELD_NZACCESS(This, lastReturned)= (-(jint)1);
  JCGO_FIELD_NZACCESS(This, knownMod)= JCGO_FIELD_NZACCESS(JCGO_FIELD_NZACCESS(This,
   this_0), modCount);
 }
}

JCGO_NOSEP_INLINE java_util_AbstractList_2 CFASTCALL
java_util_AbstractList_2__this__L8rnj6I( java_util_AbstractList_2
 This, java_util_AbstractList this_0, jint val_index )
{
 {
  JCGO_FIELD_NZACCESS(This, this_0)= this_0;
  JCGO_FIELD_NZACCESS(This, val_index)= val_index;
  java_util_AbstractList_2__void(This);
 }
 return This;
}

JCGO_NOSEP_FRWINL java_util_AbstractList_2 CFASTCALL
java_util_AbstractList_2__new__L8rnj6I( java_util_AbstractList this_0,
 jint val_index )
{
 return java_util_AbstractList_2__this__L8rnj6I(
  (java_util_AbstractList_2)jcgo_newObject((jvtable)&java_util_AbstractList_2_methods),
  this_0, val_index);
}

JCGO_NOSEP_DATA CONST struct java_util_AbstractList_2_methods_s java_util_AbstractList_2_methods=
{
 JCGO_CLASSREF_OF(java_util_AbstractList_2__class),
 JCGO_GCJDESCR_INIT(java_util_AbstractList_2_s, this_0)
 OBJT_java_util_AbstractList_2,
 (JCGO_OBJSIZE_T)sizeof(struct java_util_AbstractList_2_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__,
 java_util_AbstractList_2__hasNext__,
 java_util_AbstractList_2__next__,
 java_util_AbstractList_2__remove__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_util_AbstractList_2_class_s
 java_util_AbstractList_2__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_AbstractList_2_methods),
  JCGO_STRREF_OF(jcgo_string1_AbstLs2C),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array2_EntrItrt)),
  0x0
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype94_GmCnnctn jcgo_array2_AbstLs2C=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 24,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)65/*'A'*/, (jbyte)(jchar)98/*'b'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)114/*'r'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)76/*'L'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)36/*'$'*/, (jbyte)(jchar)50/*'2'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_AbstLs2C
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_AbstLs2C),
 0, 24, (jint)0x88583a2eL
};

#ifdef CHKALL_java_util_AbstractList
#include "jcgochke.h"
#endif

#endif
