/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE java_util_Arrays_ArrayList CFASTCALL
java_util_Arrays_ArrayList__this__LoA( java_util_Arrays_ArrayList
 This, jObjectArr a );
JCGO_NOSEP_INLINE java_util_Arrays_ArrayList CFASTCALL
java_util_Arrays_ArrayList__new__LoA( jObjectArr a );

JCGO_NOSEP_INLINE java_lang_Object CFASTCALL
java_util_Arrays_ArrayList__get__I( java_util_Arrays_ArrayList This,
 jint index );

JCGO_NOSEP_INLINE jint CFASTCALL
java_util_Arrays_ArrayList__size__( java_util_Arrays_ArrayList This
 );

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_Arrays_ArrayList__contains__Lo( java_util_Arrays_ArrayList
 This, java_lang_Object o );

JCGO_NOSEP_STATIC jint CFASTCALL
java_util_Arrays_ArrayList__lastIndexOf__Lo( java_util_Arrays_ArrayList
 This, java_lang_Object o );

struct java_util_Arrays_ArrayList_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_util_Arrays_ArrayList (CFASTCALL *jcgo_thisRtn)( java_util_Arrays_ArrayList
  This );
 jboolean (CFASTCALL *equals__Lo)( java_util_AbstractList This, java_lang_Object
  o );
 jint (CFASTCALL *hashCode__)( java_util_AbstractList This );
 java_lang_String (CFASTCALL *toString__)( java_util_AbstractCollection
  This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 jboolean (CFASTCALL *isEmpty__)( java_util_AbstractCollection This
  );
 java_util_Iterator (CFASTCALL *iterator__)( java_util_AbstractList
  This );
 jint (CFASTCALL *size__)( java_util_Arrays_ArrayList This );
 jboolean (CFASTCALL *add__Lo)( java_util_AbstractList This, java_lang_Object
  o );
 jboolean (CFASTCALL *contains__Lo)( java_util_Arrays_ArrayList This,
  java_lang_Object o );
 jboolean (CFASTCALL *containsAll__L07mt2)( java_util_AbstractCollection
  This, java_util_Collection c );
 java_lang_Object (CFASTCALL *get__I)( java_util_Arrays_ArrayList This,
  jint index );
 void (CFASTCALL *add__ILo)( java_util_AbstractList This, java_lang_Object
  o, jint index );
 java_util_Iterator (CFASTCALL *listIterator__I)( java_util_AbstractList
  This, jint index );
 java_lang_Object (CFASTCALL *remove__I)( java_util_AbstractList This,
  jint index );
};

struct java_util_Arrays_ArrayList_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_util_Arrays_ArrayList_methods_s
 java_util_Arrays_ArrayList_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_util_Arrays_ArrayList_class_s
 java_util_Arrays_ArrayList__class;

struct java_util_Arrays_ArrayList_s
{
 CONST struct java_util_Arrays_ArrayList_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
 jint modCount;
 jObjectArr a;
};

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_ArrLstD3;

#endif
