/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_lang_Boolean
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_lang_Boolean CFASTCALL
java_lang_Boolean__this__Z( java_lang_Boolean This, jboolean value
 )
{
 {
  ;
  JCGO_FIELD_NZACCESS(This, value)= (jboolean)value;
 }
 return This;
}

JCGO_NOSEP_FRWINL java_lang_Boolean CFASTCALL
java_lang_Boolean__new__Z( jboolean value )
{
 return java_lang_Boolean__this__Z(
  (java_lang_Boolean)jcgo_newObject((jvtable)&java_lang_Boolean_methods),
  value);
}

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_lang_Boolean__toString__Z( jboolean b )
{
 {
  return b? JCGO_STRREF_OF(jcgo_string2_Boolean) : JCGO_STRREF_OF(jcgo_string3_Boolean);
 }
}

JCGO_NOSEP_FRWINL jboolean CFASTCALL
java_lang_Boolean__booleanValue__( java_lang_Boolean This )
{
 {
  return (jboolean)JCGO_FIELD_NZACCESS(This, value);
 }
}

JCGO_NOSEP_FRWINL java_lang_Boolean CFASTCALL
java_lang_Boolean__valueOf__Z( jboolean b )
{
 JCGO_CLINIT_TRIG(java_lang_Boolean__class);
 {
  return b? java_lang_Boolean__TRUE0 : java_lang_Boolean__FALSE0;
 }
}

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_lang_Boolean__toString__( java_lang_Boolean This )
{
 {
  return (java_lang_Boolean__toString__Z(
   (jboolean)JCGO_FIELD_NZACCESS(This, value)));
 }
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_lang_Boolean__hashCode__( java_lang_Boolean This )
{
 {
  return JCGO_FIELD_NZACCESS(This, value)? (jint)1231 : (jint)1237;
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_lang_Boolean__equals__Lo( java_lang_Boolean This, java_lang_Object
 obj )
{
 {
  return (jboolean)(jcgo_instanceOf0(OBJT_java_lang_Boolean, MAXT_java_lang_Boolean,
   (jObject)obj) && JCGO_FIELD_NZACCESS(This, value) == JCGO_FIELD_NZACCESS(((java_lang_Boolean)obj),
   value));
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_Boolean__class__0( void )
{
 JCGO_CLINIT_BEGIN(java_lang_Boolean__class);
 java_lang_Boolean__TRUE0= (java_lang_Boolean__new__Z(
  (jboolean)jtrue));
 java_lang_Boolean__FALSE0= (java_lang_Boolean__new__Z(
  (jboolean)jfalse));
 JCGO_CLINIT_DONE(java_lang_Boolean__class);
}

JCGO_NOSEP_DATA CONST struct java_lang_Boolean_methods_s java_lang_Boolean_methods=
{
 JCGO_CLASSREF_OF(java_lang_Boolean__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_lang_Boolean,
 -(JCGO_OBJSIZE_T)sizeof(struct java_lang_Boolean_s),
 NULL,
 JCGO_CLINIT_INIT(java_lang_Boolean__class__0)
 0,
 java_lang_Boolean__equals__Lo,
 java_lang_Boolean__hashCode__,
 java_lang_Boolean__toString__,
 java_lang_Object__finalize__
};

JCGO_NOSEP_DATA struct java_lang_Boolean_class_s java_lang_Boolean__class
 ATTRIBNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_lang_Boolean_methods),
  JCGO_STRREF_OF(jcgo_string1_Boolean),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1d1
 }
};

JCGO_NOSEP_GCDATA java_lang_Boolean java_lang_Boolean__TRUE0 ATTRIBGCBSS=
 jnull;

JCGO_NOSEP_GCDATA java_lang_Boolean java_lang_Boolean__FALSE0 ATTRIBGCBSS=
 jnull;

JCGO_NOSEP_DATA CONST jcgo_arrtype492_Mdclnt jcgo_array4_Boolean=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 17,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)103/*'g'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)66/*'B'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)110/*'n'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype4_IntAddrs jcgo_array5_Boolean=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 4,
 {
  (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)101/*'e'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Boolean
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array4_Boolean),
 0, 17, (jint)0x148d6054L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_Boolean
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array5_Boolean),
 0, 4, (jint)0x36758eL
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_Boolean
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array8_Cnnctn),
 37, 5, (jint)0x5cb1923L
};

#ifdef CHKALL_java_lang_Boolean
#include "jcgochke.h"
#endif

#endif
