/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_security_BasicPermission
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_security_BasicPermission CFASTCALL
java_security_BasicPermission__this__Ls( java_security_BasicPermission
 This, java_lang_String name )
{
 {
  (java_security_Permission__this__Ls((java_security_Permission)This,
   name));
  if ((JCGO_CALL_FINALF(name) java_lang_String__equals__Lo(
   name, (java_lang_Object)JCGO_STRREF_OF(jcgo_string3_String6D))))
  {
   JCGO_THROW_EXC((java_lang_IllegalArgumentException__new__Ls(
    JCGO_STRREF_OF(jcgo_string2_BscPrmss))));
  }
 }
 return This;
}

JCGO_NOSEP_STATIC jboolean CFASTCALL
java_security_BasicPermission__equals__Lo( java_security_BasicPermission
 This, java_lang_Object obj )
{
 {
  jObject jcgo_rcvrL1;
  return (jboolean)(obj == (java_lang_Object)This || (jcgo_instanceOf0(OBJT_java_security_BasicPermission,
   MAXT_java_security_BasicPermission, (jObject)obj) && (jcgo_rcvrL1=
   (jObject)(java_lang_Object__getClass__(
   obj)), (java_lang_Class)jcgo_rcvrL1 == (java_lang_Object__getClass__(
   (java_lang_Object)This))) && (jcgo_rcvrL1= (jObject)(java_security_Permission__getName__(
   (java_security_Permission)This)), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL1)
   java_lang_String__equals__Lo(
   (java_lang_String)jcgo_rcvrL1, (java_lang_Object)(java_security_Permission__getName__(
   (java_security_Permission)((java_security_BasicPermission)obj)))))));
 }
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_security_BasicPermission__hashCode__( java_security_BasicPermission
 This )
{
 {
  jObject jcgo_rcvrL1;
  return (jcgo_rcvrL1= (jObject)(java_security_Permission__getName__(
   (java_security_Permission)This)), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL1)
   java_lang_String__hashCode__(
   (java_lang_String)jcgo_rcvrL1));
 }
}

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_security_BasicPermission__getActions__( java_security_BasicPermission
 This )
{
 {
  return JCGO_STRREF_OF(jcgo_string3_String6D);
 }
}

JCGO_NOSEP_DATA CONST struct jcgo_methods_s java_security_BasicPermission_methods=
{
 JCGO_CLASSREF_OF(java_security_BasicPermission__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_security_BasicPermission,
 0,
 NULL,
 JCGO_CLINIT_INIT(0)
 0
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_security_BasicPermission_class_s
 java_security_BasicPermission__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_security_BasicPermission_methods),
  JCGO_STRREF_OF(jcgo_string1_BscPrmss),
  JCGO_CLASSREF_OF(java_security_Permission__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x401
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype86_GmCnnctn jcgo_array3_BscPrmss=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 29,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)121/*'y'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)66/*'B'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)80/*'P'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)109/*'m'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)110/*'n'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype32_GameShll jcgo_array4_BscPrmss=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 10,
 {
  (jbyte)(jchar)69/*'E'*/, (jbyte)(jchar)109/*'m'*/, (jbyte)(jchar)112/*'p'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)121/*'y'*/, (jbyte)(jchar)32/*' '*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)109/*'m'*/,
   (jbyte)(jchar)101/*'e'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_BscPrmss
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array3_BscPrmss),
 0, 29, (jint)0xafda981bL
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_BscPrmss
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array4_BscPrmss),
 0, 10, (jint)0x3436099eL
};

#ifdef CHKALL_java_security_BasicPermission
#include "jcgochke.h"
#endif

#endif
