/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_STATIC package_Buffer CFASTCALL
package_Buffer__this__BA( package_Buffer This, jbyteArr buff );
JCGO_NOSEP_INLINE package_Buffer CFASTCALL
package_Buffer__new__BA( jbyteArr buff );

JCGO_NOSEP_INLINE jint CFASTCALL
package_Buffer__getUnsignedByte__( package_Buffer This );

JCGO_NOSEP_INLINE jint CFASTCALL
package_Buffer__getUnsignedShort__( package_Buffer This );

JCGO_NOSEP_STATIC jint CFASTCALL
package_Buffer__getUnsignedInt__( package_Buffer This );

struct package_Buffer_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 package_Buffer (CFASTCALL *jcgo_thisRtn)( package_Buffer This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct package_Buffer_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct package_Buffer_methods_s package_Buffer_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct package_Buffer_class_s package_Buffer__class;

struct package_Buffer_s
{
 CONST struct package_Buffer_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
 jbyteArr buffer;
 jint offset;
};

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Buffer96;

#endif
