/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_BZState
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC package_BZState CFASTCALL
package_BZState__this__( package_BZState This )
{
 {
  ;
  JCGO_FIELD_NZACCESS(This, unzftab)= (jintArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jint),
   0, (jint)256);
  JCGO_FIELD_NZACCESS(This, cftab)= (jintArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jint),
   0, (jint)257);
  JCGO_FIELD_NZACCESS(This, inUse)= (jbooleanArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jboolean),
   0, (jint)256);
  JCGO_FIELD_NZACCESS(This, inUse_16)= (jbooleanArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jboolean),
   0, (jint)16);
  JCGO_FIELD_NZACCESS(This, setToUnseq)= (jbyteArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jbyte),
   0, (jint)256);
  JCGO_FIELD_NZACCESS(This, mtfa)= (jbyteArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jbyte),
   0, (jint)4096);
  JCGO_FIELD_NZACCESS(This, mtfbase)= (jintArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jint),
   0, (jint)16);
  JCGO_FIELD_NZACCESS(This, selector)= (jbyteArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jbyte),
   0, (jint)18002);
  JCGO_FIELD_NZACCESS(This, selectorMtf)= (jbyteArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jbyte),
   0, (jint)18002);
  JCGO_FIELD_NZACCESS(This, len)= (jcgo_new4DArray(JCGO_CORECLASS_FOR(OBJT_jbyte),
   2, 0, (jint)6, (jint)258, 0, 0));
  JCGO_FIELD_NZACCESS(This, limit)= (jcgo_new4DArray(JCGO_CORECLASS_FOR(OBJT_jint),
   2, 0, (jint)6, (jint)258, 0, 0));
  JCGO_FIELD_NZACCESS(This, base)= (jcgo_new4DArray(JCGO_CORECLASS_FOR(OBJT_jint),
   2, 0, (jint)6, (jint)258, 0, 0));
  JCGO_FIELD_NZACCESS(This, perm)= (jcgo_new4DArray(JCGO_CORECLASS_FOR(OBJT_jint),
   2, 0, (jint)6, (jint)258, 0, 0));
  JCGO_FIELD_NZACCESS(This, minLens)= (jintArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jint),
   0, (jint)6);
 }
 return This;
}

JCGO_NOSEP_INLINE package_BZState CFASTCALL
package_BZState__new__( void )
{
 return package_BZState__this__(
  (package_BZState)jcgo_newObject((jvtable)&package_BZState_methods));
}

JCGO_NOSEP_DATA CONST struct package_BZState_methods_s package_BZState_methods=
{
 JCGO_CLASSREF_OF(package_BZState__class),
 JCGO_GCJDESCR_INIT(package_BZState_s, minLens)
 OBJT_package_BZState,
 (JCGO_OBJSIZE_T)sizeof(struct package_BZState_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 package_BZState__this__,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct package_BZState_class_s package_BZState__class
 JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&package_BZState_methods),
  JCGO_STRREF_OF(jcgo_string1_BZState),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x0
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype24_Object jcgo_array2_BZState=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 7,
 {
  (jbyte)(jchar)66/*'B'*/, (jbyte)(jchar)90/*'Z'*/, (jbyte)(jchar)83/*'S'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)101/*'e'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_BZState
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_BZState),
 0, 7, (jint)0x41b74319L
};

#ifdef CHKALL_BZState
#include "jcgochke.h"
#endif

#endif
