/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_nio_charset_CoderResult
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_nio_charset_CoderResult_Cache CFASTCALL
java_nio_charset_CoderResult_Cache__this__( java_nio_charset_CoderResult_Cache
 This )
{
 {
  ;
  JCGO_FIELD_NZACCESS(This, cache)= java_util_HashMap__new__();
 }
 return This;
}

JCGO_NOSEP_STATIC java_nio_charset_CoderResult CFASTCALL
java_nio_charset_CoderResult_Cache__get__I( java_nio_charset_CoderResult_Cache
 This, jint length )
{
 JCGO_SYNC_BLOCKSAFENZ(This)
 {
  java_lang_Integer len;
  java_nio_charset_CoderResult cr;
  java_lang_Object o;
  jObject jcgo_rcvrL1;
  if (length <= 0)
  {
   JCGO_THROW_EXC((java_lang_IllegalArgumentException__new__Ls(
    JCGO_STRREF_OF(jcgo_string2_CacheE78))));
  }
  len= (java_lang_Integer__new__I(
   length));
  cr= (java_nio_charset_CoderResult)jnull;
  if ((o= (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, cache),
   JCGO_CALL_FINALF((java_util_HashMap)jcgo_rcvrL1) java_util_HashMap__get__Lo(
   (java_util_HashMap)jcgo_rcvrL1, (java_lang_Object)len))) != jnull)
  {
   cr= (java_nio_charset_CoderResult)JCGO_CAST_OBJECT0(OBJT_java_nio_charset_CoderResult,
    MAXT_java_nio_charset_CoderResult, (java_lang_ref_Reference__get__(
    (java_lang_ref_Reference)((java_lang_ref_WeakReference)JCGO_CAST_OBJECT0(OBJT_java_lang_ref_WeakReference,
    MAXT_java_lang_ref_WeakReference, o)))));
  }
  if (cr == jnull)
  {
   jObject jcgo_rcvrL1;
   cr= (JCGO_CALL_NZVFUNC(This)->make__I(
    This, length));
   (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, cache), java_util_HashMap__put__LoLo(
    (java_util_HashMap)jcgo_rcvrL1, (java_lang_Object)len, (java_lang_Object)(java_lang_ref_WeakReference__new__Lo(
    (java_lang_Object)cr))));
  }
#ifndef JCGO_SEHTRY
  JCGO_SYNC_JUMPLEAVE(0);
#endif
  return cr;
 }
 JCGO_SYNC_ENDUNREACH
}

JCGO_NOSEP_DATA CONST struct jcgo_methods_s java_nio_charset_CoderResult_Cache_methods=
{
 JCGO_CLASSREF_OF(java_nio_charset_CoderResult_Cache__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_nio_charset_CoderResult_Cache,
 0,
 NULL,
 JCGO_CLINIT_INIT(0)
 (jObject (CFASTCALL*)(jObject))java_nio_charset_CoderResult_Cache__this__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_nio_charset_CoderResult_Cache_class_s
 java_nio_charset_CoderResult_Cache__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_nio_charset_CoderResult_Cache_methods),
  JCGO_STRREF_OF(jcgo_string1_CacheE78),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x40a
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype87_GmCnnctn jcgo_array3_CacheE78=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 34,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)67/*'C'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)100/*'d'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)82/*'R'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)117/*'u'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)36/*'$'*/, (jbyte)(jchar)67/*'C'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)101/*'e'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype42_GameShll jcgo_array4_CacheE78=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 19,
 {
  (jbyte)(jchar)78/*'N'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)45/*'-'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)118/*'v'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)104/*'h'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_CacheE78
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array3_CacheE78),
 0, 34, (jint)0xb08b1278L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_CacheE78
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array4_CacheE78),
 0, 19, (jint)0x18a5c7cdL
};

#ifdef CHKALL_java_nio_charset_CoderResult
#include "jcgochke.h"
#endif

#endif
