/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_STATIC java_nio_charset_CodingErrorAction CFASTCALL
java_nio_charset_CodingErrorAction__this__Ls( java_nio_charset_CodingErrorAction
 This, java_lang_String name );
JCGO_NOSEP_FRWINL java_nio_charset_CodingErrorAction CFASTCALL
java_nio_charset_CodingErrorAction__new__Ls( java_lang_String name
 );

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_nio_charset_CodingErrorAction__toString__( java_nio_charset_CodingErrorAction
 This );

struct java_nio_charset_CodingErrorAction_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_nio_charset_CodingErrorAction (CFASTCALL *jcgo_thisRtn)( java_nio_charset_CodingErrorAction
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_nio_charset_CodingErrorAction
  This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct java_nio_charset_CodingErrorAction_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_nio_charset_CodingErrorAction_methods_s
 java_nio_charset_CodingErrorAction_methods;
JCGO_SEP_EXTERN struct java_nio_charset_CodingErrorAction_class_s java_nio_charset_CodingErrorAction__class;

JCGO_NOSEP_STATIC void CFASTCALL
java_nio_charset_CodingErrorAction__class__0( void );

JCGO_SEP_GCEXTERN java_nio_charset_CodingErrorAction java_nio_charset_CodingErrorAction__REPLACE;
JCGO_SEP_GCEXTERN java_nio_charset_CodingErrorAction java_nio_charset_CodingErrorAction__REPORT;

struct java_nio_charset_CodingErrorAction_s
{
 CONST struct java_nio_charset_CodingErrorAction_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
 java_lang_String name;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype87_GmCnnctn jcgo_array5_CdngErAc;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_CdngErAc;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_CdngErAc;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_CdngErAc;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_CdngErAc;

#endif
