/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_nio_charset_CoderResult
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE java_nio_charset_CoderResult CFASTCALL
java_nio_charset_CoderResult_1__make__I( java_nio_charset_CoderResult_1
 This, jint length )
{
 {
  return (java_nio_charset_CoderResult__new__II(
   java_nio_charset_CoderResult__TYPE_MALFORMED, length));
 }
}

JCGO_NOSEP_STATIC java_nio_charset_CoderResult_1 CFASTCALL
java_nio_charset_CoderResult_1__this__( java_nio_charset_CoderResult_1
 This )
{
 {
  (java_nio_charset_CoderResult_Cache__this__((java_nio_charset_CoderResult_Cache)This));
 }
 return This;
}

JCGO_NOSEP_FRWINL java_nio_charset_CoderResult_1 CFASTCALL
java_nio_charset_CoderResult_1__new__( void )
{
 return java_nio_charset_CoderResult_1__this__(
  (java_nio_charset_CoderResult_1)jcgo_newObject((jvtable)&java_nio_charset_CoderResult_1_methods));
}

JCGO_NOSEP_DATA CONST struct java_nio_charset_CoderResult_1_methods_s
 java_nio_charset_CoderResult_1_methods=
{
 JCGO_CLASSREF_OF(java_nio_charset_CoderResult_1__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_nio_charset_CoderResult_1,
 (JCGO_OBJSIZE_T)sizeof(struct java_nio_charset_CoderResult_1_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 java_nio_charset_CoderResult_1__this__,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__,
 java_nio_charset_CoderResult_1__make__I
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_nio_charset_CoderResult_1_class_s
 java_nio_charset_CoderResult_1__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_nio_charset_CoderResult_1_methods),
  JCGO_STRREF_OF(jcgo_string1_CdrRslt1),
  JCGO_CLASSREF_OF(java_nio_charset_CoderResult_Cache__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x8
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_CdrRslt1
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array535_VMSstmPr),
 0, 30, (jint)0xb74e4e47L
};

#ifdef CHKALL_java_nio_charset_CoderResult
#include "jcgochke.h"
#endif

#endif
