/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE java_nio_charset_CoderResult CFASTCALL
java_nio_charset_CoderResult_2__make__I( java_nio_charset_CoderResult_2
 This, jint length );

JCGO_NOSEP_STATIC java_nio_charset_CoderResult_2 CFASTCALL
java_nio_charset_CoderResult_2__this__( java_nio_charset_CoderResult_2
 This );
JCGO_NOSEP_FRWINL java_nio_charset_CoderResult_2 CFASTCALL
java_nio_charset_CoderResult_2__new__( void );

struct java_nio_charset_CoderResult_2_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_nio_charset_CoderResult_2 (CFASTCALL *jcgo_thisRtn)( java_nio_charset_CoderResult_2
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 java_nio_charset_CoderResult (CFASTCALL *make__I)( java_nio_charset_CoderResult_2
  This, jint length );
};

struct java_nio_charset_CoderResult_2_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_nio_charset_CoderResult_2_methods_s
 java_nio_charset_CoderResult_2_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_nio_charset_CoderResult_2_class_s
 java_nio_charset_CoderResult_2__class;

struct java_nio_charset_CoderResult_2_s
{
 CONST struct java_nio_charset_CoderResult_2_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
 java_util_HashMap cache;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype77_GmCnnctn jcgo_array2_CdrRslt2;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_CdrRslt2;

#endif
