/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_STATIC java_lang_String CFASTCALL
package_ChatMessage__descramble__BAII( jbyteArr buff, jint off, jint
 len );

JCGO_NOSEP_STATIC jint CFASTCALL
package_ChatMessage__scramble__Ls( java_lang_String s );

JCGO_NOSEP_STATIC package_ChatMessage CFASTCALL
package_ChatMessage__this__( package_ChatMessage This );

struct package_ChatMessage_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 package_ChatMessage (CFASTCALL *jcgo_thisRtn)( package_ChatMessage
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct package_ChatMessage_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct package_ChatMessage_methods_s package_ChatMessage_methods;
JCGO_SEP_EXTERN struct package_ChatMessage_class_s package_ChatMessage__class;

JCGO_NOSEP_STATIC void CFASTCALL
package_ChatMessage__class__0( void );

JCGO_SEP_EXTERN CONST jbyteArr package_ChatMessage__scrambledbytes;
JCGO_SEP_GCEXTERN jcharArr package_ChatMessage__chars;
JCGO_SEP_EXTERN CONST jcharArr package_ChatMessage__charmap;

struct package_ChatMessage_s
{
 CONST struct package_ChatMessage_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN jcgo_arrtype2_ChatMssg jcgo_array2_ChatMssg;

JCGO_SEP_EXTERN CONST jcgo_arrtype3_ChatMssg jcgo_array3_ChatMssg;

JCGO_SEP_EXTERN CONST jcgo_arrtype28_Object jcgo_array4_ChatMssg;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_ChatMssg;

#endif
