/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

#define java_nio_charset_CharsetEncoder__STATE_RESET 0

#define java_nio_charset_CharsetEncoder__STATE_CODING (jint)1

#define java_nio_charset_CharsetEncoder__STATE_END (jint)2

#define java_nio_charset_CharsetEncoder__STATE_FLUSHED (jint)3

#define java_nio_charset_CharsetEncoder__DEFAULT_REPLACEMENT ((jbyteArr)JCGO_OBJREF_OF(jcgo_array2_ChrstEnc))

JCGO_NOSEP_INLINE void CFASTCALL
java_nio_charset_CharsetEncoder__void( java_nio_charset_CharsetEncoder
 This );

JCGO_NOSEP_STATIC java_nio_charset_CharsetEncoder CFASTCALL
java_nio_charset_CharsetEncoder__this__L7qsf6FFBA( java_nio_charset_CharsetEncoder
 This, java_nio_charset_Charset cs, jbyteArr replacement, jfloat averageBytesPerChar,
 jfloat maxBytesPerChar );

JCGO_NOSEP_FRWINL void CFASTCALL
java_nio_charset_CharsetEncoder__implReplaceWith__BA( java_nio_charset_CharsetEncoder
 This, jbyteArr newReplacement );

JCGO_NOSEP_INLINE jfloat CFASTCALL
java_nio_charset_CharsetEncoder__maxBytesPerChar__( java_nio_charset_CharsetEncoder
 This );

JCGO_NOSEP_INLINE java_nio_charset_CoderResult CFASTCALL
java_nio_charset_CharsetEncoder__encode__L3367bL9oaiaZ( java_nio_charset_CharsetEncoder
 This, java_nio_CharBuffer in, java_nio_ByteBuffer out, jboolean endOfInput
 );

JCGO_NOSEP_INLINE java_nio_charset_CoderResult CFASTCALL
java_nio_charset_CharsetEncoder__implFlush__L9oaia( java_nio_charset_CharsetEncoder
 This, java_nio_ByteBuffer out );

JCGO_NOSEP_INLINE java_nio_charset_CoderResult CFASTCALL
java_nio_charset_CharsetEncoder__flush__L9oaia( java_nio_charset_CharsetEncoder
 This, java_nio_ByteBuffer out );

JCGO_NOSEP_INLINE void CFASTCALL
java_nio_charset_CharsetEncoder__implOnMalformedInput__L6zetg( java_nio_charset_CharsetEncoder
 This, java_nio_charset_CodingErrorAction newAction );

JCGO_NOSEP_INLINE void CFASTCALL
java_nio_charset_CharsetEncoder__implOnUnmappableCharacter__L6zetg(
 java_nio_charset_CharsetEncoder This, java_nio_charset_CodingErrorAction
 newAction );

JCGO_NOSEP_INLINE void CFASTCALL
java_nio_charset_CharsetEncoder__implReset__( java_nio_charset_CharsetEncoder
 This );

JCGO_NOSEP_INLINE java_nio_charset_CharsetEncoder CFASTCALL
java_nio_charset_CharsetEncoder__this__L7qsf6FF( java_nio_charset_CharsetEncoder
 This, java_nio_charset_Charset cs, jfloat averageBytesPerChar, jfloat
 maxBytesPerChar );

JCGO_NOSEP_STATIC java_nio_ByteBuffer CFASTCALL
java_nio_charset_CharsetEncoder__encode__L3367b( java_nio_charset_CharsetEncoder
 This, java_nio_CharBuffer in );

JCGO_NOSEP_STATIC java_nio_charset_CharsetEncoder CFASTCALL
java_nio_charset_CharsetEncoder__onMalformedInput__L6zetg( java_nio_charset_CharsetEncoder
 This, java_nio_charset_CodingErrorAction newAction );

JCGO_NOSEP_STATIC java_nio_charset_CharsetEncoder CFASTCALL
java_nio_charset_CharsetEncoder__onUnmappableCharacter__L6zetg( java_nio_charset_CharsetEncoder
 This, java_nio_charset_CodingErrorAction newAction );

JCGO_NOSEP_FRWINL java_nio_charset_CharsetEncoder CFASTCALL
java_nio_charset_CharsetEncoder__reset__( java_nio_charset_CharsetEncoder
 This );

struct java_nio_charset_CharsetEncoder_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_nio_charset_CharsetEncoder (CFASTCALL *jcgo_thisRtn)( java_nio_charset_CharsetEncoder
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 java_nio_charset_CoderResult (CFASTCALL *encodeLoop__L3367bL9oaia)(
  java_nio_charset_CharsetEncoder This, java_nio_CharBuffer in, java_nio_ByteBuffer
  out );
 void (CFASTCALL *implReset__)( java_nio_charset_CharsetEncoder This
  );
};

struct java_nio_charset_CharsetEncoder_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct jcgo_methods_s java_nio_charset_CharsetEncoder_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_nio_charset_CharsetEncoder_class_s
 java_nio_charset_CharsetEncoder__class;

struct java_nio_charset_CharsetEncoder_s
{
 CONST struct java_nio_charset_CharsetEncoder_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
 jbyteArr replacement;
 java_nio_charset_CodingErrorAction malformedInputAction;
 java_nio_charset_CodingErrorAction unmappableCharacterAction;
 jfloat maxBytesPerChar;
 jint state;
};

JCGO_SEP_EXTERN jcgo_arrtype2_VMChnnl jcgo_array2_ChrstEnc;

JCGO_SEP_EXTERN CONST jcgo_arrtype73_GmCnnctn jcgo_array6_ChrstEnc;

JCGO_SEP_EXTERN CONST jcgo_arrtype98_GmCnnctn jcgo_array7_ChrstEnc;

JCGO_SEP_EXTERN CONST jcgo_arrtype90_GmCnnctn jcgo_array8_ChrstEnc;

JCGO_SEP_EXTERN CONST jcgo_arrtype28_Object jcgo_array9_ChrstEnc;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_ChrstEnc;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_ChrstEnc;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_ChrstEnc;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string5_ChrstEnc;

#endif
