/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_Collections
#include "jcgobchk.h"
#endif

JCGO_NOSEP_FRWINL java_util_Set CFASTCALL
java_util_Collections__unmodifiableSet__L1x914( java_util_Set s )
{
 JCGO_CLINIT_TRIG(java_util_Collections__class);
 {
  return (java_util_Set)(java_util_Collections_UnmodifiableSet__new__L1x914(
   s));
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_util_Collections__class__0( void )
{
 JCGO_CLINIT_BEGIN(java_util_Collections__class);
 java_util_Collections__EMPTY_SET= (java_util_Set)java_util_Collections_EmptySet__new__();
 java_util_Collections__EMPTY_LIST= (java_util_List)java_util_Collections_EmptyList__new__();
 (void)((java_util_Map)java_util_Collections_EmptyMap__new__());
 (void)(java_util_Collections_ReverseComparator__new__());
 JCGO_CLINIT_DONE(java_util_Collections__class);
}

JCGO_NOSEP_DATA CONST struct jcgo_methods_s java_util_Collections_methods=
{
 JCGO_CLASSREF_OF(java_util_Collections__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_util_Collections,
 0,
 NULL,
 JCGO_CLINIT_INIT(java_util_Collections__class__0)
 0
};

JCGO_NOSEP_DATA struct java_util_Collections_class_s java_util_Collections__class
 ATTRIBNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_Collections_methods),
  JCGO_STRREF_OF(jcgo_string1_Cllctns),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1c1
 }
};

JCGO_NOSEP_GCDATA java_util_Set java_util_Collections__EMPTY_SET ATTRIBGCBSS=
 jnull;

JCGO_NOSEP_GCDATA java_util_List java_util_Collections__EMPTY_LIST
 ATTRIBGCBSS= jnull;

JCGO_NOSEP_DATA CONST jcgo_arrtype73_GmCnnctn jcgo_array2_Cllctns=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 31,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)36/*'$'*/, (jbyte)(jchar)69/*'E'*/, (jbyte)(jchar)109/*'m'*/,
   (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)121/*'y'*/,
   (jbyte)(jchar)76/*'L'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)116/*'t'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Cllctns
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_Cllctns),
 0, 21, (jint)0x82803d5L
};

#ifdef CHKALL_java_util_Collections
#include "jcgochke.h"
#endif

#endif
