/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_ConcurrentModificationException
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_util_ConcurrentModificationException CFASTCALL
java_util_ConcurrentModificationException__this__( java_util_ConcurrentModificationException
 This )
{
 {
  (java_lang_RuntimeException__this__((java_lang_RuntimeException)This));
 }
 return This;
}

JCGO_NOSEP_INLINE java_util_ConcurrentModificationException CFASTCALL
java_util_ConcurrentModificationException__new__( void )
{
 return java_util_ConcurrentModificationException__this__(
  (java_util_ConcurrentModificationException)jcgo_newObject((jvtable)&java_util_ConcurrentModificationException_methods));
}

JCGO_NOSEP_DATA CONST struct java_util_ConcurrentModificationException_methods_s
 java_util_ConcurrentModificationException_methods=
{
 JCGO_CLASSREF_OF(java_util_ConcurrentModificationException__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_util_ConcurrentModificationException,
 (JCGO_OBJSIZE_T)sizeof(struct java_util_ConcurrentModificationException_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 java_util_ConcurrentModificationException__this__,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Throwable__toString__,
 java_lang_Object__finalize__,
 java_lang_Throwable__getMessage__,
 java_lang_Throwable__getCause__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_util_ConcurrentModificationException_class_s
 java_util_ConcurrentModificationException__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_ConcurrentModificationException_methods),
  JCGO_STRREF_OF(jcgo_string1_CncrMdEx),
  JCGO_CLASSREF_OF(java_lang_RuntimeException__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype468_VMSstmPr jcgo_array2_CncrMdEx=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 41,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)77/*'M'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)100/*'d'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)102/*'f'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)99/*'c'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)69/*'E'*/,
   (jbyte)(jchar)120/*'x'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)110/*'n'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_CncrMdEx
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_CncrMdEx),
 0, 41, (jint)0x30e15edcL
};

#ifdef CHKALL_java_util_ConcurrentModificationException
#include "jcgochke.h"
#endif

#endif
