/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

#define gnu_classpath_Configuration__CLASSPATH_VERSION JCGO_STRREF_OF(jcgo_string2_Cnfgrtn)

#define gnu_classpath_Configuration__CLASSPATH_HOME JCGO_STRREF_OF(jcgo_string3_Cnfgrtn)

#define gnu_classpath_Configuration__INIT_LOAD_LIBRARY jfalse

struct gnu_classpath_Configuration_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 gnu_classpath_Configuration (CFASTCALL *jcgo_thisRtn)( gnu_classpath_Configuration
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct gnu_classpath_Configuration_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct jcgo_methods_s gnu_classpath_Configuration_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct gnu_classpath_Configuration_class_s
 gnu_classpath_Configuration__class;

struct gnu_classpath_Configuration_s
{
 CONST struct gnu_classpath_Configuration_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype4_IntAddrs jcgo_array4_Cnfgrtn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Cnfgrtn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_Cnfgrtn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_Cnfgrtn;

#endif
