/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

#define java_lang_reflect_Constructor__CONSTRUCTOR_MODIFIERS (java_lang_reflect_Modifier__PUBLIC | java_lang_reflect_Modifier__PRIVATE | java_lang_reflect_Modifier__PROTECTED | java_lang_reflect_Modifier__STRICT0)

JCGO_NOSEP_FRWINL jint CFASTCALL
java_lang_reflect_Constructor__getModifiers__( java_lang_reflect_Constructor
 This );

JCGO_NOSEP_STATIC java_lang_reflect_Constructor CFASTCALL
java_lang_reflect_Constructor__this__LcILcALcAILs( java_lang_reflect_Constructor
 This, java_lang_Class declaringClass, jObjectArr parameterTypes, jObjectArr
 exceptionTypes, java_lang_String signature, jint slot, jint modifiers
 );
JCGO_NOSEP_FRWINL java_lang_reflect_Constructor CFASTCALL
java_lang_reflect_Constructor__new__LcILcALcAILs( java_lang_Class
 declaringClass, jObjectArr parameterTypes, jObjectArr exceptionTypes,
 java_lang_String signature, jint slot, jint modifiers );

JCGO_NOSEP_STATIC java_lang_Class CFASTCALL
java_lang_reflect_Constructor__getDeclaringClass__( java_lang_reflect_Constructor
 This );

JCGO_NOSEP_STATIC jboolean CFASTCALL
java_lang_reflect_Constructor__equals__Lo( java_lang_reflect_Constructor
 This, java_lang_Object obj );

JCGO_NOSEP_INLINE jint CFASTCALL
java_lang_reflect_Constructor__hashCode__( java_lang_reflect_Constructor
 This );

JCGO_NOSEP_STATIC java_lang_String CFASTCALL
java_lang_reflect_Constructor__toString__( java_lang_reflect_Constructor
 This );

JCGO_NOSEP_STATIC java_lang_StringBuilder CFASTCALL
java_lang_reflect_Constructor__appendTypeName__LcL5dy9e( java_lang_Class
 aclass, java_lang_StringBuilder sb );

JCGO_NOSEP_STATIC jboolean CFASTCALL
java_lang_reflect_Constructor__equalTypes__LcALcA( jObjectArr types,
 jObjectArr types2 );

struct java_lang_reflect_Constructor_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_lang_reflect_Constructor (CFASTCALL *jcgo_thisRtn)( java_lang_reflect_Constructor
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_reflect_Constructor This,
  java_lang_Object obj );
 jint (CFASTCALL *hashCode__)( java_lang_reflect_Constructor This );
 java_lang_String (CFASTCALL *toString__)( java_lang_reflect_Constructor
  This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct java_lang_reflect_Constructor_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_lang_reflect_Constructor_methods_s
 java_lang_reflect_Constructor_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_reflect_Constructor_class_s
 java_lang_reflect_Constructor__class;

struct java_lang_reflect_Constructor_s
{
 CONST struct java_lang_reflect_Constructor_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
 jboolean flag;
 java_lang_Class clazz;
 jObjectArr parameterTypes;
 jObjectArr exceptionTypes;
 jint slot;
 jint modifiers;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype2_GameMdl jcgo_array3_Cnstrctr;

JCGO_SEP_EXTERN CONST jcgo_arrtype86_GmCnnctn jcgo_array4_Cnstrctr;

JCGO_SEP_EXTERN CONST jcgo_arrtype31_GameShll jcgo_array5_Cnstrctr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Cnstrctr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_Cnstrctr;

#endif
