/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

#define package_Command__CL_TRADE_CONFIRM_ACCEPT (jint)104

#define package_Command__CL_APPEARANCE (jint)235

#define package_Command__CL_BANK_CLOSE (jint)212

#define package_Command__CL_BANK_DEPOSIT (jint)23

#define package_Command__CL_BANK_WITHDRAW (jint)22

#define package_Command__CL_CAST_GROUND (jint)158

#define package_Command__CL_CAST_INVITEM (jint)4

#define package_Command__CL_CAST_NPC (jint)50

#define package_Command__CL_CAST_OBJECT (jint)99

#define package_Command__CL_CAST_PLAYER (jint)229

#define package_Command__CL_CAST_SELF (jint)137

#define package_Command__CL_CHAT (jint)216

#define package_Command__CL_CHOOSE_OPTION (jint)116

#define package_Command__CL_CLOSE_CONNECTION (jint)31

#define package_Command__CL_COMBAT_STYLE (jint)29

#define package_Command__CL_COMMAND (jint)38

#define package_Command__CL_DUEL_ACCEPT (jint)176

#define package_Command__CL_DUEL_CONFIRM_ACCEPT (jint)77

#define package_Command__CL_DUEL_DECLINE (jint)197

#define package_Command__CL_DUEL_ITEM_UPDATE (jint)33

#define package_Command__CL_DUEL_SETTINGS (jint)8

#define package_Command__CL_FRIEND_ADD (jint)195

#define package_Command__CL_FRIEND_REMOVE (jint)167

#define package_Command__CL_CAST_GROUNDITEM (jint)249

#define package_Command__CL_GROUNDITEM_TAKE (jint)247

#define package_Command__CL_IGNORE_ADD (jint)132

#define package_Command__CL_IGNORE_REMOVE (jint)241

#define package_Command__CL_INV_CMD (jint)90

#define package_Command__CL_INV_DROP (jint)246

#define package_Command__CL_INV_UNEQUIP (jint)170

#define package_Command__CL_INV_WEAR (jint)169

#define package_Command__CL_KNOWN_PLAYERS (jint)163

#define package_Command__CL_LOGIN 0

#define package_Command__CL_LOGOUT (jint)102

#define package_Command__CL_NPC_ATTACK (jint)190

#define package_Command__CL_NPC_CMD (jint)202

#define package_Command__CL_NPC_TALK (jint)153

#define package_Command__CL_OBJECT_CMD1 (jint)136

#define package_Command__CL_OBJECT_CMD2 (jint)79

#define package_Command__CL_PACKET_EXCEPTION (jint)3

#define package_Command__CL_PING (jint)67

#define package_Command__CL_PLAYER_ATTACK (jint)171

#define package_Command__CL_PLAYER_DUEL (jint)103

#define package_Command__CL_PLAYER_FOLLOW (jint)165

#define package_Command__CL_PLAYER_TRADE (jint)142

#define package_Command__CL_PM (jint)218

#define package_Command__CL_PRAYER_OFF (jint)254

#define package_Command__CL_PRAYER_ON (jint)60

#define package_Command__CL_REPORT_ABUSE (jint)206

#define package_Command__CL_SESSION (jint)32

#define package_Command__CL_SETTINGS_GAME (jint)111

#define package_Command__CL_SETTINGS_PRIVACY (jint)64

#define package_Command__CL_SHOP_BUY (jint)236

#define package_Command__CL_SHOP_CLOSE (jint)166

#define package_Command__CL_SHOP_SELL (jint)221

#define package_Command__CL_SLEEP_WORD (jint)45

#define package_Command__CL_TRADE_ACCEPT (jint)55

#define package_Command__CL_TRADE_DECLINE (jint)230

#define package_Command__CL_TRADE_ITEM_UPDATE (jint)46

#define package_Command__CL_USEWITH_GROUNDITEM (jint)53

#define package_Command__CL_USEWITH_INVITEM (jint)91

#define package_Command__CL_USEWITH_NPC (jint)135

#define package_Command__CL_USEWITH_OBJECT (jint)115

#define package_Command__CL_USEWITH_PLAYER (jint)113

#define package_Command__CL_WALK (jint)187

#define package_Command__CL_WALK_ACTION (jint)16

#define package_Command__CL_WALL_OBJECT_COMMAND1 (jint)14

#define package_Command__CL_WALL_OBJECT_COMMAND2 (jint)127

#define package_Command__CL_CAST_WALLOBJECT (jint)180

#define package_Command__CL_USEWITH_WALLOBJECT (jint)161

#define package_Command__SV_APPEARANCE (jint)59

#define package_Command__SV_BANK_CLOSE (jint)203

#define package_Command__SV_BANK_OPEN (jint)42

#define package_Command__SV_BANK_UPDATE (jint)249

#define package_Command__SV_CLOSE_CONNECTION (jint)4

#define package_Command__SV_DUEL_ACCEPTED (jint)210

#define package_Command__SV_DUEL_CLOSE (jint)225

#define package_Command__SV_DUEL_CONFIRM_OPEN (jint)172

#define package_Command__SV_DUEL_OPEN (jint)176

#define package_Command__SV_DUEL_OPPONENT_ACCEPTED (jint)253

#define package_Command__SV_DUEL_SETTINGS (jint)30

#define package_Command__SV_DUEL_UPDATE (jint)6

#define package_Command__SV_FRIEND_LIST (jint)71

#define package_Command__SV_FRIEND_MESSAGE (jint)120

#define package_Command__SV_FRIEND_STATUS_CHANGE (jint)149

#define package_Command__SV_GAME_SETTINGS (jint)240

#define package_Command__SV_IGNORE_LIST (jint)109

#define package_Command__SV_INVENTORY_ITEMS (jint)53

#define package_Command__SV_INVENTORY_ITEM_REMOVE (jint)123

#define package_Command__SV_INVENTORY_ITEM_UPDATE (jint)90

#define package_Command__SV_LOGOUT_DENY (jint)183

#define package_Command__SV_MESSAGE (jint)131

#define package_Command__SV_OPTION_LIST (jint)245

#define package_Command__SV_OPTION_LIST_CLOSE (jint)252

#define package_Command__SV_PLAYER_DIED (jint)83

#define package_Command__SV_PLAYER_QUEST_LIST (jint)5

#define package_Command__SV_PLAYER_STAT_EQUIPMENT_BONUS (jint)153

#define package_Command__SV_PLAYER_STAT_EXPERIENCE_UPDATE (jint)33

#define package_Command__SV_PLAYER_STAT_FATIGUE (jint)114

#define package_Command__SV_PLAYER_STAT_FATIGUE_ASLEEP (jint)244

#define package_Command__SV_PLAYER_STAT_LIST (jint)156

#define package_Command__SV_PLAYER_STAT_UPDATE (jint)159

#define package_Command__SV_PRAYER_STATUS (jint)206

#define package_Command__SV_PRIVACY_SETTINGS (jint)51

#define package_Command__SV_REGION_ENTITY_UPDATE (jint)211

#define package_Command__SV_REGION_GROUND_ITEMS (jint)99

#define package_Command__SV_REGION_NPCS (jint)79

#define package_Command__SV_REGION_NPC_UPDATE (jint)104

#define package_Command__SV_REGION_OBJECTS (jint)48

#define package_Command__SV_REGION_PLAYERS (jint)191

#define package_Command__SV_REGION_PLAYER_UPDATE (jint)234

#define package_Command__SV_REGION_WALL_OBJECTS (jint)91

#define package_Command__SV_SERVER_MESSAGE (jint)89

#define package_Command__SV_SERVER_MESSAGE_ONTOP (jint)222

#define package_Command__SV_SHOP_CLOSE (jint)137

#define package_Command__SV_SHOP_OPEN (jint)101

#define package_Command__SV_SLEEP_CLOSE (jint)84

#define package_Command__SV_SLEEP_INCORRECT (jint)194

#define package_Command__SV_SLEEP_OPEN (jint)117

#define package_Command__SV_SOUND (jint)204

#define package_Command__SV_SYSTEM_UPDATE (jint)52

#define package_Command__SV_TELEPORT_BUBBLE (jint)36

#define package_Command__SV_TRADE_CLOSE (jint)128

#define package_Command__SV_TRADE_CONFIRM_OPEN (jint)20

#define package_Command__SV_TRADE_ITEMS (jint)97

#define package_Command__SV_TRADE_OPEN (jint)92

#define package_Command__SV_TRADE_RECIPIENT_STATUS (jint)162

#define package_Command__SV_TRADE_STATUS (jint)15

#define package_Command__SV_WELCOME (jint)182

#define package_Command__SV_WORLD_INFO (jint)25

JCGO_NOSEP_STATIC package_Command CFASTCALL
package_Command__this__( package_Command This );

struct package_Command_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 package_Command (CFASTCALL *jcgo_thisRtn)( package_Command This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct package_Command_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct package_Command_methods_s package_Command_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct package_Command_class_s package_Command__class;

struct package_Command_s
{
 CONST struct package_Command_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype24_Object jcgo_array2_Command;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Command;

#endif
