/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_gnu_java_nio_charset_Cp424
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC gnu_java_nio_charset_Cp424 CFASTCALL
gnu_java_nio_charset_Cp424__this__( gnu_java_nio_charset_Cp424 This
 )
{
 {
  (gnu_java_nio_charset_ByteCharset__this__LsLsA((gnu_java_nio_charset_ByteCharset)This,
   JCGO_STRREF_OF(jcgo_string3_Cp424), (jObjectArr)jcgo_arrayClone((jObject)JCGO_OBJREF_OF(jcgo_array2_UncdBg))));
  JCGO_FIELD_NZACCESS(This, lookupTable)= gnu_java_nio_charset_Cp424__lookup;
 }
 return This;
}

JCGO_NOSEP_INLINE gnu_java_nio_charset_Cp424 CFASTCALL
gnu_java_nio_charset_Cp424__new__( void )
{
 return gnu_java_nio_charset_Cp424__this__(
  (gnu_java_nio_charset_Cp424)jcgo_newObject((jvtable)&gnu_java_nio_charset_Cp424_methods));
}

JCGO_NOSEP_DATA CONST struct gnu_java_nio_charset_Cp424_methods_s
 gnu_java_nio_charset_Cp424_methods=
{
 JCGO_CLASSREF_OF(gnu_java_nio_charset_Cp424__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_gnu_java_nio_charset_Cp424,
 (JCGO_OBJSIZE_T)sizeof(struct gnu_java_nio_charset_Cp424_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 gnu_java_nio_charset_Cp424__this__,
 java_nio_charset_Charset__equals__Lo,
 java_nio_charset_Charset__hashCode__,
 java_nio_charset_Charset__toString__,
 java_lang_Object__finalize__,
 gnu_java_nio_charset_ByteCharset__newDecoder__,
 gnu_java_nio_charset_ByteCharset__newEncoder__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct gnu_java_nio_charset_Cp424_class_s
 gnu_java_nio_charset_Cp424__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&gnu_java_nio_charset_Cp424_methods),
  JCGO_STRREF_OF(jcgo_string1_Cp424),
  JCGO_CLASSREF_OF(gnu_java_nio_charset_ByteCharset__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x101
 }
};

JCGO_NOSEP_DATA jcgo_arrtype39_CharData jcgo_array2_Cp424 ATTRIBNONGC=
{
 (jvtable)&jcharArr_methods,
 JCGO_MON_INIT
 256,
 {
  (jchar)0, (jchar)(jint)1, (jchar)(jint)2, (jchar)(jint)3, (jchar)(jint)156,
   (jchar)(jint)9, (jchar)(jint)134, (jchar)(jint)127, (jchar)(jint)151,
   (jchar)(jint)141, (jchar)(jint)142, (jchar)(jint)11, (jchar)(jint)12,
   (jchar)(jint)13, (jchar)(jint)14, (jchar)(jint)15, (jchar)(jint)16,
   (jchar)(jint)17, (jchar)(jint)18, (jchar)(jint)19, (jchar)(jint)157,
   (jchar)(jint)133, (jchar)(jint)8, (jchar)(jint)135, (jchar)(jint)24,
   (jchar)(jint)25, (jchar)(jint)146, (jchar)(jint)143, (jchar)(jint)28,
   (jchar)(jint)29, (jchar)(jint)30, (jchar)(jint)31, (jchar)(jint)128,
   (jchar)(jint)129, (jchar)(jint)130, (jchar)(jint)131, (jchar)(jint)132,
   (jchar)(jint)10, (jchar)(jint)23, (jchar)(jint)27, (jchar)(jint)136,
   (jchar)(jint)137, (jchar)(jint)138, (jchar)(jint)139, (jchar)(jint)140,
   (jchar)(jint)5, (jchar)(jint)6, (jchar)(jint)7, (jchar)(jint)144,
   (jchar)(jint)145, (jchar)(jint)22, (jchar)(jint)147, (jchar)(jint)148,
   (jchar)(jint)149, (jchar)(jint)150, (jchar)(jint)4, (jchar)(jint)152,
   (jchar)(jint)153, (jchar)(jint)154, (jchar)(jint)155, (jchar)(jint)20,
   (jchar)(jint)21, (jchar)(jint)158, (jchar)(jint)26, (jchar)(jint)32,
   (jchar)(jint)1488, (jchar)(jint)1489, (jchar)(jint)1490, (jchar)(jint)1491,
   (jchar)(jint)1492, (jchar)(jint)1493, (jchar)(jint)1494, (jchar)(jint)1495,
   (jchar)(jint)1496, (jchar)(jint)162, (jchar)(jint)46, (jchar)(jint)60,
   (jchar)(jint)40, (jchar)(jint)43, (jchar)(jint)124, (jchar)(jint)38,
   (jchar)(jint)1497, (jchar)(jint)1498, (jchar)(jint)1499, (jchar)(jint)1500,
   (jchar)(jint)1501, (jchar)(jint)1502, (jchar)(jint)1503, (jchar)(jint)1504,
   (jchar)(jint)1505, (jchar)(jint)33, (jchar)(jint)36, (jchar)(jint)42,
   (jchar)(jint)41, (jchar)(jint)59, (jchar)(jint)172, (jchar)(jint)45,
   (jchar)(jint)47, (jchar)(jint)1506, (jchar)(jint)1507, (jchar)(jint)1508,
   (jchar)(jint)1509, (jchar)(jint)1510, (jchar)(jint)1511, (jchar)(jint)1512,
   (jchar)(jint)1513, (jchar)(jint)166, (jchar)(jint)44, (jchar)(jint)37,
   (jchar)(jint)95, (jchar)(jint)62, (jchar)(jint)63, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)1514, gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)160, gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)8215, (jchar)(jint)96,
   (jchar)(jint)58, (jchar)(jint)35, (jchar)(jint)64, (jchar)(jint)39,
   (jchar)(jint)61, (jchar)(jint)34, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)97, (jchar)(jint)98, (jchar)(jint)99, (jchar)(jint)100,
   (jchar)(jint)101, (jchar)(jint)102, (jchar)(jint)103, (jchar)(jint)104,
   (jchar)(jint)105, (jchar)(jint)171, (jchar)(jint)187, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)177, (jchar)(jint)176, (jchar)(jint)106, (jchar)(jint)107,
   (jchar)(jint)108, (jchar)(jint)109, (jchar)(jint)110, (jchar)(jint)111,
   (jchar)(jint)112, (jchar)(jint)113, (jchar)(jint)114, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)184, gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)164,
   (jchar)(jint)181, (jchar)(jint)126, (jchar)(jint)115, (jchar)(jint)116,
   (jchar)(jint)117, (jchar)(jint)118, (jchar)(jint)119, (jchar)(jint)120,
   (jchar)(jint)121, (jchar)(jint)122, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)174, (jchar)(jint)94, (jchar)(jint)163, (jchar)(jint)165,
   (jchar)(jint)183, (jchar)(jint)169, (jchar)(jint)167, (jchar)(jint)182,
   (jchar)(jint)188, (jchar)(jint)189, (jchar)(jint)190, (jchar)(jint)91,
   (jchar)(jint)93, (jchar)(jint)175, (jchar)(jint)168, (jchar)(jint)180,
   (jchar)(jint)215, (jchar)(jint)123, (jchar)(jint)65, (jchar)(jint)66,
   (jchar)(jint)67, (jchar)(jint)68, (jchar)(jint)69, (jchar)(jint)70,
   (jchar)(jint)71, (jchar)(jint)72, (jchar)(jint)73, (jchar)(jint)173,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)125, (jchar)(jint)74,
   (jchar)(jint)75, (jchar)(jint)76, (jchar)(jint)77, (jchar)(jint)78,
   (jchar)(jint)79, (jchar)(jint)80, (jchar)(jint)81, (jchar)(jint)82,
   (jchar)(jint)185, gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)92, (jchar)(jint)247,
   (jchar)(jint)83, (jchar)(jint)84, (jchar)(jint)85, (jchar)(jint)86,
   (jchar)(jint)87, (jchar)(jint)88, (jchar)(jint)89, (jchar)(jint)90,
   (jchar)(jint)178, gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)48, (jchar)(jint)49,
   (jchar)(jint)50, (jchar)(jint)51, (jchar)(jint)52, (jchar)(jint)53,
   (jchar)(jint)54, (jchar)(jint)55, (jchar)(jint)56, (jchar)(jint)57,
   (jchar)(jint)179, gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)159
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype27_Object jcgo_array4_Cp424=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 26,
 {
  (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)118/*'v'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)52/*'4'*/,
   (jbyte)(jchar)50/*'2'*/, (jbyte)(jchar)52/*'4'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Cp424
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array4_Cp424),
 0, 26, (jint)0xb5cfd501L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_Cp424
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array4_Cp424),
 21, 5, (jint)0x3e3d9c9L
};

#ifdef CHKALL_gnu_java_nio_charset_Cp424
#include "jcgochke.h"
#endif

#endif
