/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_gnu_java_nio_charset_Cp737
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC gnu_java_nio_charset_Cp737 CFASTCALL
gnu_java_nio_charset_Cp737__this__( gnu_java_nio_charset_Cp737 This
 )
{
 {
  (gnu_java_nio_charset_ByteCharset__this__LsLsA((gnu_java_nio_charset_ByteCharset)This,
   JCGO_STRREF_OF(jcgo_string3_Cp737), (jObjectArr)jcgo_arrayClone((jObject)JCGO_OBJREF_OF(jcgo_array2_UncdBg))));
  JCGO_FIELD_NZACCESS(This, lookupTable)= gnu_java_nio_charset_Cp737__lookup;
 }
 return This;
}

JCGO_NOSEP_INLINE gnu_java_nio_charset_Cp737 CFASTCALL
gnu_java_nio_charset_Cp737__new__( void )
{
 return gnu_java_nio_charset_Cp737__this__(
  (gnu_java_nio_charset_Cp737)jcgo_newObject((jvtable)&gnu_java_nio_charset_Cp737_methods));
}

JCGO_NOSEP_DATA CONST struct gnu_java_nio_charset_Cp737_methods_s
 gnu_java_nio_charset_Cp737_methods=
{
 JCGO_CLASSREF_OF(gnu_java_nio_charset_Cp737__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_gnu_java_nio_charset_Cp737,
 (JCGO_OBJSIZE_T)sizeof(struct gnu_java_nio_charset_Cp737_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 gnu_java_nio_charset_Cp737__this__,
 java_nio_charset_Charset__equals__Lo,
 java_nio_charset_Charset__hashCode__,
 java_nio_charset_Charset__toString__,
 java_lang_Object__finalize__,
 gnu_java_nio_charset_ByteCharset__newDecoder__,
 gnu_java_nio_charset_ByteCharset__newEncoder__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct gnu_java_nio_charset_Cp737_class_s
 gnu_java_nio_charset_Cp737__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&gnu_java_nio_charset_Cp737_methods),
  JCGO_STRREF_OF(jcgo_string1_Cp737),
  JCGO_CLASSREF_OF(gnu_java_nio_charset_ByteCharset__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x101
 }
};

JCGO_NOSEP_DATA jcgo_arrtype39_CharData jcgo_array2_Cp737 ATTRIBNONGC=
{
 (jvtable)&jcharArr_methods,
 JCGO_MON_INIT
 256,
 {
  (jchar)0, (jchar)(jint)1, (jchar)(jint)2, (jchar)(jint)3, (jchar)(jint)4,
   (jchar)(jint)5, (jchar)(jint)6, (jchar)(jint)7, (jchar)(jint)8,
   (jchar)(jint)9, (jchar)(jint)10, (jchar)(jint)11, (jchar)(jint)12,
   (jchar)(jint)13, (jchar)(jint)14, (jchar)(jint)15, (jchar)(jint)16,
   (jchar)(jint)17, (jchar)(jint)18, (jchar)(jint)19, (jchar)(jint)20,
   (jchar)(jint)21, (jchar)(jint)22, (jchar)(jint)23, (jchar)(jint)24,
   (jchar)(jint)25, (jchar)(jint)26, (jchar)(jint)27, (jchar)(jint)28,
   (jchar)(jint)29, (jchar)(jint)30, (jchar)(jint)31, (jchar)(jint)32,
   (jchar)(jint)33, (jchar)(jint)34, (jchar)(jint)35, (jchar)(jint)36,
   (jchar)(jint)37, (jchar)(jint)38, (jchar)(jint)39, (jchar)(jint)40,
   (jchar)(jint)41, (jchar)(jint)42, (jchar)(jint)43, (jchar)(jint)44,
   (jchar)(jint)45, (jchar)(jint)46, (jchar)(jint)47, (jchar)(jint)48,
   (jchar)(jint)49, (jchar)(jint)50, (jchar)(jint)51, (jchar)(jint)52,
   (jchar)(jint)53, (jchar)(jint)54, (jchar)(jint)55, (jchar)(jint)56,
   (jchar)(jint)57, (jchar)(jint)58, (jchar)(jint)59, (jchar)(jint)60,
   (jchar)(jint)61, (jchar)(jint)62, (jchar)(jint)63, (jchar)(jint)64,
   (jchar)(jint)65, (jchar)(jint)66, (jchar)(jint)67, (jchar)(jint)68,
   (jchar)(jint)69, (jchar)(jint)70, (jchar)(jint)71, (jchar)(jint)72,
   (jchar)(jint)73, (jchar)(jint)74, (jchar)(jint)75, (jchar)(jint)76,
   (jchar)(jint)77, (jchar)(jint)78, (jchar)(jint)79, (jchar)(jint)80,
   (jchar)(jint)81, (jchar)(jint)82, (jchar)(jint)83, (jchar)(jint)84,
   (jchar)(jint)85, (jchar)(jint)86, (jchar)(jint)87, (jchar)(jint)88,
   (jchar)(jint)89, (jchar)(jint)90, (jchar)(jint)91, (jchar)(jint)92,
   (jchar)(jint)93, (jchar)(jint)94, (jchar)(jint)95, (jchar)(jint)96,
   (jchar)(jint)97, (jchar)(jint)98, (jchar)(jint)99, (jchar)(jint)100,
   (jchar)(jint)101, (jchar)(jint)102, (jchar)(jint)103, (jchar)(jint)104,
   (jchar)(jint)105, (jchar)(jint)106, (jchar)(jint)107, (jchar)(jint)108,
   (jchar)(jint)109, (jchar)(jint)110, (jchar)(jint)111, (jchar)(jint)112,
   (jchar)(jint)113, (jchar)(jint)114, (jchar)(jint)115, (jchar)(jint)116,
   (jchar)(jint)117, (jchar)(jint)118, (jchar)(jint)119, (jchar)(jint)120,
   (jchar)(jint)121, (jchar)(jint)122, (jchar)(jint)123, (jchar)(jint)124,
   (jchar)(jint)125, (jchar)(jint)126, (jchar)(jint)127, (jchar)(jint)913,
   (jchar)(jint)914, (jchar)(jint)915, (jchar)(jint)916, (jchar)(jint)917,
   (jchar)(jint)918, (jchar)(jint)919, (jchar)(jint)920, (jchar)(jint)921,
   (jchar)(jint)922, (jchar)(jint)923, (jchar)(jint)924, (jchar)(jint)925,
   (jchar)(jint)926, (jchar)(jint)927, (jchar)(jint)928, (jchar)(jint)929,
   (jchar)(jint)931, (jchar)(jint)932, (jchar)(jint)933, (jchar)(jint)934,
   (jchar)(jint)935, (jchar)(jint)936, (jchar)(jint)937, (jchar)(jint)945,
   (jchar)(jint)946, (jchar)(jint)947, (jchar)(jint)948, (jchar)(jint)949,
   (jchar)(jint)950, (jchar)(jint)951, (jchar)(jint)952, (jchar)(jint)953,
   (jchar)(jint)954, (jchar)(jint)955, (jchar)(jint)956, (jchar)(jint)957,
   (jchar)(jint)958, (jchar)(jint)959, (jchar)(jint)960, (jchar)(jint)961,
   (jchar)(jint)963, (jchar)(jint)962, (jchar)(jint)964, (jchar)(jint)965,
   (jchar)(jint)966, (jchar)(jint)967, (jchar)(jint)968, (jchar)(jint)9617,
   (jchar)(jint)9618, (jchar)(jint)9619, (jchar)(jint)9474, (jchar)(jint)9508,
   (jchar)(jint)9569, (jchar)(jint)9570, (jchar)(jint)9558, (jchar)(jint)9557,
   (jchar)(jint)9571, (jchar)(jint)9553, (jchar)(jint)9559, (jchar)(jint)9565,
   (jchar)(jint)9564, (jchar)(jint)9563, (jchar)(jint)9488, (jchar)(jint)9492,
   (jchar)(jint)9524, (jchar)(jint)9516, (jchar)(jint)9500, (jchar)(jint)9472,
   (jchar)(jint)9532, (jchar)(jint)9566, (jchar)(jint)9567, (jchar)(jint)9562,
   (jchar)(jint)9556, (jchar)(jint)9577, (jchar)(jint)9574, (jchar)(jint)9568,
   (jchar)(jint)9552, (jchar)(jint)9580, (jchar)(jint)9575, (jchar)(jint)9576,
   (jchar)(jint)9572, (jchar)(jint)9573, (jchar)(jint)9561, (jchar)(jint)9560,
   (jchar)(jint)9554, (jchar)(jint)9555, (jchar)(jint)9579, (jchar)(jint)9578,
   (jchar)(jint)9496, (jchar)(jint)9484, (jchar)(jint)9608, (jchar)(jint)9604,
   (jchar)(jint)9612, (jchar)(jint)9616, (jchar)(jint)9600, (jchar)(jint)969,
   (jchar)(jint)940, (jchar)(jint)941, (jchar)(jint)942, (jchar)(jint)970,
   (jchar)(jint)943, (jchar)(jint)972, (jchar)(jint)973, (jchar)(jint)971,
   (jchar)(jint)974, (jchar)(jint)902, (jchar)(jint)904, (jchar)(jint)905,
   (jchar)(jint)906, (jchar)(jint)908, (jchar)(jint)910, (jchar)(jint)911,
   (jchar)(jint)177, (jchar)(jint)8805, (jchar)(jint)8804, (jchar)(jint)938,
   (jchar)(jint)939, (jchar)(jint)247, (jchar)(jint)8776, (jchar)(jint)176,
   (jchar)(jint)8729, (jchar)(jint)183, (jchar)(jint)8730, (jchar)(jint)8319,
   (jchar)(jint)178, (jchar)(jint)9632, (jchar)(jint)160
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype27_Object jcgo_array4_Cp737=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 26,
 {
  (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)118/*'v'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)55/*'7'*/,
   (jbyte)(jchar)51/*'3'*/, (jbyte)(jchar)55/*'7'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Cp737
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array4_Cp737),
 0, 26, (jint)0xb5cfe066L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_Cp737
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array4_Cp737),
 21, 5, (jint)0x3e3e52eL
};

#ifdef CHKALL_gnu_java_nio_charset_Cp737
#include "jcgochke.h"
#endif

#endif
