/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_gnu_java_nio_charset_Cp864
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC gnu_java_nio_charset_Cp864 CFASTCALL
gnu_java_nio_charset_Cp864__this__( gnu_java_nio_charset_Cp864 This
 )
{
 {
  (gnu_java_nio_charset_ByteCharset__this__LsLsA((gnu_java_nio_charset_ByteCharset)This,
   JCGO_STRREF_OF(jcgo_string3_Cp864), (jObjectArr)jcgo_arrayClone((jObject)JCGO_OBJREF_OF(jcgo_array5_Cp864))));
  JCGO_FIELD_NZACCESS(This, lookupTable)= gnu_java_nio_charset_Cp864__lookup;
 }
 return This;
}

JCGO_NOSEP_INLINE gnu_java_nio_charset_Cp864 CFASTCALL
gnu_java_nio_charset_Cp864__new__( void )
{
 return gnu_java_nio_charset_Cp864__this__(
  (gnu_java_nio_charset_Cp864)jcgo_newObject((jvtable)&gnu_java_nio_charset_Cp864_methods));
}

JCGO_NOSEP_DATA CONST struct gnu_java_nio_charset_Cp864_methods_s
 gnu_java_nio_charset_Cp864_methods=
{
 JCGO_CLASSREF_OF(gnu_java_nio_charset_Cp864__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_gnu_java_nio_charset_Cp864,
 (JCGO_OBJSIZE_T)sizeof(struct gnu_java_nio_charset_Cp864_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 gnu_java_nio_charset_Cp864__this__,
 java_nio_charset_Charset__equals__Lo,
 java_nio_charset_Charset__hashCode__,
 java_nio_charset_Charset__toString__,
 java_lang_Object__finalize__,
 gnu_java_nio_charset_ByteCharset__newDecoder__,
 gnu_java_nio_charset_ByteCharset__newEncoder__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct gnu_java_nio_charset_Cp864_class_s
 gnu_java_nio_charset_Cp864__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&gnu_java_nio_charset_Cp864_methods),
  JCGO_STRREF_OF(jcgo_string1_Cp864),
  JCGO_CLASSREF_OF(gnu_java_nio_charset_ByteCharset__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x101
 }
};

JCGO_NOSEP_DATA jcgo_arrtype39_CharData jcgo_array2_Cp864 ATTRIBNONGC=
{
 (jvtable)&jcharArr_methods,
 JCGO_MON_INIT
 256,
 {
  (jchar)0, (jchar)(jint)1, (jchar)(jint)2, (jchar)(jint)3, (jchar)(jint)4,
   (jchar)(jint)5, (jchar)(jint)6, (jchar)(jint)7, (jchar)(jint)8,
   (jchar)(jint)9, (jchar)(jint)10, (jchar)(jint)11, (jchar)(jint)12,
   (jchar)(jint)13, (jchar)(jint)14, (jchar)(jint)15, (jchar)(jint)16,
   (jchar)(jint)17, (jchar)(jint)18, (jchar)(jint)19, (jchar)(jint)20,
   (jchar)(jint)21, (jchar)(jint)22, (jchar)(jint)23, (jchar)(jint)24,
   (jchar)(jint)25, (jchar)(jint)26, (jchar)(jint)27, (jchar)(jint)28,
   (jchar)(jint)29, (jchar)(jint)30, (jchar)(jint)31, (jchar)(jint)32,
   (jchar)(jint)33, (jchar)(jint)34, (jchar)(jint)35, (jchar)(jint)36,
   (jchar)(jint)1642, (jchar)(jint)38, (jchar)(jint)39, (jchar)(jint)40,
   (jchar)(jint)41, (jchar)(jint)42, (jchar)(jint)43, (jchar)(jint)44,
   (jchar)(jint)45, (jchar)(jint)46, (jchar)(jint)47, (jchar)(jint)48,
   (jchar)(jint)49, (jchar)(jint)50, (jchar)(jint)51, (jchar)(jint)52,
   (jchar)(jint)53, (jchar)(jint)54, (jchar)(jint)55, (jchar)(jint)56,
   (jchar)(jint)57, (jchar)(jint)58, (jchar)(jint)59, (jchar)(jint)60,
   (jchar)(jint)61, (jchar)(jint)62, (jchar)(jint)63, (jchar)(jint)64,
   (jchar)(jint)65, (jchar)(jint)66, (jchar)(jint)67, (jchar)(jint)68,
   (jchar)(jint)69, (jchar)(jint)70, (jchar)(jint)71, (jchar)(jint)72,
   (jchar)(jint)73, (jchar)(jint)74, (jchar)(jint)75, (jchar)(jint)76,
   (jchar)(jint)77, (jchar)(jint)78, (jchar)(jint)79, (jchar)(jint)80,
   (jchar)(jint)81, (jchar)(jint)82, (jchar)(jint)83, (jchar)(jint)84,
   (jchar)(jint)85, (jchar)(jint)86, (jchar)(jint)87, (jchar)(jint)88,
   (jchar)(jint)89, (jchar)(jint)90, (jchar)(jint)91, (jchar)(jint)92,
   (jchar)(jint)93, (jchar)(jint)94, (jchar)(jint)95, (jchar)(jint)96,
   (jchar)(jint)97, (jchar)(jint)98, (jchar)(jint)99, (jchar)(jint)100,
   (jchar)(jint)101, (jchar)(jint)102, (jchar)(jint)103, (jchar)(jint)104,
   (jchar)(jint)105, (jchar)(jint)106, (jchar)(jint)107, (jchar)(jint)108,
   (jchar)(jint)109, (jchar)(jint)110, (jchar)(jint)111, (jchar)(jint)112,
   (jchar)(jint)113, (jchar)(jint)114, (jchar)(jint)115, (jchar)(jint)116,
   (jchar)(jint)117, (jchar)(jint)118, (jchar)(jint)119, (jchar)(jint)120,
   (jchar)(jint)121, (jchar)(jint)122, (jchar)(jint)123, (jchar)(jint)124,
   (jchar)(jint)125, (jchar)(jint)126, (jchar)(jint)127, (jchar)(jint)176,
   (jchar)(jint)183, (jchar)(jint)8729, (jchar)(jint)8730, (jchar)(jint)9618,
   (jchar)(jint)9472, (jchar)(jint)9474, (jchar)(jint)9532, (jchar)(jint)9508,
   (jchar)(jint)9516, (jchar)(jint)9500, (jchar)(jint)9524, (jchar)(jint)9488,
   (jchar)(jint)9484, (jchar)(jint)9492, (jchar)(jint)9496, (jchar)(jint)946,
   (jchar)(jint)8734, (jchar)(jint)966, (jchar)(jint)177, (jchar)(jint)189,
   (jchar)(jint)188, (jchar)(jint)8776, (jchar)(jint)171, (jchar)(jint)187,
   (jchar)(jint)65271L, (jchar)(jint)65272L, gnu_java_nio_charset_ByteCharset__NONE,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)65275L, (jchar)(jint)65276L,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)160, (jchar)(jint)173,
   (jchar)(jint)65154L, (jchar)(jint)163, (jchar)(jint)164, (jchar)(jint)65156L,
   gnu_java_nio_charset_ByteCharset__NONE, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)65166L, (jchar)(jint)65167L, (jchar)(jint)65173L, (jchar)(jint)65177L,
   (jchar)(jint)1548, (jchar)(jint)65181L, (jchar)(jint)65185L, (jchar)(jint)65189L,
   (jchar)(jint)1632, (jchar)(jint)1633, (jchar)(jint)1634, (jchar)(jint)1635,
   (jchar)(jint)1636, (jchar)(jint)1637, (jchar)(jint)1638, (jchar)(jint)1639,
   (jchar)(jint)1640, (jchar)(jint)1641, (jchar)(jint)65233L, (jchar)(jint)1563,
   (jchar)(jint)65201L, (jchar)(jint)65205L, (jchar)(jint)65209L, (jchar)(jint)1567,
   (jchar)(jint)162, (jchar)(jint)65152L, (jchar)(jint)65153L, (jchar)(jint)65155L,
   (jchar)(jint)65157L, (jchar)(jint)65226L, (jchar)(jint)65163L, (jchar)(jint)65165L,
   (jchar)(jint)65169L, (jchar)(jint)65171L, (jchar)(jint)65175L, (jchar)(jint)65179L,
   (jchar)(jint)65183L, (jchar)(jint)65187L, (jchar)(jint)65191L, (jchar)(jint)65193L,
   (jchar)(jint)65195L, (jchar)(jint)65197L, (jchar)(jint)65199L, (jchar)(jint)65203L,
   (jchar)(jint)65207L, (jchar)(jint)65211L, (jchar)(jint)65215L, (jchar)(jint)65217L,
   (jchar)(jint)65221L, (jchar)(jint)65227L, (jchar)(jint)65231L, (jchar)(jint)166,
   (jchar)(jint)172, (jchar)(jint)247, (jchar)(jint)215, (jchar)(jint)65225L,
   (jchar)(jint)1600, (jchar)(jint)65235L, (jchar)(jint)65239L, (jchar)(jint)65243L,
   (jchar)(jint)65247L, (jchar)(jint)65251L, (jchar)(jint)65255L, (jchar)(jint)65259L,
   (jchar)(jint)65261L, (jchar)(jint)65263L, (jchar)(jint)65267L, (jchar)(jint)65213L,
   (jchar)(jint)65228L, (jchar)(jint)65230L, (jchar)(jint)65229L, (jchar)(jint)65249L,
   (jchar)(jint)65149L, (jchar)(jint)1617, (jchar)(jint)65253L, (jchar)(jint)65257L,
   (jchar)(jint)65260L, (jchar)(jint)65264L, (jchar)(jint)65266L, (jchar)(jint)65232L,
   (jchar)(jint)65237L, (jchar)(jint)65269L, (jchar)(jint)65270L, (jchar)(jint)65245L,
   (jchar)(jint)65241L, (jchar)(jint)65265L, (jchar)(jint)9632, gnu_java_nio_charset_ByteCharset__NONE
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype2_GameMdl jcgo_array5_Cp864=
{
 (jvtable)&jObjectArr_methods,
 JCGO_MON_INIT
 1,
 JCGO_CLASSREF_OF(java_lang_String__class),
 {
  (jObject)JCGO_STRREF_OF(jcgo_string4_Cp864)
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype27_Object jcgo_array6_Cp864=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 26,
 {
  (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)118/*'v'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)56/*'8'*/,
   (jbyte)(jchar)54/*'6'*/, (jbyte)(jchar)52/*'4'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype2_BZLib jcgo_array7_Cp864=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 6,
 {
  (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)45/*'-'*/,
   (jbyte)(jchar)56/*'8'*/, (jbyte)(jchar)54/*'6'*/, (jbyte)(jchar)52/*'4'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Cp864
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array6_Cp864),
 0, 26, (jint)0xb5cfe481L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_Cp864
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array6_Cp864),
 21, 5, (jint)0x3e3e949L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_Cp864
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array7_Cp864),
 0, 6, (jint)0x789447b6L
};

#ifdef CHKALL_gnu_java_nio_charset_Cp864
#include "jcgochke.h"
#endif

#endif
