/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_Collections
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_util_Collections_EmptySet CFASTCALL
java_util_Collections_EmptySet__this__( java_util_Collections_EmptySet
 This )
{
 {
  (java_util_AbstractSet__this__((java_util_AbstractSet)This));
 }
 return This;
}

JCGO_NOSEP_FRWINL java_util_Collections_EmptySet CFASTCALL
java_util_Collections_EmptySet__new__( void )
{
 return java_util_Collections_EmptySet__this__(
  (java_util_Collections_EmptySet)jcgo_newObject((jvtable)&java_util_Collections_EmptySet_methods));
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_util_Collections_EmptySet__size__( java_util_Collections_EmptySet
 This )
{
 {
  return 0;
 }
}

JCGO_NOSEP_INLINE java_util_Iterator CFASTCALL
java_util_Collections_EmptySet__iterator__( java_util_Collections_EmptySet
 This )
{
 {
  return (java_util_AbstractList__iterator__(
   (java_util_AbstractList)JCGO_CLINIT_VARACC(java_util_Collections__class,
   java_util_Collections__EMPTY_LIST)));
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_Collections_EmptySet__contains__Lo( java_util_Collections_EmptySet
 This, java_lang_Object o )
{
 {
  return (jboolean)jfalse;
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_Collections_EmptySet__containsAll__L07mt2( java_util_Collections_EmptySet
 This, java_util_Collection c )
{
 {
  return (jboolean)(JCGO_CALL_VFUNC(c)->isEmpty__(
   c));
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_Collections_EmptySet__equals__Lo( java_util_Collections_EmptySet
 This, java_lang_Object o )
{
 {
  return (jboolean)(jcgo_instanceOf(OBJT_java_util_Set, MAXT_java_util_Set,
   ~0, (jObject)o) && (JCGO_CALL_NZVFUNC(((java_util_Set)o))->isEmpty__(
   ((java_util_Set)o))));
 }
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_util_Collections_EmptySet__hashCode__( java_util_Collections_EmptySet
 This )
{
 {
  return 0;
 }
}

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_util_Collections_EmptySet__toString__( java_util_Collections_EmptySet
 This )
{
 {
  return JCGO_STRREF_OF(jcgo_string2_EmptyMap);
 }
}

JCGO_NOSEP_DATA CONST struct java_util_Collections_EmptySet_methods_s
 java_util_Collections_EmptySet_methods=
{
 JCGO_CLASSREF_OF(java_util_Collections_EmptySet__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_util_Collections_EmptySet,
 -(JCGO_OBJSIZE_T)sizeof(struct java_util_Collections_EmptySet_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 java_util_Collections_EmptySet__this__,
 java_util_Collections_EmptySet__equals__Lo,
 java_util_Collections_EmptySet__hashCode__,
 java_util_Collections_EmptySet__toString__,
 java_lang_Object__finalize__,
 java_util_AbstractCollection__isEmpty__,
 java_util_Collections_EmptySet__iterator__,
 java_util_Collections_EmptySet__size__,
 java_util_AbstractCollection__add__Lo,
 java_util_Collections_EmptySet__contains__Lo,
 java_util_Collections_EmptySet__containsAll__L07mt2
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_util_Collections_EmptySet_class_s
 java_util_Collections_EmptySet__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_Collections_EmptySet_methods),
  JCGO_STRREF_OF(jcgo_string1_EmptySet),
  JCGO_CLASSREF_OF(java_util_AbstractSet__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1a
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype77_GmCnnctn jcgo_array2_EmptySet=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 30,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)36/*'$'*/, (jbyte)(jchar)69/*'E'*/, (jbyte)(jchar)109/*'m'*/,
   (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)121/*'y'*/,
   (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_EmptySet
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_EmptySet),
 0, 30, (jint)0xe7581be4L
};

#ifdef CHKALL_java_util_Collections
#include "jcgochke.h"
#endif

#endif
