/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_io_FileInputStream
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_io_FileInputStream CFASTCALL
java_io_FileInputStream__this__L6745c( java_io_FileInputStream This,
 java_io_File file )
{
 {
  java_lang_SecurityManager s;
  (java_io_InputStream__this__((java_io_InputStream)This));
  s= (java_lang_System__getSecurityManager__());
  if (s != jnull)
  {
   (java_lang_SecurityManager__checkRead__Ls(
    s, (JCGO_CALL_FINALF(file) java_io_File__getPath__(
    file))));
  }
  {
   JCGO_TRY_BLOCK
   {
    JCGO_FIELD_NZACCESS(This, ch)= (gnu_java_nio_FileChannelImpl__create__L6745cI(
     file, gnu_java_nio_FileChannelImpl__READ));
   }
   JCGO_TRY_LEAVE
   JCGO_TRY_CATCHES(1)
   JCGO_TRY_CATCH(OBJT_java_io_FileNotFoundException, MAXT_java_io_FileNotFoundException)
   {
    java_io_FileNotFoundException fnfe;
    fnfe= (java_io_FileNotFoundException)JCGO_TRY_THROWABLE(0);
    JCGO_THROW_EXC(fnfe);
   }
   JCGO_TRY_CATCH(OBJT_java_io_IOException, MAXT_java_io_IOException)
   {
    java_io_IOException ioe;
    java_io_FileNotFoundException fnfe;
    ioe= (java_io_IOException)JCGO_TRY_THROWABLE(0);
    fnfe= (java_io_FileNotFoundException__new__Ls(
     (JCGO_CALL_FINALF(file) java_io_File__getPath__(
     file))));
    (java_lang_Throwable__initCause__Lt(
     (java_lang_Throwable)fnfe, (java_lang_Throwable)ioe));
    JCGO_THROW_EXC(fnfe);
   }
   JCGO_TRY_RETHROW(1)
  }
 }
 return This;
}

JCGO_NOSEP_INLINE java_io_FileInputStream CFASTCALL
java_io_FileInputStream__new__L6745c( java_io_File file )
{
 return java_io_FileInputStream__this__L6745c(
  (java_io_FileInputStream)jcgo_newObject((jvtable)&java_io_FileInputStream_methods),
  file);
}

JCGO_NOSEP_INLINE java_io_FileInputStream CFASTCALL
java_io_FileInputStream__this__Ls( java_io_FileInputStream This, java_lang_String
 name )
{
 {
  struct java_io_File_s jcgo_stackobj1;
  (java_io_FileInputStream__this__L6745c((java_io_FileInputStream)This,
   (java_io_File__this__Ls(
   JCGO_STACKOBJVLT_NEWTRIG(jcgo_stackobj1, java_io_File_methods),
   name))));
 }
 return This;
}

JCGO_NOSEP_FRWINL java_io_FileInputStream CFASTCALL
java_io_FileInputStream__new__Ls( java_lang_String name )
{
 return java_io_FileInputStream__this__Ls(
  (java_io_FileInputStream)jcgo_newObject((jvtable)&java_io_FileInputStream_methods),
  name);
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_io_FileInputStream__available__( java_io_FileInputStream This
 )
{
 {
  jObject jcgo_rcvrL1;
  return (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, ch), JCGO_CALL_FINALF((gnu_java_nio_FileChannelImpl)jcgo_rcvrL1)
   gnu_java_nio_FileChannelImpl__available__(
   (gnu_java_nio_FileChannelImpl)jcgo_rcvrL1));
 }
}

JCGO_NOSEP_INLINE void CFASTCALL
java_io_FileInputStream__close__( java_io_FileInputStream This )
{
 {
  jObject jcgo_rcvrL1;
  (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, ch), JCGO_CALL_FINALF((gnu_java_nio_FileChannelImpl)jcgo_rcvrL1)
   java_nio_channels_spi_AbstractInterruptibleChannel__close__(
   (java_nio_channels_spi_AbstractInterruptibleChannel)jcgo_rcvrL1));
 }
}

JCGO_NOSEP_INLINE void CFASTCALL
java_io_FileInputStream__finalize__( java_io_FileInputStream This
 )
{
 {
 }
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_io_FileInputStream__read__( java_io_FileInputStream This )
{
 {
  jObject jcgo_rcvrL1;
  return (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, ch), JCGO_CALL_FINALF((gnu_java_nio_FileChannelImpl)jcgo_rcvrL1)
   gnu_java_nio_FileChannelImpl__read__(
   (gnu_java_nio_FileChannelImpl)jcgo_rcvrL1));
 }
}

JCGO_NOSEP_STATIC jint CFASTCALL
java_io_FileInputStream__read__BAII( java_io_FileInputStream This,
 jbyteArr buf, jint offset, jint len )
{
 {
  jObject jcgo_rcvrL1;
  struct java_nio_ByteBufferImpl_s jcgo_stackobj1;
  if (offset < 0 || len < 0 || offset + len > JCGO_ARRAY_LENGTH(buf))
  {
   JCGO_THROW_EXC(java_lang_ArrayIndexOutOfBoundsException__new__());
  }
  return (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, ch), JCGO_CALL_FINALF((gnu_java_nio_FileChannelImpl)jcgo_rcvrL1)
   gnu_java_nio_FileChannelImpl__read__L9oaia(
   (gnu_java_nio_FileChannelImpl)jcgo_rcvrL1, (java_nio_ByteBuffer__wrap__BAIIX(
   buf, offset, len, JCGO_STACKOBJVLT_NEW(jcgo_stackobj1, java_nio_ByteBufferImpl_methods)))));
 }
}

JCGO_NOSEP_DATA CONST struct java_io_FileInputStream_methods_s java_io_FileInputStream_methods=
{
 JCGO_CLASSREF_OF(java_io_FileInputStream__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_io_FileInputStream,
 (JCGO_OBJSIZE_T)sizeof(struct java_io_FileInputStream_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 (void (CFASTCALL*)(java_io_FileInputStream))java_lang_Object__finalize__,
 java_io_FileInputStream__available__,
 java_io_FileInputStream__close__,
 java_io_FileInputStream__read__,
 java_io_FileInputStream__read__BAII
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_io_FileInputStream_class_s
 java_io_FileInputStream__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_io_FileInputStream_methods),
  JCGO_STRREF_OF(jcgo_string1_FlInptSt),
  JCGO_CLASSREF_OF(java_io_InputStream__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype91_GmCnnctn jcgo_array2_FlInptSt=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 23,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)70/*'F'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)73/*'I'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)112/*'p'*/,
   (jbyte)(jchar)117/*'u'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)83/*'S'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)109/*'m'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_FlInptSt
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_FlInptSt),
 0, 23, (jint)0x89d97732L
};

#ifdef CHKALL_java_io_FileInputStream
#include "jcgochke.h"
#endif

#endif
