/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE void CFASTCALL
java_io_FilePermission__void( java_io_FilePermission This );

JCGO_NOSEP_INLINE void CFASTCALL
java_io_FilePermission__checkPerms__( java_io_FilePermission This
 );

JCGO_NOSEP_INLINE java_io_FilePermission CFASTCALL
java_io_FilePermission__this__LsLs( java_io_FilePermission This, java_lang_String
 pathExpression, java_lang_String actionsString );
JCGO_NOSEP_INLINE java_io_FilePermission CFASTCALL
java_io_FilePermission__new__LsLs( java_lang_String pathExpression,
 java_lang_String actionsString );

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_io_FilePermission__getActions__( java_io_FilePermission This
 );

JCGO_NOSEP_INLINE jint CFASTCALL
java_io_FilePermission__hashCode__( java_io_FilePermission This );

JCGO_NOSEP_STATIC jboolean CFASTCALL
java_io_FilePermission__equals__Lo( java_io_FilePermission This, java_lang_Object
 o );

struct java_io_FilePermission_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_io_FilePermission (CFASTCALL *jcgo_thisRtn)( java_io_FilePermission
  This );
 jboolean (CFASTCALL *equals__Lo)( java_io_FilePermission This, java_lang_Object
  o );
 jint (CFASTCALL *hashCode__)( java_io_FilePermission This );
 java_lang_String (CFASTCALL *toString__)( java_security_Permission
  This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 java_lang_String (CFASTCALL *getActions__)( java_io_FilePermission
  This );
};

struct java_io_FilePermission_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_io_FilePermission_methods_s java_io_FilePermission_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_io_FilePermission_class_s
 java_io_FilePermission__class;

struct java_io_FilePermission_s
{
 CONST struct java_io_FilePermission_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
 java_lang_String name;
 java_lang_String actionsString;
 jboolean readPerm;
 jboolean writePerm;
 jboolean executePerm;
 jboolean deletePerm;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype44_GameShll jcgo_array9_FlPrmssn;

JCGO_SEP_EXTERN CONST jcgo_arrtype31_GameShll jcgo_array10_FlPrmssn;

JCGO_SEP_EXTERN CONST jcgo_arrtype24_Object jcgo_array11_FlPrmssn;

JCGO_SEP_EXTERN CONST jcgo_arrtype2_BZLib jcgo_array12_FlPrmssn;

JCGO_SEP_EXTERN CONST jcgo_arrtype22_Object jcgo_array13_FlPrmssn;

JCGO_SEP_EXTERN CONST jcgo_arrtype63_GmCnnctn jcgo_array14_FlPrmssn;

JCGO_SEP_EXTERN CONST jcgo_arrtype30_GameShll jcgo_array15_FlPrmssn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_FlPrmssn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_FlPrmssn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_FlPrmssn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_FlPrmssn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string5_FlPrmssn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string6_FlPrmssn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string7_FlPrmssn;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string8_FlPrmssn;

#endif
