/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_io_FilterInputStream
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_io_FilterInputStream CFASTCALL
java_io_FilterInputStream__this__L0gpra( java_io_FilterInputStream
 This, java_io_InputStream in )
{
 {
  (java_io_InputStream__this__((java_io_InputStream)This));
  JCGO_FIELD_NZACCESS(This, in)= in;
 }
 return This;
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_io_FilterInputStream__available__( java_io_FilterInputStream
 This )
{
 {
  jObject jcgo_rcvrL1;
  return (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, in), JCGO_CALL_VFUNC((java_io_InputStream)jcgo_rcvrL1)->available__(
   (java_io_InputStream)jcgo_rcvrL1));
 }
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_io_FilterInputStream__read__( java_io_FilterInputStream This
 )
{
 {
  jObject jcgo_rcvrL1;
  return (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, in), JCGO_CALL_VFUNC((java_io_InputStream)jcgo_rcvrL1)->read__(
   (java_io_InputStream)jcgo_rcvrL1));
 }
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_io_FilterInputStream__read__BAII( java_io_FilterInputStream This,
 jbyteArr buf, jint offset, jint len )
{
 {
  jObject jcgo_rcvrL1;
  return (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, in), JCGO_CALL_VFUNC((java_io_InputStream)jcgo_rcvrL1)->read__BAII(
   (java_io_InputStream)jcgo_rcvrL1, buf, offset, len));
 }
}

JCGO_NOSEP_FRWINL void CFASTCALL
java_io_FilterInputStream__close__( java_io_FilterInputStream This
 )
{
 {
  jObject jcgo_rcvrL1;
  (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, in), JCGO_CALL_VFUNC((java_io_InputStream)jcgo_rcvrL1)->close__(
   (java_io_InputStream)jcgo_rcvrL1));
 }
}

JCGO_NOSEP_DATA CONST struct java_io_FilterInputStream_methods_s java_io_FilterInputStream_methods=
{
 JCGO_CLASSREF_OF(java_io_FilterInputStream__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_io_FilterInputStream,
 (JCGO_OBJSIZE_T)sizeof(struct java_io_FilterInputStream_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__,
 java_io_FilterInputStream__available__,
 java_io_FilterInputStream__close__,
 java_io_FilterInputStream__read__,
 java_io_FilterInputStream__read__BAII
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_io_FilterInputStream_class_s
 java_io_FilterInputStream__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_io_FilterInputStream_methods),
  JCGO_STRREF_OF(jcgo_string1_FltrInSt),
  JCGO_CLASSREF_OF(java_io_InputStream__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype108_GmCnnctn jcgo_array2_FltrInSt=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 25,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)70/*'F'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)73/*'I'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)109/*'m'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_FltrInSt
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_FltrInSt),
 0, 25, (jint)0xd46442b6L
};

#ifdef CHKALL_java_io_FilterInputStream
#include "jcgochke.h"
#endif

#endif
