/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_Hashtable
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_util_Hashtable_HashEntry CFASTCALL
java_util_Hashtable_HashEntry__this__LoLoI( java_util_Hashtable_HashEntry
 This, java_lang_Object key, java_lang_Object value, jint hash )
{
 {
  ;
  JCGO_FIELD_NZACCESS(This, key)= key;
  JCGO_FIELD_NZACCESS(This, value)= value;
  JCGO_FIELD_NZACCESS(This, hash)= hash;
 }
 return This;
}

JCGO_NOSEP_FRWINL java_util_Hashtable_HashEntry CFASTCALL
java_util_Hashtable_HashEntry__new__LoLoI( java_lang_Object key, java_lang_Object
 value, jint hash )
{
 return java_util_Hashtable_HashEntry__this__LoLoI(
  (java_util_Hashtable_HashEntry)jcgo_newObject((jvtable)&java_util_Hashtable_HashEntry_methods),
  key, value, hash);
}

JCGO_NOSEP_INLINE java_lang_Object CFASTCALL
java_util_Hashtable_HashEntry__getKey__( java_util_Hashtable_HashEntry
 This )
{
 {
  return JCGO_FIELD_NZACCESS(This, key);
 }
}

JCGO_NOSEP_INLINE java_lang_Object CFASTCALL
java_util_Hashtable_HashEntry__getValue__( java_util_Hashtable_HashEntry
 This )
{
 {
  return JCGO_FIELD_NZACCESS(This, value);
 }
}

JCGO_NOSEP_STATIC jboolean CFASTCALL
java_util_Hashtable_HashEntry__equals__Lo( java_util_Hashtable_HashEntry
 This, java_lang_Object o )
{
 {
  java_util_Map_Entry e;
  jObject jcgo_rcvrL1;
  if (!jcgo_instanceOf(OBJT_java_util_Map_Entry, MAXT_java_util_Map_Entry,
   ~0, (jObject)o))
  {
   return (jboolean)jfalse;
  }
  e= (java_util_Map_Entry)o;
  return (jboolean)((jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This,
   key), JCGO_CALL_VFUNC((java_lang_Object)jcgo_rcvrL1)->equals__Lo(
   (java_lang_Object)jcgo_rcvrL1, (JCGO_CALL_NZVFUNC(e)->getKey__(
   e)))) && (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, value),
   JCGO_CALL_VFUNC((java_lang_Object)jcgo_rcvrL1)->equals__Lo(
   (java_lang_Object)jcgo_rcvrL1, (JCGO_CALL_NZVFUNC(e)->getValue__(
   e)))));
 }
}

JCGO_NOSEP_FRWINL jint CFASTCALL
java_util_Hashtable_HashEntry__hashCode__( java_util_Hashtable_HashEntry
 This )
{
 {
  jObject jcgo_rcvrL1;
  jint jcgo_rcvrI1;
  return (jcgo_rcvrI1= (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This,
   value), JCGO_CALL_VFUNC((java_lang_Object)jcgo_rcvrL1)->hashCode__(
   (java_lang_Object)jcgo_rcvrL1)), jcgo_rcvrI1 ^ JCGO_FIELD_NZACCESS(This,
   hash));
 }
}

JCGO_NOSEP_FRWINL java_lang_String CFASTCALL
java_util_Hashtable_HashEntry__toString__X( java_util_Hashtable_HashEntry
 This, java_lang_String jcgo_stackparam )
{
 {
  jObject jcgo_rcvrL1;
  jObject jcgo_rcvrL2;
  struct java_lang_StringBuilder_s jcgo_stackobj1;
  return (jcgo_rcvrL1= (jObject)java_lang_StringBuilder__append__Ls(
   java_lang_StringBuilder__append__Ls(
   java_lang_StringBuilder__this__(
   JCGO_STACKOBJ_NEW(jcgo_stackobj1, java_lang_StringBuilder_methods)),
   (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, key), JCGO_CALL_VFUNC((java_lang_Object)jcgo_rcvrL1)->toString__(
   (java_lang_Object)jcgo_rcvrL1))), JCGO_STRREF_OF(jcgo_string2_HashEntr)),
   java_lang_String__this__L5dy9e(
   jcgo_stackparam, java_lang_StringBuilder__append__Ls(
   (java_lang_StringBuilder)jcgo_rcvrL1, (jcgo_rcvrL2= (jObject)JCGO_FIELD_NZACCESS(This,
   value), JCGO_CALL_VFUNC((java_lang_Object)jcgo_rcvrL2)->toString__(
   (java_lang_Object)jcgo_rcvrL2)))));
 }
}

JCGO_NOSEP_FRWINL java_lang_String CFASTCALL
java_util_Hashtable_HashEntry__toString__( java_util_Hashtable_HashEntry
 This )
{
 return java_util_Hashtable_HashEntry__toString__X(This, (java_lang_String)jcgo_newObject((jvtable)&java_lang_String_methods));
}

JCGO_NOSEP_DATA CONST struct java_util_Hashtable_HashEntry_methods_s
 java_util_Hashtable_HashEntry_methods=
{
 JCGO_CLASSREF_OF(java_util_Hashtable_HashEntry__class),
 JCGO_GCJDESCR_INIT(java_util_Hashtable_HashEntry_s, value)
 OBJT_java_util_Hashtable_HashEntry,
 (JCGO_OBJSIZE_T)sizeof(struct java_util_Hashtable_HashEntry_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_util_Hashtable_HashEntry__equals__Lo,
 java_util_Hashtable_HashEntry__hashCode__,
 java_util_Hashtable_HashEntry__toString__,
 java_lang_Object__finalize__,
 java_util_Hashtable_HashEntry__getKey__,
 java_util_Hashtable_HashEntry__getValue__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_util_Hashtable_HashEntry_class_s
 java_util_Hashtable_HashEntry__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_Hashtable_HashEntry_methods),
  JCGO_STRREF_OF(jcgo_string1_HashEntr),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_HashEntr)),
  0x1a
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype2_GameMdl jcgo_array3_HashEntr=
{
 (jvtable)&jObjectArr_methods,
 JCGO_MON_INIT
 1,
 JCGO_CLASSREF_OF(java_lang_Class__class),
 {
  (jObject)JCGO_CLASSREF_OF(java_util_Map_Entry__class)
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype86_GmCnnctn jcgo_array4_HashEntr=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 29,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)72/*'H'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)98/*'b'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)36/*'$'*/, (jbyte)(jchar)72/*'H'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)69/*'E'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)121/*'y'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype86_GmCnnctn jcgo_array5_HashEntr=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 29,
 {
  (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)79/*'O'*/, (jbyte)(jchar)95/*'_'*/,
   (jbyte)(jchar)84/*'T'*/, (jbyte)(jchar)73/*'I'*/, (jbyte)(jchar)77/*'M'*/,
   (jbyte)(jchar)69/*'E'*/, (jbyte)(jchar)79/*'O'*/, (jbyte)(jchar)85/*'U'*/,
   (jbyte)(jchar)84/*'T'*/, (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)109/*'m'*/,
   (jbyte)(jchar)117/*'u'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)98/*'b'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)62/*'>'*/, (jbyte)(jchar)61/*'='*/,
   (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)48/*'0'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_HashEntr
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array4_HashEntr),
 0, 29, (jint)0xcea90a00L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_HashEntr
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array5_HashEntr),
 26, 1, (jint)0x3dL
};

#ifdef CHKALL_java_util_Hashtable
#include "jcgochke.h"
#endif

#endif
