/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_HashSet
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE java_util_HashMap CFASTCALL
java_util_HashSet__init__I( java_util_HashSet This, jint capacity
 )
{
 {
  return (java_util_HashMap__new__I(
   capacity));
 }
}

JCGO_NOSEP_STATIC java_util_HashSet CFASTCALL
java_util_HashSet__this__I( java_util_HashSet This, jint initialCapacity
 )
{
 {
  (java_util_AbstractSet__this__((java_util_AbstractSet)This));
  JCGO_FIELD_NZACCESS(This, map)= (java_util_HashSet__init__I(
   This, initialCapacity));
 }
 return This;
}

JCGO_NOSEP_FRWINL java_util_HashSet CFASTCALL
java_util_HashSet__new__I( jint initialCapacity )
{
 return java_util_HashSet__this__I(
  (java_util_HashSet)jcgo_newObject((jvtable)&java_util_HashSet_methods),
  initialCapacity);
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_util_HashSet__divBy075__I( jint size )
{
 {
  return size / (jint)3 + size;
 }
}

JCGO_NOSEP_INLINE java_util_HashSet CFASTCALL
java_util_HashSet__this__( java_util_HashSet This )
{
 {
  (java_util_HashSet__this__I((java_util_HashSet)This, java_util_HashMap__DEFAULT_CAPACITY));
 }
 return This;
}

JCGO_NOSEP_INLINE java_util_HashSet CFASTCALL
java_util_HashSet__this__L07mt2( java_util_HashSet This, java_util_Collection
 c )
{
 {
  (java_util_HashSet__this__I((java_util_HashSet)This, (java_lang_Math__max__II(
   (java_util_HashSet__divBy075__I(
   (JCGO_CALL_VFUNC(c)->size__(
   c)))) + (jint)1, java_util_HashMap__DEFAULT_CAPACITY))));
  (java_util_AbstractCollection__addAll__L07mt2(
   (java_util_AbstractCollection)This, c));
 }
 return This;
}

JCGO_NOSEP_INLINE java_util_HashSet CFASTCALL
java_util_HashSet__new__L07mt2( java_util_Collection c )
{
 return java_util_HashSet__this__L07mt2(
  (java_util_HashSet)jcgo_newObject((jvtable)&java_util_HashSet_methods),
  c);
}

JCGO_NOSEP_FRWINL jboolean CFASTCALL
java_util_HashSet__add__Lo( java_util_HashSet This, java_lang_Object
 o )
{
 {
  jObject jcgo_rcvrL1;
  return (jboolean)((jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This,
   map), JCGO_CALL_FINALF((java_util_HashMap)jcgo_rcvrL1) java_util_HashMap__put__LoLo(
   (java_util_HashMap)jcgo_rcvrL1, o, (java_lang_Object)JCGO_STRREF_OF(jcgo_string3_String6D))) ==
   jnull);
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_HashSet__contains__Lo( java_util_HashSet This, java_lang_Object
 o )
{
 {
  jObject jcgo_rcvrL1;
  return (jboolean)(jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This,
   map), JCGO_CALL_FINALF((java_util_HashMap)jcgo_rcvrL1) java_util_HashMap__containsKey__Lo(
   (java_util_HashMap)jcgo_rcvrL1, o));
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_HashSet__isEmpty__( java_util_HashSet This )
{
 {
  return (jboolean)(JCGO_FIELD_ACCESS(java_util_HashMap, JCGO_FIELD_NZACCESS(This,
   map), size) == 0);
 }
}

JCGO_NOSEP_INLINE java_util_Iterator CFASTCALL
java_util_HashSet__iterator__( java_util_HashSet This )
{
 {
  jObject jcgo_rcvrL1;
  return (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, map), JCGO_CALL_FINALF((java_util_HashMap)jcgo_rcvrL1)
   java_util_HashMap__iterator__I(
   (java_util_HashMap)jcgo_rcvrL1, java_util_AbstractMap__KEYS));
 }
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_util_HashSet__size__( java_util_HashSet This )
{
 {
  return JCGO_FIELD_ACCESS(java_util_HashMap, JCGO_FIELD_NZACCESS(This,
   map), size);
 }
}

JCGO_NOSEP_DATA CONST struct java_util_HashSet_methods_s java_util_HashSet_methods=
{
 JCGO_CLASSREF_OF(java_util_HashSet__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_util_HashSet,
 (JCGO_OBJSIZE_T)sizeof(struct java_util_HashSet_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 java_util_HashSet__this__,
 java_util_AbstractSet__equals__Lo,
 java_util_AbstractSet__hashCode__,
 java_util_AbstractCollection__toString__,
 java_lang_Object__finalize__,
 java_util_HashSet__isEmpty__,
 java_util_HashSet__iterator__,
 java_util_HashSet__size__,
 java_util_HashSet__add__Lo,
 java_util_HashSet__contains__Lo,
 java_util_AbstractCollection__containsAll__L07mt2
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_util_HashSet_class_s
 java_util_HashSet__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_HashSet_methods),
  JCGO_STRREF_OF(jcgo_string1_HashSet),
  JCGO_CLASSREF_OF(java_util_AbstractSet__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array2_HashSet)),
  0x1
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype5_Hshtbl jcgo_array2_HashSet=
{
 (jvtable)&jObjectArr_methods,
 JCGO_MON_INIT
 2,
 JCGO_CLASSREF_OF(java_lang_Class__class),
 {
  (jObject)JCGO_CLASSREF_OF(java_util_Set__class), (jObject)JCGO_CLASSREF_OF(java_lang_Cloneable__class)
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype492_Mdclnt jcgo_array3_HashSet=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 17,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)72/*'H'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)83/*'S'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_HashSet
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array3_HashSet),
 0, 17, (jint)0xac643eb4L
};

#ifdef CHKALL_java_util_HashSet
#include "jcgochke.h"
#endif

#endif
