/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE void CFASTCALL
java_util_HashMap_HashIterator__void( java_util_HashMap_HashIterator
 This );

JCGO_NOSEP_STATIC java_util_HashMap_HashIterator CFASTCALL
java_util_HashMap_HashIterator__this__L8hkr7I( java_util_HashMap_HashIterator
 This, java_util_HashMap this_0, jint type );
JCGO_NOSEP_FRWINL java_util_HashMap_HashIterator CFASTCALL
java_util_HashMap_HashIterator__new__L8hkr7I( java_util_HashMap this_0,
 jint type );

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_HashMap_HashIterator__hasNext__( java_util_HashMap_HashIterator
 This );

JCGO_NOSEP_STATIC java_lang_Object CFASTCALL
java_util_HashMap_HashIterator__next__( java_util_HashMap_HashIterator
 This );

JCGO_NOSEP_STATIC void CFASTCALL
java_util_HashMap_HashIterator__remove__( java_util_HashMap_HashIterator
 This );

struct java_util_HashMap_HashIterator_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_util_HashMap_HashIterator (CFASTCALL *jcgo_thisRtn)( java_util_HashMap_HashIterator
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 jboolean (CFASTCALL *hasNext__)( java_util_HashMap_HashIterator This
  );
 java_lang_Object (CFASTCALL *next__)( java_util_HashMap_HashIterator
  This );
 void (CFASTCALL *remove__)( java_util_HashMap_HashIterator This );
};

struct java_util_HashMap_HashIterator_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_util_HashMap_HashIterator_methods_s
 java_util_HashMap_HashIterator_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_util_HashMap_HashIterator_class_s
 java_util_HashMap_HashIterator__class;

struct java_util_HashMap_HashIterator_s
{
 CONST struct java_util_HashMap_HashIterator_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
 java_util_HashMap this_0;
 java_util_HashMap_HashEntry last;
 java_util_HashMap_HashEntry next;
 jint type;
 jint knownMod;
 jint count;
 jint idx;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype77_GmCnnctn jcgo_array2_HshItrtr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_HshItrtr;

#endif
