/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_Hashtable
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE jint CFASTCALL
java_util_Hashtable_3__size__( java_util_Hashtable_3 This )
{
 {
  return JCGO_FIELD_NZACCESS(JCGO_FIELD_NZACCESS(This, this_0), size);
 }
}

JCGO_NOSEP_INLINE java_util_Iterator CFASTCALL
java_util_Hashtable_3__iterator__( java_util_Hashtable_3 This )
{
 {
  return (java_util_Iterator)(java_util_Hashtable_EntryIterator__new__L76hud(
   JCGO_FIELD_NZACCESS(This, this_0)));
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_Hashtable_3__contains__Lo( java_util_Hashtable_3 This, java_lang_Object
 o )
{
 {
  return (jboolean)((java_util_Hashtable__getEntry__Lo(
   JCGO_FIELD_NZACCESS(This, this_0), o)) != jnull);
 }
}

JCGO_NOSEP_INLINE java_util_Hashtable_3 CFASTCALL
java_util_Hashtable_3__this__L76hud( java_util_Hashtable_3 This, java_util_Hashtable
 this_0 )
{
 {
  JCGO_FIELD_NZACCESS(This, this_0)= this_0;
  (java_util_AbstractSet__this__((java_util_AbstractSet)This));
 }
 return This;
}

JCGO_NOSEP_FRWINL java_util_Hashtable_3 CFASTCALL
java_util_Hashtable_3__new__L76hud( java_util_Hashtable this_0 )
{
 return java_util_Hashtable_3__this__L76hud(
  (java_util_Hashtable_3)jcgo_newObject((jvtable)&java_util_Hashtable_3_methods),
  this_0);
}

JCGO_NOSEP_DATA CONST struct java_util_Hashtable_3_methods_s java_util_Hashtable_3_methods=
{
 JCGO_CLASSREF_OF(java_util_Hashtable_3__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_util_Hashtable_3,
 (JCGO_OBJSIZE_T)sizeof(struct java_util_Hashtable_3_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_util_AbstractSet__equals__Lo,
 java_util_AbstractSet__hashCode__,
 java_util_AbstractCollection__toString__,
 java_lang_Object__finalize__,
 java_util_AbstractCollection__isEmpty__,
 java_util_Hashtable_3__iterator__,
 java_util_Hashtable_3__size__,
 java_util_AbstractCollection__add__Lo,
 java_util_Hashtable_3__contains__Lo,
 java_util_AbstractCollection__containsAll__L07mt2
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_util_Hashtable_3_class_s
 java_util_Hashtable_3__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_Hashtable_3_methods),
  JCGO_STRREF_OF(jcgo_string1_Hshtbl3),
  JCGO_CLASSREF_OF(java_util_AbstractSet__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x0
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Hshtbl3
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array6_Hshtbl),
 0, 21, (jint)0x180cf64fL
};

#ifdef CHKALL_java_util_Hashtable
#include "jcgochke.h"
#endif

#endif
