/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

#define java_net_Inet6Address__AF_INET60 (jint)10

JCGO_NOSEP_INLINE java_net_Inet6Address CFASTCALL
java_net_Inet6Address__this__BALs( java_net_Inet6Address This, jbyteArr
 addr, java_lang_String host );
JCGO_NOSEP_FRWINL java_net_Inet6Address CFASTCALL
java_net_Inet6Address__new__BALs( jbyteArr addr, java_lang_String
 host );

JCGO_NOSEP_INLINE jbyteArr CFASTCALL
java_net_Inet6Address__getAddress__( java_net_Inet6Address This );

JCGO_NOSEP_STATIC java_lang_String CFASTCALL
java_net_Inet6Address__getHostAddress__( java_net_Inet6Address This
 );

JCGO_NOSEP_STATIC jboolean CFASTCALL
java_net_Inet6Address__equals__Lo( java_net_Inet6Address This, java_lang_Object
 obj );

struct java_net_Inet6Address_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_net_Inet6Address (CFASTCALL *jcgo_thisRtn)( java_net_Inet6Address
  This );
 jboolean (CFASTCALL *equals__Lo)( java_net_Inet6Address This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_net_InetAddress This );
 java_lang_String (CFASTCALL *toString__)( java_net_InetAddress This
  );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 jbyteArr (CFASTCALL *getAddress__)( java_net_Inet6Address This );
 java_lang_String (CFASTCALL *getHostAddress__)( java_net_Inet6Address
  This );
};

struct java_net_Inet6Address_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_net_Inet6Address_methods_s java_net_Inet6Address_methods;
JCGO_SEP_EXTERN struct java_net_Inet6Address_class_s java_net_Inet6Address__class;

JCGO_NOSEP_STATIC void CFASTCALL
java_net_Inet6Address__class__0( void );

struct java_net_Inet6Address_s
{
 CONST struct java_net_Inet6Address_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
 jbyteArr addr;
 java_lang_String hostName;
 jbyteArr ipaddress;
 java_lang_Object nif;
 jint scope_id;
 jboolean scope_id_set;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype80_GmCnnctn jcgo_array2_Int6Addr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Int6Addr;

#endif
