/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

struct java_util_Iterator_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_util_Iterator (CFASTCALL *jcgo_thisRtn)( java_util_Iterator This
  );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 jboolean (CFASTCALL *hasNext__)( java_util_Iterator This );
 java_lang_Object (CFASTCALL *next__)( java_util_Iterator This );
 void (CFASTCALL *remove__)( java_util_Iterator This );
};

struct java_util_Iterator_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct jcgo_methods_s java_util_Iterator_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_util_Iterator_class_s
 java_util_Iterator__class;

struct java_util_Iterator_s
{
 CONST struct java_util_Iterator_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype82_GmCnnctn jcgo_array2_Itrtr68;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Itrtr68;

#endif
