/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_KeyEvent
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC package_KeyEvent CFASTCALL
package_KeyEvent__this__( package_KeyEvent This )
{
 {
  ;
 }
 return This;
}

JCGO_NOSEP_DATA CONST struct package_KeyEvent_methods_s package_KeyEvent_methods=
{
 JCGO_CLASSREF_OF(package_KeyEvent__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_package_KeyEvent,
 -(JCGO_OBJSIZE_T)sizeof(struct package_KeyEvent_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 package_KeyEvent__this__,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct package_KeyEvent_class_s package_KeyEvent__class
 JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&package_KeyEvent_methods),
  JCGO_STRREF_OF(jcgo_string1_KeyEvent),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x0
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype31_GameShll jcgo_array2_KeyEvent=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 8,
 {
  (jbyte)(jchar)75/*'K'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)121/*'y'*/,
   (jbyte)(jchar)69/*'E'*/, (jbyte)(jchar)118/*'v'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)116/*'t'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_KeyEvent
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_KeyEvent),
 0, 8, (jint)0x204b6b9bL
};

#ifdef CHKALL_KeyEvent
#include "jcgochke.h"
#endif

#endif
