/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_lang_NoSuchFieldError
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_lang_NoSuchFieldError CFASTCALL
java_lang_NoSuchFieldError__this__( java_lang_NoSuchFieldError This
 )
{
 {
  (java_lang_IncompatibleClassChangeError__this__((java_lang_IncompatibleClassChangeError)This));
 }
 return This;
}

JCGO_NOSEP_INLINE java_lang_NoSuchFieldError CFASTCALL
java_lang_NoSuchFieldError__this__Ls( java_lang_NoSuchFieldError This,
 java_lang_String s )
{
 {
  (java_lang_IncompatibleClassChangeError__this__Ls((java_lang_IncompatibleClassChangeError)This,
   s));
 }
 return This;
}

JCGO_NOSEP_INLINE java_lang_NoSuchFieldError CFASTCALL
java_lang_NoSuchFieldError__new__Ls( java_lang_String s )
{
 return java_lang_NoSuchFieldError__this__Ls(
  (java_lang_NoSuchFieldError)jcgo_newObject((jvtable)&java_lang_NoSuchFieldError_methods),
  s);
}

JCGO_NOSEP_DATA CONST struct java_lang_NoSuchFieldError_methods_s
 java_lang_NoSuchFieldError_methods=
{
 JCGO_CLASSREF_OF(java_lang_NoSuchFieldError__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_lang_NoSuchFieldError,
 (JCGO_OBJSIZE_T)sizeof(struct java_lang_NoSuchFieldError_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 java_lang_NoSuchFieldError__this__,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Throwable__toString__,
 java_lang_Object__finalize__,
 java_lang_Throwable__getMessage__,
 java_lang_Throwable__getCause__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_NoSuchFieldError_class_s
 java_lang_NoSuchFieldError__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_lang_NoSuchFieldError_methods),
  JCGO_STRREF_OF(jcgo_string1_NSchFlEr),
  JCGO_CLASSREF_OF(java_lang_IncompatibleClassChangeError__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype27_Object jcgo_array2_NSchFlEr=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 26,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)103/*'g'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)78/*'N'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)117/*'u'*/, (jbyte)(jchar)99/*'c'*/,
   (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)70/*'F'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)100/*'d'*/,
   (jbyte)(jchar)69/*'E'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)114/*'r'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)114/*'r'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_NSchFlEr
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_NSchFlEr),
 0, 26, (jint)0x50daf84aL
};

#ifdef CHKALL_java_lang_NoSuchFieldError
#include "jcgochke.h"
#endif

#endif
