/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE jint CFASTCALL
package_Packet__availableStream__( package_Packet This );

JCGO_NOSEP_INLINE jint CFASTCALL
package_Packet__readStream__( package_Packet This );

JCGO_NOSEP_INLINE void CFASTCALL
package_Packet__readBytes__IBA( package_Packet This, jbyteArr buff,
 jint len );

JCGO_NOSEP_INLINE void CFASTCALL
package_Packet__writeStreamBytes__BAII( package_Packet This, jbyteArr
 abyte0, jint i, jint j );

JCGO_NOSEP_INLINE jint CFASTCALL
package_Packet__getByte__( package_Packet This );

JCGO_NOSEP_INLINE void CFASTCALL
package_Packet__readStreamBytes__IIBA( package_Packet This, jbyteArr
 abyte0, jint i, jint j );

JCGO_NOSEP_STATIC package_Packet CFASTCALL
package_Packet__this__( package_Packet This );

JCGO_NOSEP_FRWINL void CFASTCALL
package_Packet__seedIsaac__IA( package_Packet This, jintArr seed );

JCGO_NOSEP_INLINE void CFASTCALL
package_Packet__closeStream__( package_Packet This );

JCGO_NOSEP_FRWINL jint CFASTCALL
package_Packet__readPacket__BA( package_Packet This, jbyteArr buff
 );

JCGO_NOSEP_FRWINL jboolean CFASTCALL
package_Packet__hasPacket__( package_Packet This );

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__writePacket__I( package_Packet This, jint i );

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__sendPacket__( package_Packet This );

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__putBytes__BAII( package_Packet This, jbyteArr src,
 jint srcPos, jint len );

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__putLong__J( package_Packet This, jlong l );

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__newPacket__I( package_Packet This, jint i );

JCGO_NOSEP_FRWINL jlong CFASTCALL
package_Packet__getLong__( package_Packet This );

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__putShort__I( package_Packet This, jint i );

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__putInt__I( package_Packet This, jint i );

JCGO_NOSEP_STATIC jint CFASTCALL
package_Packet__getShort__( package_Packet This );

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__putString__Ls( package_Packet This, java_lang_String
 s );

JCGO_NOSEP_FRWINL void CFASTCALL
package_Packet__putByte__I( package_Packet This, jint i );

JCGO_NOSEP_FRWINL jint CFASTCALL
package_Packet__isaacCommand__I( package_Packet This, jint i );

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__flushPacket__( package_Packet This );

struct package_Packet_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 package_Packet (CFASTCALL *jcgo_thisRtn)( package_Packet This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 void (CFASTCALL *jcgo_dummy1)( void );
 jint (CFASTCALL *availableStream__)( package_Packet This );
 void (CFASTCALL *readStreamBytes__IIBA)( package_Packet This, jbyteArr
  abyte0, jint i, jint j );
 void (CFASTCALL *writeStreamBytes__BAII)( package_Packet This, jbyteArr
  abyte0, jint i, jint j );
 jint (CFASTCALL *readStream__)( package_Packet This );
};

struct package_Packet_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct package_Packet_methods_s package_Packet_methods;
JCGO_SEP_EXTERN struct package_Packet_class_s package_Packet__class;

JCGO_NOSEP_STATIC void CFASTCALL
package_Packet__class__0( void );

JCGO_SEP_GCEXTERN jintArr package_Packet__anIntArray537;
JCGO_SEP_GCEXTERN jintArr package_Packet__anIntArray541;

struct package_Packet_s
{
 CONST struct package_Packet_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
 jbyteArr packetData;
 java_lang_String socketExceptionMessage;
 jint readTries;
 jint maxReadTries;
 jint packetStart;
 jint length;
 jint packetMaxLength;
 jint delay;
 jint packetEnd;
 jint packet8Check;
 jboolean socketException;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype2_BZLib jcgo_array3_Packet;

JCGO_SEP_EXTERN CONST jcgo_arrtype31_GameShll jcgo_array4_Packet;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Packet;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_Packet;

#endif
