/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_Polygon
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC package_Polygon CFASTCALL
package_Polygon__this__( package_Polygon This )
{
 {
  ;
  JCGO_FIELD_NZACCESS(This, skipSomething)= (jboolean)jfalse;
  JCGO_FIELD_NZACCESS(This, index2)= (-(jint)1);
 }
 return This;
}

JCGO_NOSEP_FRWINL package_Polygon CFASTCALL
package_Polygon__new__( void )
{
 return package_Polygon__this__(
  (package_Polygon)jcgo_newObject((jvtable)&package_Polygon_methods));
}

JCGO_NOSEP_DATA CONST struct package_Polygon_methods_s package_Polygon_methods=
{
 JCGO_CLASSREF_OF(package_Polygon__class),
 JCGO_GCJDESCR_INIT(package_Polygon_s, model)
 OBJT_package_Polygon,
 (JCGO_OBJSIZE_T)sizeof(struct package_Polygon_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 package_Polygon__this__,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct package_Polygon_class_s package_Polygon__class
 JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&package_Polygon_methods),
  JCGO_STRREF_OF(jcgo_string1_Polygon),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype24_Object jcgo_array2_Polygon=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 7,
 {
  (jbyte)(jchar)80/*'P'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)121/*'y'*/, (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)110/*'n'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Polygon
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_Polygon),
 0, 7, (jint)0x4b86ed1aL
};

#ifdef CHKALL_Polygon
#include "jcgochke.h"
#endif

#endif
