/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_io_PrintStream
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE void CFASTCALL
java_io_PrintStream__void( java_io_PrintStream This )
{
 jObject jcgo_rcvrL1;
 JCGO_FIELD_NZACCESS(This, line_separator)= (jcgo_rcvrL1= (jObject)(gnu_classpath_SystemProperties__getProperty__LsLs(
  JCGO_STRREF_OF(jcgo_string2_PrntStrm), JCGO_STRREF_OF(jcgo_string3_PrntStrm))),
  JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL1) java_lang_String__toCharArray__(
  (java_lang_String)jcgo_rcvrL1));
}

JCGO_NOSEP_INLINE void CFASTCALL
java_io_PrintStream__ensureOpen__( java_io_PrintStream This )
{
 {
  if (JCGO_FIELD_NZACCESS(This, out) == jnull)
  {
   JCGO_THROW_EXC((java_io_IOException__new__Ls(
    JCGO_STRREF_OF(jcgo_string4_PrntStrm))));
  }
 }
}

JCGO_NOSEP_INLINE void CFASTCALL
java_io_PrintStream__writeChars__CA( java_io_PrintStream This, jcharArr
 buf )
{
 {
  jObject jcgo_rcvrL1;
  (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, charOut), JCGO_CALL_FINALF((java_io_OutputStreamWriter)jcgo_rcvrL1)
   java_io_OutputStreamWriter__write__CAII(
   (java_io_OutputStreamWriter)jcgo_rcvrL1, buf, 0, JCGO_ARRAY_LENGTH(buf)));
 }
}

JCGO_NOSEP_INLINE void CFASTCALL
java_io_PrintStream__writeChars__Ls( java_io_PrintStream This, java_lang_String
 str )
{
 {
  (java_io_PrintStream__writeChars__CA(
   This, (JCGO_CALL_FINALF(str) java_lang_String__toCharArray__(
   str))));
 }
}

JCGO_NOSEP_INLINE void CFASTCALL
java_io_PrintStream__setInterrupted__( void )
{
 {
  (java_lang_Thread__interrupt__(
   (java_lang_Thread__currentThread__())));
 }
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_io_PrintStream__lastIndexOfNewLine__CA( jcharArr chars )
{
 {
  jint i;
  i= JCGO_ARRAY_LENGTH(chars);
  while (i-- > 0)
  {
   if (JCGO_ARRAY_NZCACCESS(chars, i) == (jchar)10)
   {
    break;
   }
  }
  return i;
 }
}

JCGO_NOSEP_INLINE void CFASTCALL
java_io_PrintStream__print__CAZ( java_io_PrintStream This, jcharArr
 chars, jboolean println )
{
 JCGO_SYNC_BLOCKSAFENZ(This)
 {
  {
   JCGO_TRY_BLOCK
   {
    (java_io_PrintStream__ensureOpen__(
     This));
    (java_io_PrintStream__writeChars__CA(
     This, chars));
    if (println)
    {
     (java_io_PrintStream__writeChars__CA(
      This, JCGO_FIELD_NZACCESS(This, line_separator)));
    }
    (java_io_OutputStreamWriter__flushBuffer__(
     JCGO_FIELD_NZACCESS(This, charOut)));
    if (JCGO_FIELD_NZACCESS(This, auto_flush) && (println || chars ==
     JCGO_FIELD_NZACCESS(This, line_separator) || (java_io_PrintStream__lastIndexOfNewLine__CA(
     chars)) >= 0))
    {
     jObject jcgo_rcvrL1;
     (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, out), JCGO_CALL_VFUNC((java_io_OutputStream)jcgo_rcvrL1)->flush__(
      (java_io_OutputStream)jcgo_rcvrL1));
    }
   }
   JCGO_TRY_LEAVE
   JCGO_TRY_CATCHES(1)
   JCGO_TRY_CATCH(OBJT_java_io_InterruptedIOException, MAXT_java_io_InterruptedIOException)
   {
    (java_io_PrintStream__setInterrupted__());
   }
   JCGO_TRY_CATCH(OBJT_java_io_IOException, MAXT_java_io_IOException)
   {
    (void)jtrue;
   }
   JCGO_TRY_RETHROW(1)
  }
 }
 JCGO_SYNC_END
}

JCGO_NOSEP_STATIC java_io_PrintStream CFASTCALL
java_io_PrintStream__this__L0rv4gZLs( java_io_PrintStream This, java_io_OutputStream
 out, java_lang_String encoding, jboolean auto_flush )
{
 {
  (java_io_FilterOutputStream__this__L0rv4g((java_io_FilterOutputStream)This,
   out));
  java_io_PrintStream__void(This);
  if (out == jnull)
  {
   JCGO_THROW_EXC(java_lang_NullPointerException__new__());
  }
  JCGO_FIELD_NZACCESS(This, auto_flush)= (jboolean)auto_flush;
  JCGO_FIELD_NZACCESS(This, charOut)= (java_io_OutputStreamWriter__new__L0rv4gLs(
   (java_io_OutputStream)This, encoding));
 }
 return This;
}

JCGO_NOSEP_FRWINL java_io_PrintStream CFASTCALL
java_io_PrintStream__new__L0rv4gZLs( java_io_OutputStream out, java_lang_String
 encoding, jboolean auto_flush )
{
 return java_io_PrintStream__this__L0rv4gZLs(
  (java_io_PrintStream)jcgo_newObject((jvtable)&java_io_PrintStream_methods),
  out, encoding, auto_flush);
}

JCGO_NOSEP_STATIC void CFASTCALL
java_io_PrintStream__close__( java_io_PrintStream This )
{
 JCGO_SYNC_BLOCKSAFENZ(This)
 {
  if (JCGO_FIELD_NZACCESS(This, closing))
  {
#ifndef JCGO_SEHTRY
   JCGO_SYNC_JUMPLEAVE(0);
#endif
   return;
  }
  JCGO_FIELD_NZACCESS(This, closing)= (jboolean)jtrue;
  {
   JCGO_TRY_BLOCK
   {
    java_io_OutputStream out;
    out= JCGO_FIELD_NZACCESS(This, out);
    if (out != jnull)
    {
     jObject jcgo_rcvrL1;
     (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, charOut), JCGO_CALL_FINALF((java_io_OutputStreamWriter)jcgo_rcvrL1)
      java_io_OutputStreamWriter__close__(
      (java_io_OutputStreamWriter)jcgo_rcvrL1));
     (JCGO_CALL_NZVFUNC(out)->close__(
      out));
     JCGO_FIELD_NZACCESS(This, out)= (java_io_OutputStream)jnull;
    }
   }
   JCGO_TRY_LEAVE
   JCGO_TRY_CATCHES(1)
   JCGO_TRY_CATCH(OBJT_java_io_IOException, MAXT_java_io_IOException)
   {
    (void)jtrue;
   }
   JCGO_TRY_RETHROW(1)
  }
 }
 JCGO_SYNC_END
}

JCGO_NOSEP_STATIC void CFASTCALL
java_io_PrintStream__flush__( java_io_PrintStream This )
{
 JCGO_SYNC_BLOCKSAFENZ(This)
 {
  {
   JCGO_TRY_BLOCK
   {
    jObject jcgo_rcvrL1;
    (java_io_PrintStream__ensureOpen__(
     This));
    (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, out), JCGO_CALL_VFUNC((java_io_OutputStream)jcgo_rcvrL1)->flush__(
     (java_io_OutputStream)jcgo_rcvrL1));
   }
   JCGO_TRY_LEAVE
   JCGO_TRY_CATCHES(1)
   JCGO_TRY_CATCH(OBJT_java_io_IOException, MAXT_java_io_IOException)
   {
    (void)jtrue;
   }
   JCGO_TRY_RETHROW(1)
  }
 }
 JCGO_SYNC_END
}

JCGO_NOSEP_STATIC void CFASTCALL
java_io_PrintStream__print__LsZ( java_io_PrintStream This, java_lang_String
 str, jboolean println )
{
 JCGO_SYNC_BLOCKSAFENZ(This)
 {
  {
   JCGO_TRY_BLOCK
   {
    (java_io_PrintStream__ensureOpen__(
     This));
    (java_io_PrintStream__writeChars__Ls(
     This, str));
    if (println)
    {
     (java_io_PrintStream__writeChars__CA(
      This, JCGO_FIELD_NZACCESS(This, line_separator)));
    }
    (java_io_OutputStreamWriter__flushBuffer__(
     JCGO_FIELD_NZACCESS(This, charOut)));
    if (JCGO_FIELD_NZACCESS(This, auto_flush) && (println || (java_lang_String__lastIndexOf__I(
     str, (jchar)10)) >= 0))
    {
     jObject jcgo_rcvrL1;
     (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, out), JCGO_CALL_VFUNC((java_io_OutputStream)jcgo_rcvrL1)->flush__(
      (java_io_OutputStream)jcgo_rcvrL1));
    }
   }
   JCGO_TRY_LEAVE
   JCGO_TRY_CATCHES(1)
   JCGO_TRY_CATCH(OBJT_java_io_InterruptedIOException, MAXT_java_io_InterruptedIOException)
   {
    (java_io_PrintStream__setInterrupted__());
   }
   JCGO_TRY_CATCH(OBJT_java_io_IOException, MAXT_java_io_IOException)
   {
    (void)jtrue;
   }
   JCGO_TRY_RETHROW(1)
  }
 }
 JCGO_SYNC_END
}

JCGO_NOSEP_INLINE void CFASTCALL
java_io_PrintStream__print__Ls( java_io_PrintStream This, java_lang_String
 str )
{
 {
  (java_io_PrintStream__print__LsZ(
   This, str == jnull? JCGO_STRREF_OF(jcgo_string5_String6D) : str,
   (jboolean)jfalse));
 }
}

JCGO_NOSEP_INLINE void CFASTCALL
java_io_PrintStream__println__( java_io_PrintStream This )
{
 {
  (java_io_PrintStream__print__CAZ(
   This, JCGO_FIELD_NZACCESS(This, line_separator), (jboolean)jfalse));
 }
}

JCGO_NOSEP_FRWINL void CFASTCALL
java_io_PrintStream__println__Ls( java_io_PrintStream This, java_lang_String
 str )
{
 {
  (java_io_PrintStream__print__LsZ(
   This, str == jnull? JCGO_STRREF_OF(jcgo_string5_String6D) : str,
   (jboolean)jtrue));
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_io_PrintStream__write__BAII( java_io_PrintStream This, jbyteArr
 buffer, jint offset, jint len )
{
 JCGO_SYNC_BLOCKSAFENZ(This)
 {
  {
   JCGO_TRY_BLOCK
   {
    jObject jcgo_rcvrL1;
    (java_io_PrintStream__ensureOpen__(
     This));
    (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, out), JCGO_CALL_VFUNC((java_io_OutputStream)jcgo_rcvrL1)->write__BAII(
     (java_io_OutputStream)jcgo_rcvrL1, buffer, offset, len));
    if (JCGO_FIELD_NZACCESS(This, auto_flush))
    {
     jObject jcgo_rcvrL1;
     (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, out), JCGO_CALL_VFUNC((java_io_OutputStream)jcgo_rcvrL1)->flush__(
      (java_io_OutputStream)jcgo_rcvrL1));
    }
   }
   JCGO_TRY_LEAVE
   JCGO_TRY_CATCHES(1)
   JCGO_TRY_CATCH(OBJT_java_io_InterruptedIOException, MAXT_java_io_InterruptedIOException)
   {
    (java_io_PrintStream__setInterrupted__());
   }
   JCGO_TRY_CATCH(OBJT_java_io_IOException, MAXT_java_io_IOException)
   {
    (void)jtrue;
   }
   JCGO_TRY_RETHROW(1)
  }
 }
 JCGO_SYNC_END
}

JCGO_NOSEP_DATA CONST struct java_io_PrintStream_methods_s java_io_PrintStream_methods=
{
 JCGO_CLASSREF_OF(java_io_PrintStream__class),
 JCGO_GCJDESCR_INIT(java_io_PrintStream_s, charOut)
 OBJT_java_io_PrintStream,
 (JCGO_OBJSIZE_T)sizeof(struct java_io_PrintStream_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__,
 java_io_PrintStream__write__BAII,
 java_io_PrintStream__flush__,
 java_io_PrintStream__close__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_io_PrintStream_class_s
 java_io_PrintStream__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_io_PrintStream_methods),
  JCGO_STRREF_OF(jcgo_string1_PrntStrm),
  JCGO_CLASSREF_OF(java_io_FilterOutputStream__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype42_GameShll jcgo_array5_PrntStrm=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 19,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)80/*'P'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)109/*'m'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype63_GmCnnctn jcgo_array6_PrntStrm=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 14,
 {
  (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)114/*'r'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype2_VMChnnl jcgo_array7_PrntStrm=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 1,
 {
  (jbyte)(jchar)10
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype63_GmCnnctn jcgo_array8_PrntStrm=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 14,
 {
  (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)114/*'r'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)109/*'m'*/,
   (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)100/*'d'*/, (jbyte)(jchar)46/*'.'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_PrntStrm
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array5_PrntStrm),
 0, 19, (jint)0x301100f1L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_PrntStrm
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array6_PrntStrm),
 0, 14, (jint)0x7659856bL
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_PrntStrm
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array7_PrntStrm),
 0, 1, (jint)0xaL
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_PrntStrm
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array8_PrntStrm),
 0, 14, (jint)0x5a6083c2L
};

#ifdef CHKALL_java_io_PrintStream
#include "jcgochke.h"
#endif

#endif
