/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_gnu_java_net_PlainSocketImpl
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE void CFASTCALL
gnu_java_net_PlainSocketImpl_SocketOutputStream__close__( gnu_java_net_PlainSocketImpl_SocketOutputStream
 This )
{
 {
  (gnu_java_net_PlainSocketImpl__close__(
   JCGO_FIELD_NZACCESS(This, this_0)));
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
gnu_java_net_PlainSocketImpl_SocketOutputStream__write__BAII( gnu_java_net_PlainSocketImpl_SocketOutputStream
 This, jbyteArr buf, jint offset, jint len )
{
 {
  java_nio_ByteBuffer b;
  struct java_nio_ByteBufferImpl_s jcgo_stackobj1;
  if (JCGO_FIELD_NZACCESS(JCGO_FIELD_NZACCESS(This, this_0), channel) ==
   jnull)
  {
   JCGO_THROW_EXC((java_net_SocketException__new__Ls(
    JCGO_STRREF_OF(jcgo_string2_ScktHndl))));
  }
  b= (java_nio_ByteBuffer__wrap__BAIIX(
   buf, offset, len, JCGO_STACKOBJVLT_NEW(jcgo_stackobj1, java_nio_ByteBufferImpl_methods)));
  while ((java_nio_Buffer__hasRemaining__(
   (java_nio_Buffer)b)))
  {
   {
    JCGO_TRY_BLOCK
    {
     jObject jcgo_rcvrL1;
     if ((jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(JCGO_FIELD_NZACCESS(This,
      this_0), channel), JCGO_CALL_FINALF((gnu_java_nio_SocketChannelImpl)jcgo_rcvrL1)
      gnu_java_nio_SocketChannelImpl__write__L9oaia(
      (gnu_java_nio_SocketChannelImpl)jcgo_rcvrL1, b)) == (-(jint)1))
     {
      JCGO_THROW_EXC((java_io_IOException__new__Ls(
       JCGO_STRREF_OF(jcgo_string2_ScktOtSt))));
     }
    }
    JCGO_TRY_LEAVE
    JCGO_TRY_CATCHES(1)
    JCGO_TRY_CATCH(OBJT_java_io_InterruptedIOException, MAXT_java_io_InterruptedIOException)
    {
    }
    JCGO_TRY_RETHROW(1)
   }
  }
 }
}

JCGO_NOSEP_INLINE gnu_java_net_PlainSocketImpl_SocketOutputStream
 CFASTCALL
gnu_java_net_PlainSocketImpl_SocketOutputStream__this__L81fmm( gnu_java_net_PlainSocketImpl_SocketOutputStream
 This, gnu_java_net_PlainSocketImpl this_0 )
{
 {
  JCGO_FIELD_NZACCESS(This, this_0)= this_0;
  (java_io_OutputStream__this__((java_io_OutputStream)This));
 }
 return This;
}

JCGO_NOSEP_INLINE gnu_java_net_PlainSocketImpl_SocketOutputStream
 CFASTCALL
gnu_java_net_PlainSocketImpl_SocketOutputStream__new__L81fmm( gnu_java_net_PlainSocketImpl
 this_0 )
{
 return gnu_java_net_PlainSocketImpl_SocketOutputStream__this__L81fmm(
  (gnu_java_net_PlainSocketImpl_SocketOutputStream)jcgo_newObject((jvtable)&gnu_java_net_PlainSocketImpl_SocketOutputStream_methods),
  this_0);
}

JCGO_NOSEP_DATA CONST struct gnu_java_net_PlainSocketImpl_SocketOutputStream_methods_s
 gnu_java_net_PlainSocketImpl_SocketOutputStream_methods=
{
 JCGO_CLASSREF_OF(gnu_java_net_PlainSocketImpl_SocketOutputStream__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_gnu_java_net_PlainSocketImpl_SocketOutputStream,
 (JCGO_OBJSIZE_T)sizeof(struct gnu_java_net_PlainSocketImpl_SocketOutputStream_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__,
 gnu_java_net_PlainSocketImpl_SocketOutputStream__write__BAII,
 (void (CFASTCALL*)(java_io_OutputStream))java_lang_Object__finalize__,
 gnu_java_net_PlainSocketImpl_SocketOutputStream__close__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct gnu_java_net_PlainSocketImpl_SocketOutputStream_class_s
 gnu_java_net_PlainSocketImpl_SocketOutputStream__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&gnu_java_net_PlainSocketImpl_SocketOutputStream_methods),
  JCGO_STRREF_OF(jcgo_string1_ScktOtSt),
  JCGO_CLASSREF_OF(java_io_OutputStream__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x10
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype109_GmCnnctn jcgo_array3_ScktOtSt=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 47,
 {
  (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)118/*'v'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)80/*'P'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)99/*'c'*/,
   (jbyte)(jchar)107/*'k'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)73/*'I'*/, (jbyte)(jchar)109/*'m'*/, (jbyte)(jchar)112/*'p'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)36/*'$'*/, (jbyte)(jchar)83/*'S'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)107/*'k'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)79/*'O'*/,
   (jbyte)(jchar)117/*'u'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)112/*'p'*/,
   (jbyte)(jchar)117/*'u'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)83/*'S'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)109/*'m'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype91_GmCnnctn jcgo_array4_ScktOtSt=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 23,
 {
  (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)32/*' '*/,
   (jbyte)(jchar)98/*'b'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)99/*'c'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)100/*'d'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_ScktOtSt
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array3_ScktOtSt),
 0, 47, (jint)0x1623cb58L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_ScktOtSt
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array4_ScktOtSt),
 0, 23, (jint)0xcb0c663dL
};

#ifdef CHKALL_gnu_java_net_PlainSocketImpl
#include "jcgochke.h"
#endif

#endif
