/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_nio_channels_SocketChannel
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE java_nio_channels_SocketChannel CFASTCALL
java_nio_channels_SocketChannel__this__L6sfa6( java_nio_channels_SocketChannel
 This, java_nio_channels_spi_SelectorProvider provider )
{
 {
  (java_nio_channels_spi_AbstractSelectableChannel__this__L6sfa6((java_nio_channels_spi_AbstractSelectableChannel)This,
   provider));
 }
 return This;
}

JCGO_NOSEP_DATA CONST struct jcgo_methods_s java_nio_channels_SocketChannel_methods=
{
 JCGO_CLASSREF_OF(java_nio_channels_SocketChannel__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_nio_channels_SocketChannel,
 0,
 NULL,
 JCGO_CLINIT_INIT(0)
 0
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_nio_channels_SocketChannel_class_s
 java_nio_channels_SocketChannel__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_nio_channels_SocketChannel_methods),
  JCGO_STRREF_OF(jcgo_string1_ScktChnn),
  JCGO_CLASSREF_OF(java_nio_channels_spi_AbstractSelectableChannel__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x401
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype73_GmCnnctn jcgo_array2_ScktChnn=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 31,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)99/*'c'*/,
   (jbyte)(jchar)107/*'k'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)108/*'l'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_ScktChnn
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_ScktChnn),
 0, 31, (jint)0x452cbcb8L
};

#ifdef CHKALL_java_nio_channels_SocketChannel
#include "jcgochke.h"
#endif

#endif
