/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_Set
#include "jcgobchk.h"
#endif

JCGO_NOSEP_DATA CONST struct jcgo_methods_s java_util_Set_methods=
{
 JCGO_CLASSREF_OF(java_util_Set__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_util_Set,
 0,
 NULL,
 JCGO_CLINIT_INIT(0)
 0
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_util_Set_class_s java_util_Set__class
 JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_Set_methods),
  JCGO_STRREF_OF(jcgo_string1_Set2C1F3),
  jnull,
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array4_AbstrcCl)),
  0x601
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype30_GameShll jcgo_array2_Set2C1F3=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 13,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)116/*'t'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Set2C1F3
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_Set2C1F3),
 0, 13, (jint)0xad8bdaa2L
};

#ifdef CHKALL_java_util_Set
#include "jcgochke.h"
#endif

#endif
