/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE java_util_Collections_SynchronizedCollection CFASTCALL
java_util_Collections_SynchronizedCollection__this__LoL07mt2( java_util_Collections_SynchronizedCollection
 This, java_lang_Object sync, java_util_Collection c );

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_Collections_SynchronizedCollection__isEmpty__( java_util_Collections_SynchronizedCollection
 This );

JCGO_NOSEP_STATIC java_util_Iterator CFASTCALL
java_util_Collections_SynchronizedCollection__iterator__( java_util_Collections_SynchronizedCollection
 This );

JCGO_NOSEP_INLINE jint CFASTCALL
java_util_Collections_SynchronizedCollection__size__( java_util_Collections_SynchronizedCollection
 This );

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_util_Collections_SynchronizedCollection__toString__( java_util_Collections_SynchronizedCollection
 This );

struct java_util_Collections_SynchronizedCollection_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_util_Collections_SynchronizedCollection (CFASTCALL *jcgo_thisRtn)(
  java_util_Collections_SynchronizedCollection This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_util_Collections_SynchronizedCollection
  This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 jboolean (CFASTCALL *isEmpty__)( java_util_Collections_SynchronizedCollection
  This );
 java_util_Iterator (CFASTCALL *iterator__)( java_util_Collections_SynchronizedCollection
  This );
 jint (CFASTCALL *size__)( java_util_Collections_SynchronizedCollection
  This );
};

struct java_util_Collections_SynchronizedCollection_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_util_Collections_SynchronizedCollection_methods_s
 java_util_Collections_SynchronizedCollection_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_util_Collections_SynchronizedCollection_class_s
 java_util_Collections_SynchronizedCollection__class;

struct java_util_Collections_SynchronizedCollection_s
{
 CONST struct java_util_Collections_SynchronizedCollection_methods_s
  *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
 java_util_Collection c;
 java_lang_Object mutex;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype117_GmCnnctn jcgo_array2_SnchrnCl;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_SnchrnCl;

#endif
