/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_Collections
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE java_util_Collections_SynchronizedSet CFASTCALL
java_util_Collections_SynchronizedSet__this__LoL1x914( java_util_Collections_SynchronizedSet
 This, java_lang_Object sync, java_util_Set s )
{
 {
  (java_util_Collections_SynchronizedCollection__this__LoL07mt2((java_util_Collections_SynchronizedCollection)This,
   sync, (java_util_Collection)s));
 }
 return This;
}

JCGO_NOSEP_FRWINL java_util_Collections_SynchronizedSet CFASTCALL
java_util_Collections_SynchronizedSet__new__LoL1x914( java_lang_Object
 sync, java_util_Set s )
{
 return java_util_Collections_SynchronizedSet__this__LoL1x914(
  (java_util_Collections_SynchronizedSet)jcgo_newObject((jvtable)&java_util_Collections_SynchronizedSet_methods),
  sync, s);
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_Collections_SynchronizedSet__equals__Lo( java_util_Collections_SynchronizedSet
 This, java_lang_Object o )
{
 {
  {
   JCGO_SYNC_BLOCK(JCGO_FIELD_NZACCESS(This, mutex))
   {
    {
     jboolean jcgo_retval= (jboolean)(JCGO_CALL_VFUNC(JCGO_FIELD_NZACCESS(This,
      c))->equals__Lo(
      JCGO_FIELD_NZACCESS(This, c), o));
#ifndef JCGO_SEHTRY
     JCGO_SYNC_JUMPLEAVE(0);
#endif
     return jcgo_retval;
    }
   }
   JCGO_SYNC_ENDUNREACH
  }
 }
}

JCGO_NOSEP_INLINE jint CFASTCALL
java_util_Collections_SynchronizedSet__hashCode__( java_util_Collections_SynchronizedSet
 This )
{
 {
  {
   JCGO_SYNC_BLOCK(JCGO_FIELD_NZACCESS(This, mutex))
   {
    {
     jint jcgo_retval= (JCGO_CALL_VFUNC(JCGO_FIELD_NZACCESS(This, c))->hashCode__(
      JCGO_FIELD_NZACCESS(This, c)));
#ifndef JCGO_SEHTRY
     JCGO_SYNC_JUMPLEAVE(0);
#endif
     return jcgo_retval;
    }
   }
   JCGO_SYNC_ENDUNREACH
  }
 }
}

JCGO_NOSEP_DATA CONST struct java_util_Collections_SynchronizedSet_methods_s
 java_util_Collections_SynchronizedSet_methods=
{
 JCGO_CLASSREF_OF(java_util_Collections_SynchronizedSet__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_util_Collections_SynchronizedSet,
 (JCGO_OBJSIZE_T)sizeof(struct java_util_Collections_SynchronizedSet_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_util_Collections_SynchronizedSet__equals__Lo,
 java_util_Collections_SynchronizedSet__hashCode__,
 java_util_Collections_SynchronizedCollection__toString__,
 java_lang_Object__finalize__,
 java_util_Collections_SynchronizedCollection__isEmpty__,
 java_util_Collections_SynchronizedCollection__iterator__,
 java_util_Collections_SynchronizedCollection__size__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_util_Collections_SynchronizedSet_class_s
 java_util_Collections_SynchronizedSet__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_Collections_SynchronizedSet_methods),
  JCGO_STRREF_OF(jcgo_string1_SnchrnSt),
  JCGO_CLASSREF_OF(java_util_Collections_SynchronizedCollection__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array2_AbstrcSt)),
  0x8
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype92_GmCnnctn jcgo_array2_SnchrnSt=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 37,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)67/*'C'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)36/*'$'*/, (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)121/*'y'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)122/*'z'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)100/*'d'*/, (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)116/*'t'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_SnchrnSt
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_SnchrnSt),
 0, 37, (jint)0x9ff85bbfL
};

#ifdef CHKALL_java_util_Collections
#include "jcgochke.h"
#endif

#endif
