/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_STATIC java_lang_ClassLoader_StaticData CFASTCALL
java_lang_ClassLoader_StaticData__this__( java_lang_ClassLoader_StaticData
 This );

struct java_lang_ClassLoader_StaticData_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_lang_ClassLoader_StaticData (CFASTCALL *jcgo_thisRtn)( java_lang_ClassLoader_StaticData
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct java_lang_ClassLoader_StaticData_class_s
{
 struct java_lang_Class_s jcgo_class;
 java_lang_ClassLoader systemClassLoader;
};

JCGO_SEP_EXTERN CONST struct java_lang_ClassLoader_StaticData_methods_s
 java_lang_ClassLoader_StaticData_methods;
JCGO_SEP_GCEXTERN struct java_lang_ClassLoader_StaticData_class_s java_lang_ClassLoader_StaticData__class;

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_ClassLoader_StaticData__class__0( void );

struct java_lang_ClassLoader_StaticData_s
{
 CONST struct java_lang_ClassLoader_StaticData_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype2_GameMdl jcgo_array3_StaticDt;

JCGO_SEP_EXTERN CONST jcgo_arrtype4_VMChnnl jcgo_array4_StaticDt;

JCGO_SEP_EXTERN CONST jcgo_arrtype2_GameMdl jcgo_array5_StaticDt;

JCGO_SEP_EXTERN CONST jcgo_arrtype6_StaticDt jcgo_array6_StaticDt;

JCGO_SEP_EXTERN CONST jcgo_arrtype492_Mdclnt jcgo_array7_StaticDt;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_StaticDt;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_StaticDt;

#endif
