/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_gnu_java_net_VMPlainSocketImpl
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC gnu_java_net_VMPlainSocketImpl_State CFASTCALL
gnu_java_net_VMPlainSocketImpl_State__this__L8vgeu( gnu_java_net_VMPlainSocketImpl_State
 This, gnu_java_net_VMPlainSocketImpl this_0 )
{
 {
  ;
 }
 return This;
}

JCGO_NOSEP_FRWINL gnu_java_net_VMPlainSocketImpl_State CFASTCALL
gnu_java_net_VMPlainSocketImpl_State__new__L8vgeu( gnu_java_net_VMPlainSocketImpl
 this_0 )
{
 return gnu_java_net_VMPlainSocketImpl_State__this__L8vgeu(
  (gnu_java_net_VMPlainSocketImpl_State)jcgo_newObject((jvtable)&gnu_java_net_VMPlainSocketImpl_State_methods),
  this_0);
}

JCGO_NOSEP_STATIC void CFASTCALL
gnu_java_net_VMPlainSocketImpl_State__setChannelFD__L7r5z2( gnu_java_net_VMPlainSocketImpl_State
 This, gnu_java_nio_VMChannel_State newChState )
{
 {
  gnu_java_nio_VMChannel_State chState;
  chState= JCGO_FIELD_NZACCESS(This, chState);
  if (chState != jnull && (gnu_java_nio_VMChannel_State__isValid__(
   chState)))
  {
   JCGO_THROW_EXC((java_io_IOException__new__Ls(
    JCGO_STRREF_OF(jcgo_string6_State))));
  }
  JCGO_FIELD_NZACCESS(This, chState)= newChState;
 }
}

JCGO_NOSEP_INLINE jboolean CFASTCALL
gnu_java_net_VMPlainSocketImpl_State__isValid__( gnu_java_net_VMPlainSocketImpl_State
 This )
{
 {
  gnu_java_nio_VMChannel_State chState;
  chState= JCGO_FIELD_NZACCESS(This, chState);
  return (jboolean)(chState != jnull && (gnu_java_nio_VMChannel_State__isValid__(
   chState)));
 }
}

JCGO_NOSEP_STATIC jint CFASTCALL
gnu_java_net_VMPlainSocketImpl_State__getNativeFD__( gnu_java_net_VMPlainSocketImpl_State
 This )
{
 {
  gnu_java_nio_VMChannel_State chState;
  chState= JCGO_FIELD_NZACCESS(This, chState);
  if (chState == jnull)
  {
   JCGO_THROW_EXC((java_io_IOException__new__Ls(
    JCGO_STRREF_OF(jcgo_string4_State))));
  }
  return (gnu_java_nio_VMChannel_State__getNativeFD__(
   chState));
 }
}

JCGO_NOSEP_FRWINL void CFASTCALL
gnu_java_net_VMPlainSocketImpl_State__close__( gnu_java_net_VMPlainSocketImpl_State
 This )
{
 {
  gnu_java_nio_VMChannel_State chState;
  chState= JCGO_FIELD_NZACCESS(This, chState);
  if (chState == jnull)
  {
   JCGO_THROW_EXC((java_io_IOException__new__Ls(
    JCGO_STRREF_OF(jcgo_string4_State))));
  }
  (gnu_java_nio_VMChannel_State__close__(
   chState));
 }
}

JCGO_NOSEP_DATA CONST struct gnu_java_net_VMPlainSocketImpl_State_methods_s
 gnu_java_net_VMPlainSocketImpl_State_methods=
{
 JCGO_CLASSREF_OF(gnu_java_net_VMPlainSocketImpl_State__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_gnu_java_net_VMPlainSocketImpl_State,
 (JCGO_OBJSIZE_T)sizeof(struct gnu_java_net_VMPlainSocketImpl_State_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct gnu_java_net_VMPlainSocketImpl_State_class_s
 gnu_java_net_VMPlainSocketImpl_State__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&gnu_java_net_VMPlainSocketImpl_State_methods),
  JCGO_STRREF_OF(jcgo_string1_StateB46),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x11
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_StateB46
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array9_VMPlScIm),
 0, 36, (jint)0x4d27b696L
};

#ifdef CHKALL_gnu_java_net_VMPlainSocketImpl
#include "jcgochke.h"
#endif

#endif
