/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_util_StringTokenizer
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE java_util_StringTokenizer CFASTCALL
java_util_StringTokenizer__this__LsLsZ( java_util_StringTokenizer
 This, java_lang_String str, java_lang_String delim, jboolean returnDelims
 )
{
 {
  ;
  JCGO_FIELD_NZACCESS(This, len)= (JCGO_CALL_FINALF(str) java_lang_String__length__(
   str));
  JCGO_FIELD_NZACCESS(This, str)= str;
  JCGO_FIELD_NZACCESS(This, delim)= delim;
  JCGO_FIELD_NZACCESS(This, retDelims)= (jboolean)returnDelims;
  JCGO_FIELD_NZACCESS(This, pos)= 0;
 }
 return This;
}

JCGO_NOSEP_FRWINL java_util_StringTokenizer CFASTCALL
java_util_StringTokenizer__this__LsLs( java_util_StringTokenizer This,
 java_lang_String str, java_lang_String delim )
{
 {
  (java_util_StringTokenizer__this__LsLsZ((java_util_StringTokenizer)This,
   str, delim, (jboolean)jfalse));
 }
 return This;
}

JCGO_NOSEP_INLINE java_util_StringTokenizer CFASTCALL
java_util_StringTokenizer__new__LsLs( java_lang_String str, java_lang_String
 delim )
{
 return java_util_StringTokenizer__this__LsLs(
  (java_util_StringTokenizer)jcgo_newObject((jvtable)&java_util_StringTokenizer_methods),
  str, delim);
}

JCGO_NOSEP_FRWINL jboolean CFASTCALL
java_util_StringTokenizer__hasMoreTokens__( java_util_StringTokenizer
 This )
{
 {
  if (!JCGO_FIELD_NZACCESS(This, retDelims))
  {
   jObject jcgo_rcvrL1;
   jObject jcgo_rcvrL2;
   while (JCGO_FIELD_NZACCESS(This, pos) < JCGO_FIELD_NZACCESS(This,
    len) && (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, delim),
    JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL1) java_lang_String__indexOf__I(
    (java_lang_String)jcgo_rcvrL1, (jcgo_rcvrL2= (jObject)JCGO_FIELD_NZACCESS(This,
    str), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL2) java_lang_String__charAt__I(
    (java_lang_String)jcgo_rcvrL2, JCGO_FIELD_NZACCESS(This, pos))))) >=
    0)
   {
    JCGO_FIELD_NZACCESS(This, pos)++;
   }
  }
  return (jboolean)(JCGO_FIELD_NZACCESS(This, pos) < JCGO_FIELD_NZACCESS(This,
   len));
 }
}

JCGO_NOSEP_FRWINL java_lang_String CFASTCALL
java_util_StringTokenizer__nextToken__( java_util_StringTokenizer
 This )
{
 {
  jObject jcgo_rcvrL1;
  jObject jcgo_rcvrL2;
  if (JCGO_FIELD_NZACCESS(This, pos) < JCGO_FIELD_NZACCESS(This, len) &&
   (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, delim), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL1)
   java_lang_String__indexOf__I(
   (java_lang_String)jcgo_rcvrL1, (jcgo_rcvrL2= (jObject)JCGO_FIELD_NZACCESS(This,
   str), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL2) java_lang_String__charAt__I(
   (java_lang_String)jcgo_rcvrL2, JCGO_FIELD_NZACCESS(This, pos))))) >=
   0)
  {
   jObject jcgo_rcvrL1;
   jObject jcgo_rcvrL2;
   jint jcgo_rcvrI1;
   if (JCGO_FIELD_NZACCESS(This, retDelims))
   {
    jObject jcgo_rcvrL1;
    jint jcgo_rcvrI1;
    return (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, str), jcgo_rcvrI1=
     JCGO_FIELD_NZACCESS(This, pos), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL1)
     java_lang_String__substring__II(
     (java_lang_String)jcgo_rcvrL1, jcgo_rcvrI1, ++JCGO_FIELD_NZACCESS(This,
     pos)));
   }
   while ((jcgo_rcvrI1= ++JCGO_FIELD_NZACCESS(This, pos), jcgo_rcvrI1 <
    JCGO_FIELD_NZACCESS(This, len)) && (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This,
    delim), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL1) java_lang_String__indexOf__I(
    (java_lang_String)jcgo_rcvrL1, (jcgo_rcvrL2= (jObject)JCGO_FIELD_NZACCESS(This,
    str), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL2) java_lang_String__charAt__I(
    (java_lang_String)jcgo_rcvrL2, JCGO_FIELD_NZACCESS(This, pos))))) >=
    0)
   {
    ;
   }
  }
  if (JCGO_FIELD_NZACCESS(This, pos) < JCGO_FIELD_NZACCESS(This, len))
  {
   jint start;
   jObject jcgo_rcvrL1;
   jObject jcgo_rcvrL2;
   jint jcgo_rcvrI1;
   start= JCGO_FIELD_NZACCESS(This, pos);
   while ((jcgo_rcvrI1= ++JCGO_FIELD_NZACCESS(This, pos), jcgo_rcvrI1 <
    JCGO_FIELD_NZACCESS(This, len)) && (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This,
    delim), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL1) java_lang_String__indexOf__I(
    (java_lang_String)jcgo_rcvrL1, (jcgo_rcvrL2= (jObject)JCGO_FIELD_NZACCESS(This,
    str), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL2) java_lang_String__charAt__I(
    (java_lang_String)jcgo_rcvrL2, JCGO_FIELD_NZACCESS(This, pos))))) <
    0)
   {
    ;
   }
   return (jcgo_rcvrL1= (jObject)JCGO_FIELD_NZACCESS(This, str), JCGO_CALL_FINALF((java_lang_String)jcgo_rcvrL1)
    java_lang_String__substring__II(
    (java_lang_String)jcgo_rcvrL1, start, JCGO_FIELD_NZACCESS(This,
    pos)));
  }
  JCGO_THROW_EXC(java_util_NoSuchElementException__new__());
 }
 return jnull;
}

JCGO_NOSEP_DATA CONST struct java_util_StringTokenizer_methods_s java_util_StringTokenizer_methods=
{
 JCGO_CLASSREF_OF(java_util_StringTokenizer__class),
 JCGO_GCJDESCR_INIT(java_util_StringTokenizer_s, delim)
 OBJT_java_util_StringTokenizer,
 (JCGO_OBJSIZE_T)sizeof(struct java_util_StringTokenizer_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 0,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_util_StringTokenizer_class_s
 java_util_StringTokenizer__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_util_StringTokenizer_methods),
  JCGO_STRREF_OF(jcgo_string1_StrngTkn),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype108_GmCnnctn jcgo_array2_StrngTkn=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 25,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)83/*'S'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)84/*'T'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)107/*'k'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)122/*'z'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)114/*'r'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_StrngTkn
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array2_StrngTkn),
 0, 25, (jint)0x8210a846L
};

#ifdef CHKALL_java_util_StringTokenizer
#include "jcgochke.h"
#endif

#endif
