/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE java_lang_SecurityManager CFASTCALL
java_lang_System__getSecurityManager__( void );

JCGO_NOSEP_FRWINL jlong CFASTCALL
java_lang_System__currentTimeMillis__( void );

JCGO_NOSEP_INLINE void CFASTCALL
java_lang_System__arraycopy__LoILoII( java_lang_Object src, java_lang_Object
 dest, jint srcStart, jint destStart, jint len );

JCGO_NOSEP_FRWINL java_lang_String CFASTCALL
java_lang_System__getProperty__Ls( java_lang_String key );

JCGO_NOSEP_FRWINL void CFASTCALL
java_lang_System__exit__I( jint status );

JCGO_NOSEP_FRWINL void CFASTCALL
java_lang_System__gc__( void );

struct java_lang_System_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_lang_System (CFASTCALL *jcgo_thisRtn)( java_lang_System This
  );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct java_lang_System_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct jcgo_methods_s java_lang_System_methods;
JCGO_SEP_EXTERN struct java_lang_System_class_s java_lang_System__class;

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_System__class__0( void );

JCGO_SEP_GCEXTERN java_io_PrintStream java_lang_System__err;
JCGO_SEP_GCEXTERN java_io_PrintStream java_lang_System__out;

struct java_lang_System_s
{
 CONST struct java_lang_System_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype22_Object jcgo_array3_System;

JCGO_SEP_EXTERN CONST jcgo_arrtype82_GmCnnctn jcgo_array4_System;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_System;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_System;

#endif
