/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_lang_VMThread
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC java_lang_VMThread_UncaughtHandler CFASTCALL
java_lang_VMThread_UncaughtHandler__this__( java_lang_VMThread_UncaughtHandler
 This )
{
 {
  ;
 }
 return This;
}

JCGO_NOSEP_FRWINL java_lang_VMThread_UncaughtHandler CFASTCALL
java_lang_VMThread_UncaughtHandler__new__( void )
{
 return java_lang_VMThread_UncaughtHandler__this__(
  (java_lang_VMThread_UncaughtHandler)jcgo_newObject((jvtable)&java_lang_VMThread_UncaughtHandler_methods));
}

JCGO_NOSEP_FRWINL jboolean CFASTCALL
java_lang_VMThread_UncaughtHandler__printJniException__Lt( java_lang_VMThread_UncaughtHandler
 This, java_lang_Throwable throwable )
{
 JCGO_SYNC_BLOCKSAFENZ(This)
 {
  JCGO_TRY_VOLATILE jboolean done;
  done= jfalse;
  if (throwable != jnull && !JCGO_FIELD_NZACCESS(This, insideJniExc))
  {
   JCGO_FIELD_NZACCESS(This, insideJniExc)= (jboolean)jtrue;
   {
    JCGO_TRY_BLOCK
    {
     java_lang_Thread thread;
     java_io_PrintStream err;
     err= JCGO_CLINIT_VARACC(java_lang_System__class, java_lang_System__err);
     if (err != jnull && (thread= (java_lang_VMThread__currentThread__())) !=
      jnull && JCGO_VLT_LFETCH(java_lang_ThreadGroup, JCGO_FIELD_NZACCESS(thread,
      group)) != jnull)
     {
      jObject jcgo_rcvrL1;
      struct java_lang_StringBuilder_s jcgo_stackobj1;
      struct java_lang_String_s jcgo_stackobj2;
      (java_io_PrintStream__println__Ls(
       err, (jcgo_rcvrL1= (jObject)java_lang_StringBuilder__append__Ls(
       java_lang_StringBuilder__append__Ls(
       java_lang_StringBuilder__append__Ls(
       java_lang_StringBuilder__this__(
       JCGO_STACKOBJ_NEW(jcgo_stackobj1, java_lang_StringBuilder_methods)),
       JCGO_STRREF_OF(jcgo_string2_UncghtHn)), (java_lang_Thread__getName__(
       thread))), JCGO_STRREF_OF(jcgo_string3_UncghtHn)), java_lang_String__this__L5dy9e(
       JCGO_STACKOBJ_NEW(jcgo_stackobj2, java_lang_String_methods),
       java_lang_StringBuilder__append__Ls(
       (java_lang_StringBuilder)jcgo_rcvrL1, (java_lang_Throwable__toString__(
       throwable)))))));
      done= (jboolean)jtrue;
     }
    }
    JCGO_TRY_LEAVE
    {
     JCGO_FIELD_NZACCESS(This, insideJniExc)= (jboolean)jfalse;
    }
    JCGO_TRY_FINALLYEND
   }
  }
#ifndef JCGO_SEHTRY
  JCGO_SYNC_JUMPLEAVE(0);
#endif
  return (jboolean)done;
 }
 JCGO_SYNC_ENDUNREACH
}

JCGO_NOSEP_FRWINL jboolean CFASTCALL
java_lang_VMThread_UncaughtHandler__printException__L20uxkLt( java_lang_VMThread_UncaughtHandler
 This, java_lang_Thread thread, java_lang_Throwable throwable )
{
 {
  java_io_PrintStream err;
  err= JCGO_CLINIT_VARACC(java_lang_System__class, java_lang_System__err);
  if (err != jnull)
  {
   if (thread != jnull && JCGO_VLT_LFETCH(java_lang_ThreadGroup, JCGO_FIELD_NZACCESS(thread,
    group)) != jnull)
   {
    {
     JCGO_TRY_BLOCK
     {
      jObject jcgo_rcvrL1;
      (jcgo_rcvrL1= (jObject)(java_lang_Thread__getUncaughtExceptionHandler__(
       thread)), JCGO_CALL_EFINALF((java_lang_ThreadGroup)jcgo_rcvrL1)
       java_lang_ThreadGroup__uncaughtException__L20uxkLt(
       (java_lang_ThreadGroup)jcgo_rcvrL1, thread, throwable));
#ifndef JCGO_SEHTRY
      jcgo_tryLeave();
#endif
      return (jboolean)jtrue;
     }
     JCGO_TRY_LEAVE
     JCGO_TRY_CATCHES(1)
     JCGO_TRY_CATCH(OBJT_java_lang_Error, MAXT_java_lang_Error)
     {
     }
     JCGO_TRY_CATCH(OBJT_java_lang_RuntimeException, MAXT_java_lang_RuntimeException)
     {
     }
     JCGO_TRY_RETHROW(1)
    }
   }
   {
    JCGO_TRY_BLOCK
    {
     (java_io_PrintStream__println__(
      err));
     {
      JCGO_SYNC_BLOCKSAFENZ(err)
      {
       jObject jcgo_rcvrL1;
       (java_io_PrintStream__print__Ls(
        err, JCGO_STRREF_OF(jcgo_string4_UncghtHn)));
       (java_io_PrintStream__println__Ls(
        err, (jcgo_rcvrL1= (jObject)(JCGO_CALL_EFINALF(throwable) java_lang_Object__getClass__(
        (java_lang_Object)throwable)), JCGO_CALL_EFINALF((java_lang_Class)jcgo_rcvrL1)
        java_lang_Class__getName__(
        (java_lang_Class)jcgo_rcvrL1))));
      }
      JCGO_SYNC_END
     }
#ifndef JCGO_SEHTRY
     jcgo_tryLeave();
#endif
     return (jboolean)jtrue;
    }
    JCGO_TRY_LEAVE
    JCGO_TRY_CATCHES(2)
    JCGO_TRY_CATCH(OBJT_java_lang_Error, MAXT_java_lang_Error)
    {
    }
    JCGO_TRY_CATCH(OBJT_java_lang_RuntimeException, MAXT_java_lang_RuntimeException)
    {
    }
    JCGO_TRY_RETHROW(2)
   }
  }
  return (jboolean)jfalse;
 }
}

JCGO_NOSEP_DATA CONST struct java_lang_VMThread_UncaughtHandler_methods_s
 java_lang_VMThread_UncaughtHandler_methods=
{
 JCGO_CLASSREF_OF(java_lang_VMThread_UncaughtHandler__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_lang_VMThread_UncaughtHandler,
 -(JCGO_OBJSIZE_T)sizeof(struct java_lang_VMThread_UncaughtHandler_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 java_lang_VMThread_UncaughtHandler__this__,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_VMThread_UncaughtHandler_class_s
 java_lang_VMThread_UncaughtHandler__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_lang_VMThread_UncaughtHandler_methods),
  JCGO_STRREF_OF(jcgo_string1_UncghtHn),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x18
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype87_GmCnnctn jcgo_array5_UncghtHn=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 34,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)103/*'g'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)86/*'V'*/, (jbyte)(jchar)77/*'M'*/,
   (jbyte)(jchar)84/*'T'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)114/*'r'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)100/*'d'*/,
   (jbyte)(jchar)36/*'$'*/, (jbyte)(jchar)85/*'U'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)72/*'H'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)100/*'d'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)114/*'r'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype640_Mdclnt jcgo_array6_UncghtHn=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 3,
 {
  (jbyte)(jchar)34/*'"'*/, (jbyte)(jchar)58/*':'*/, (jbyte)(jchar)32/*' '*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_UncghtHn
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array5_UncghtHn),
 0, 34, (jint)0x12ab9f46L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_UncghtHn
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array38_Object),
 0, 27, (jint)0x86e481a9L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_UncghtHn
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array6_UncghtHn),
 0, 3, (jint)0x86c8L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_UncghtHn
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array38_Object),
 6, 10, (jint)0x287c15d1L
};

#ifdef CHKALL_java_lang_VMThread
#include "jcgochke.h"
#endif

#endif
