/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_lang_Thread
#include "jcgobchk.h"
#endif

JCGO_NOSEP_DATA CONST struct jcgo_methods_s java_lang_Thread_UncaughtExceptionHandler_methods=
{
 JCGO_CLASSREF_OF(java_lang_Thread_UncaughtExceptionHandler__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_lang_Thread_UncaughtExceptionHandler,
 0,
 NULL,
 JCGO_CLINIT_INIT(0)
 0
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_Thread_UncaughtExceptionHandler_class_s
 java_lang_Thread_UncaughtExceptionHandler__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_lang_Thread_UncaughtExceptionHandler_methods),
  JCGO_STRREF_OF(jcgo_string1_UncgExHn),
  jnull,
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x609
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_UncgExHn
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array7_ThreadF9),
 0, 41, (jint)0x7ac27016L
};

#ifdef CHKALL_java_lang_Thread
#include "jcgochke.h"
#endif

#endif
