/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_STATIC java_util_Collections_UnmodifiableIterator CFASTCALL
java_util_Collections_UnmodifiableIterator__this__L23h9x( java_util_Collections_UnmodifiableIterator
 This, java_util_Iterator i );
JCGO_NOSEP_FRWINL java_util_Collections_UnmodifiableIterator CFASTCALL
java_util_Collections_UnmodifiableIterator__new__L23h9x( java_util_Iterator
 i );

JCGO_NOSEP_INLINE java_lang_Object CFASTCALL
java_util_Collections_UnmodifiableIterator__next__( java_util_Collections_UnmodifiableIterator
 This );

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_util_Collections_UnmodifiableIterator__hasNext__( java_util_Collections_UnmodifiableIterator
 This );

JCGO_NOSEP_INLINE void CFASTCALL
java_util_Collections_UnmodifiableIterator__remove__( java_util_Collections_UnmodifiableIterator
 This );

struct java_util_Collections_UnmodifiableIterator_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_util_Collections_UnmodifiableIterator (CFASTCALL *jcgo_thisRtn)(
  java_util_Collections_UnmodifiableIterator This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 jboolean (CFASTCALL *hasNext__)( java_util_Collections_UnmodifiableIterator
  This );
 java_lang_Object (CFASTCALL *next__)( java_util_Collections_UnmodifiableIterator
  This );
 void (CFASTCALL *remove__)( java_util_Collections_UnmodifiableIterator
  This );
};

struct java_util_Collections_UnmodifiableIterator_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_util_Collections_UnmodifiableIterator_methods_s
 java_util_Collections_UnmodifiableIterator_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_util_Collections_UnmodifiableIterator_class_s
 java_util_Collections_UnmodifiableIterator__class;

struct java_util_Collections_UnmodifiableIterator_s
{
 CONST struct java_util_Collections_UnmodifiableIterator_methods_s
  *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
 java_util_Iterator i;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype621_Mdclnt jcgo_array2_UnmdfbIt;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_UnmdfbIt;

#endif
