/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE java_nio_charset_UnmappableCharacterException CFASTCALL
java_nio_charset_UnmappableCharacterException__this__I( java_nio_charset_UnmappableCharacterException
 This, jint inputLength );
JCGO_NOSEP_INLINE java_nio_charset_UnmappableCharacterException CFASTCALL
java_nio_charset_UnmappableCharacterException__new__I( jint inputLength
 );

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_nio_charset_UnmappableCharacterException__getMessage__( java_nio_charset_UnmappableCharacterException
 This );

struct java_nio_charset_UnmappableCharacterException_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_nio_charset_UnmappableCharacterException (CFASTCALL *jcgo_thisRtn)(
  java_nio_charset_UnmappableCharacterException This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Throwable This
  );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 java_lang_String (CFASTCALL *getMessage__)( java_nio_charset_UnmappableCharacterException
  This );
 java_lang_Throwable (CFASTCALL *getCause__)( java_lang_Throwable This
  );
};

struct java_nio_charset_UnmappableCharacterException_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_nio_charset_UnmappableCharacterException_methods_s
 java_nio_charset_UnmappableCharacterException_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_nio_charset_UnmappableCharacterException_class_s
 java_nio_charset_UnmappableCharacterException__class;

struct java_nio_charset_UnmappableCharacterException_s
{
 CONST struct java_nio_charset_UnmappableCharacterException_methods_s
  *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
 java_lang_String detailMessage;
 java_lang_Throwable cause;
 jObjectArr stackTrace;
 java_lang_VMThrowable vmState;
 jint inputLength;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype669_Mdclnt jcgo_array2_UnmpChEx;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_UnmpChEx;

#endif
