/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

#define java_net_URL__DEFAULT_SEARCH_PATH JCGO_STRREF_OF(jcgo_string2_Url)

JCGO_NOSEP_INLINE void CFASTCALL
java_net_URL__void( java_net_URL This );

JCGO_NOSEP_INLINE java_net_URL CFASTCALL
java_net_URL__this__L6799iLsL1u6yeZ( java_net_URL This, java_net_URL
 context, java_lang_String spec, java_net_URLStreamHandler ph, jboolean
 phFromUser );

JCGO_NOSEP_INLINE java_net_URLConnection CFASTCALL
java_net_URL__openConnection__( java_net_URL This );

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_net_URL__getFile__( java_net_URL This );

JCGO_NOSEP_INLINE java_net_URL CFASTCALL
java_net_URL__this__L6799iLs( java_net_URL This, java_net_URL context,
 java_lang_String spec );
JCGO_NOSEP_FRWINL java_net_URL CFASTCALL
java_net_URL__new__L6799iLs( java_net_URL context, java_lang_String
 spec );

JCGO_NOSEP_STATIC jboolean CFASTCALL
java_net_URL__equals__Lo( java_net_URL This, java_lang_Object obj
 );

JCGO_NOSEP_STATIC java_lang_String CFASTCALL
java_net_URL__getPath__( java_net_URL This );

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_net_URL__getAuthority__( java_net_URL This );

JCGO_NOSEP_STATIC java_lang_String CFASTCALL
java_net_URL__getHost__( java_net_URL This );

JCGO_NOSEP_INLINE jint CFASTCALL
java_net_URL__getPort__( java_net_URL This );

JCGO_NOSEP_INLINE jint CFASTCALL
java_net_URL__getDefaultPort__( java_net_URL This );

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_net_URL__getProtocol__( java_net_URL This );

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_net_URL__getRef__( java_net_URL This );

JCGO_NOSEP_STATIC java_lang_String CFASTCALL
java_net_URL__getUserInfo__( java_net_URL This );

JCGO_NOSEP_STATIC java_lang_String CFASTCALL
java_net_URL__getQuery__( java_net_URL This );

JCGO_NOSEP_STATIC jint CFASTCALL
java_net_URL__hashCode__( java_net_URL This );

JCGO_NOSEP_FRWINL java_io_InputStream CFASTCALL
java_net_URL__openStream__( java_net_URL This );

JCGO_NOSEP_INLINE void CFASTCALL
java_net_URL__set__LsLsILsLs( java_net_URL This, java_lang_String
 protocol, java_lang_String host, java_lang_String file, java_lang_String
 ref, jint port );

JCGO_NOSEP_INLINE void CFASTCALL
java_net_URL__set__LsLsILsLsLsLsLs( java_net_URL This, java_lang_String
 protocol, java_lang_String host, java_lang_String authority, java_lang_String
 userInfo, java_lang_String path, java_lang_String query, java_lang_String
 ref, jint port );

JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_net_URL__toString__( java_net_URL This );
JCGO_NOSEP_INLINE java_lang_String CFASTCALL
java_net_URL__toString__X( java_net_URL This, java_lang_String jcgo_stackparam
 );

JCGO_NOSEP_STATIC java_net_URLStreamHandler CFASTCALL
java_net_URL__getURLStreamHandler__Ls( java_lang_String protocol );

struct java_net_URL_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_net_URL (CFASTCALL *jcgo_thisRtn)( java_net_URL This );
 jboolean (CFASTCALL *equals__Lo)( java_net_URL This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_net_URL This );
 java_lang_String (CFASTCALL *toString__)( java_net_URL This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct java_net_URL_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct java_net_URL_methods_s java_net_URL_methods;
JCGO_SEP_EXTERN struct java_net_URL_class_s java_net_URL__class;

JCGO_NOSEP_STATIC void CFASTCALL
java_net_URL__class__0( void );

JCGO_SEP_GCEXTERN java_lang_ClassLoader java_net_URL__systemClassLoader;
JCGO_SEP_GCEXTERN java_util_HashMap java_net_URL__ph_cache;
JCGO_SEP_EXTERN jboolean java_net_URL__cache_handlers;

struct java_net_URL_s
{
 CONST struct java_net_URL_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
 java_lang_String protocol;
 java_lang_String authority;
 java_lang_String host;
 java_lang_String userInfo;
 java_lang_String file;
 java_lang_String ref;
 java_net_URLStreamHandler ph;
 jint port;
 jint hashCode;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype63_GmCnnctn jcgo_array14_Url;

JCGO_SEP_EXTERN CONST jcgo_arrtype77_GmCnnctn jcgo_array15_Url;

JCGO_SEP_EXTERN CONST jcgo_arrtype4_IntAddrs jcgo_array16_Url;

JCGO_SEP_EXTERN CONST jcgo_arrtype468_VMSstmPr jcgo_array17_Url;

JCGO_SEP_EXTERN CONST jcgo_arrtype23_Object jcgo_array18_Url;

JCGO_SEP_EXTERN CONST jcgo_arrtype27_Object jcgo_array19_Url;

JCGO_SEP_EXTERN CONST jcgo_arrtype87_GmCnnctn jcgo_array20_Url;

JCGO_SEP_EXTERN CONST jcgo_arrtype858_Mdclnt jcgo_array21_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string5_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string6_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string7_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string8_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string9_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string10_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string11_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string12_Url;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string13_Url;

#endif
