/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_FRWINL java_lang_String CFASTCALL
gnu_classpath_VMAccessorGnuClasspath__getConsoleEncodingVMSystemProperties__L0rv4g(
 java_io_OutputStream out );

struct gnu_classpath_VMAccessorGnuClasspath_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 gnu_classpath_VMAccessorGnuClasspath (CFASTCALL *jcgo_thisRtn)( gnu_classpath_VMAccessorGnuClasspath
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct gnu_classpath_VMAccessorGnuClasspath_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct jcgo_methods_s gnu_classpath_VMAccessorGnuClasspath_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct gnu_classpath_VMAccessorGnuClasspath_class_s
 gnu_classpath_VMAccessorGnuClasspath__class;

struct gnu_classpath_VMAccessorGnuClasspath_s
{
 CONST struct gnu_classpath_VMAccessorGnuClasspath_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype75_GmCnnctn jcgo_array2_VMAcGnCl;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_VMAcGnCl;

#endif
