/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

#define java_lang_VMClass__MODIFIER_PUBLIC (jint)1

#define java_lang_VMClass__MODIFIER_PRIVATE (jint)2

#define java_lang_VMClass__MODIFIER_PROTECTED (jint)4

#define java_lang_VMClass__MODIFIER_FINAL (jint)16

#define java_lang_VMClass__MODIFIER_VOLATILE (jint)64

#define java_lang_VMClass__MODIFIER_TRANSIENT (jint)128

#define java_lang_VMClass__MODIFIER_NATIVE (jint)256

#define java_lang_VMClass__MODIFIER_INTERFACE (jint)512

#define java_lang_VMClass__MODIFIER_ABSTRACT (jint)1024

JCGO_NOSEP_FRWINL java_lang_Class CFASTCALL
java_lang_VMClass__getComponentType__Lc( java_lang_Class klass );

JCGO_NOSEP_INLINE java_lang_Class CFASTCALL
java_lang_VMClass__loadArrayClass__LsL09rb1( java_lang_String name,
 java_lang_ClassLoader loader );

JCGO_NOSEP_FRWINL void CFASTCALL
java_lang_VMClass__initialize__Lc( java_lang_Class klass );

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_lang_VMClass__isAsciiDigit__C( jchar ch );

JCGO_NOSEP_INLINE java_lang_Class CFASTCALL
java_lang_VMClass__loadClassResolve__LsL09rb1( java_lang_String name,
 java_lang_ClassLoader loader );

JCGO_NOSEP_INLINE java_lang_Class CFASTCALL
java_lang_VMClass__getDeclaringClass__Lc( java_lang_Class klass );

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_lang_VMClass__isInterface__Lc( java_lang_Class klass );

JCGO_NOSEP_INLINE jboolean CFASTCALL
java_lang_VMClass__isPrimitive__Lc( java_lang_Class klass );

JCGO_NOSEP_FRWINL jboolean CFASTCALL
java_lang_VMClass__isAssignableFrom__LcLc( java_lang_Class klass,
 java_lang_Class aclass );

JCGO_NOSEP_STATIC java_lang_Class CFASTCALL
java_lang_VMClass__getSuperclass__Lc( java_lang_Class klass );

JCGO_NOSEP_FRWINL jboolean CFASTCALL
java_lang_VMClass__isArray__Lc( java_lang_Class klass );

JCGO_NOSEP_STATIC jint CFASTCALL
java_lang_VMClass__getModifiers__LcZ( java_lang_Class klass, jboolean
 ignoreInnerClassesAttrib );

JCGO_NOSEP_STATIC java_lang_ClassLoader CFASTCALL
java_lang_VMClass__getClassLoader__Lc( java_lang_Class klass );

JCGO_NOSEP_STATIC java_lang_Class CFASTCALL
java_lang_VMClass__forName__LsZL09rb1( java_lang_String name, java_lang_ClassLoader
 loader, jboolean initialize );

JCGO_NOSEP_FRWINL void CFASTCALL
java_lang_VMClass__throwException__Lt( java_lang_Throwable throwable
 );

JCGO_NOSEP_STATIC java_lang_Class CFASTCALL
java_lang_VMClass__arrayClassOf0X__LcI( java_lang_Class klass, jint
 dims );

JCGO_NOSEP_STATIC java_lang_Class CFASTCALL
java_lang_VMClass__classForSig__LsLc( java_lang_String sig, java_lang_Class
 klass );

JCGO_NOSEP_FRWINL jObjectArr CFASTCALL
java_lang_VMClass__getInterfacesInner__Lc( java_lang_Class klass );

JCGO_NOSEP_FRWINL jboolean CFASTCALL
java_lang_VMClass__hasClassInitializer__Lc( java_lang_Class klass
 );

JCGO_NOSEP_FRWINL void CFASTCALL
java_lang_VMClass__setBasicConstructorOf__LcL1693g( java_lang_Class
 klass, java_lang_reflect_Constructor constructor_8w9 );

JCGO_NOSEP_FRWINL java_lang_reflect_Constructor CFASTCALL
java_lang_VMClass__getBasicConstructorOf__Lc( java_lang_Class klass
 );

JCGO_NOSEP_STATIC java_lang_ClassLoader CFASTCALL
java_lang_VMClass__getClassLoaderInner__Lc( java_lang_Class klass
 );

JCGO_NOSEP_STATIC jboolean CFASTCALL
java_lang_VMClass__isImplementedBy__LcLc( java_lang_Class klass, java_lang_Class
 aclass );

JCGO_NOSEP_STATIC jint CFASTCALL
java_lang_VMClass__initialize0__Lc( java_lang_Class klass );

JCGO_NOSEP_STATIC java_lang_Object CFASTCALL
java_lang_VMClass__getClassLoader0__Lc( java_lang_Class klass );

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMClass__throwException0__Lo( java_lang_Object throwable
 );

JCGO_NOSEP_STATIC java_lang_Object CFASTCALL
java_lang_VMClass__vmdataForObjArray0__I( jint dims );

#define JCGO_NATCLASS_java_lang_VMClass

struct java_lang_VMClass_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 java_lang_VMClass (CFASTCALL *jcgo_thisRtn)( java_lang_VMClass This
  );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct java_lang_VMClass_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct jcgo_methods_s java_lang_VMClass_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_VMClass_class_s java_lang_VMClass__class;

struct java_lang_VMClass_s
{
 CONST struct java_lang_VMClass_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype33_Object jcgo_array10_VMClass;

JCGO_SEP_EXTERN CONST jcgo_arrtype32_GameShll jcgo_array11_VMClass;

JCGO_SEP_EXTERN CONST jcgo_arrtype625_Mdclnt jcgo_array12_VMClass;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_VMClass;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_VMClass;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_VMClass;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_VMClass;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string5_VMClass;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string6_VMClass;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string7_VMClass;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string8_VMClass;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string9_VMClass;

#endif
