/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE java_lang_ClassLoader CFASTCALL
gnu_classpath_VMStackWalker__getClassLoader__Lc( java_lang_Class klass
 );

JCGO_NOSEP_FRWINL java_lang_Class CFASTCALL
gnu_classpath_VMStackWalker__getCallingClass__( void );

JCGO_NOSEP_STATIC java_lang_ClassLoader CFASTCALL
gnu_classpath_VMStackWalker__getCallingClassLoader__( void );

JCGO_NOSEP_STATIC java_lang_Class CFASTCALL
gnu_classpath_VMStackWalker__getCallingClassAt0__I( jint depth );

#define JCGO_NATCLASS_gnu_classpath_VMStackWalker

struct gnu_classpath_VMStackWalker_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 gnu_classpath_VMStackWalker (CFASTCALL *jcgo_thisRtn)( gnu_classpath_VMStackWalker
  This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct gnu_classpath_VMStackWalker_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct jcgo_methods_s gnu_classpath_VMStackWalker_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct gnu_classpath_VMStackWalker_class_s
 gnu_classpath_VMStackWalker__class;

struct gnu_classpath_VMStackWalker_s
{
 CONST struct gnu_classpath_VMStackWalker_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype38_Object jcgo_array2_VMStckWl;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_VMStckWl;

#endif
