/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_java_lang_VMThrowable
#include "jcgobchk.h"
#endif

JCGO_NOSEP_INLINE java_lang_VMThrowable CFASTCALL
java_lang_VMThrowable__this__Lo( java_lang_VMThrowable This, java_lang_Object
 vmdata )
{
 {
  ;
  JCGO_FIELD_NZACCESS(This, vmdata)= vmdata;
 }
 return This;
}

JCGO_NOSEP_INLINE java_lang_VMThrowable CFASTCALL
java_lang_VMThrowable__new__Lo( java_lang_Object vmdata )
{
 return java_lang_VMThrowable__this__Lo(
  (java_lang_VMThrowable)jcgo_newObject((jvtable)&java_lang_VMThrowable_methods),
  vmdata);
}

JCGO_NOSEP_FRWINL java_lang_VMThrowable CFASTCALL
java_lang_VMThrowable__fillInStackTrace__Lt( java_lang_Throwable throwable
 )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  return (java_lang_VMThrowable__new__Lo(
   (java_lang_VMThrowable__fillInStackTrace0__())));
 }
}

JCGO_NOSEP_FRWINL jObjectArr CFASTCALL
java_lang_VMThrowable__getStackTrace__Lt( java_lang_VMThrowable This,
 java_lang_Throwable throwable )
{
 {
  java_lang_Object vmdata;
  jObjectArr elements;
  jint count;
  vmdata= JCGO_FIELD_NZACCESS(This, vmdata);
  count= vmdata != jnull? (java_lang_VMThrowable__getStackTraceLen0__Lo(
   vmdata)) : 0;
  elements= (jObjectArr)jcgo_newArray(JCGO_CLASSREF_OF(java_lang_StackTraceElement__class),
   0, count);
  if (count > 0)
  {
   jObjectArr classes;
   jObjectArr methodNames;
   jintArr lineNumbers;
   classes= (jObjectArr)jcgo_newArray(JCGO_CLASSREF_OF(java_lang_Class__class),
    0, count);
   methodNames= (jObjectArr)jcgo_newArray(JCGO_CLASSREF_OF(java_lang_String__class),
    0, count);
   lineNumbers= (jintArr)jcgo_newArray(JCGO_CORECLASS_FOR(OBJT_jint),
    0, count);
   (java_lang_VMThrowable__getStackTraceFill0__LoLcALsAIA(
    vmdata, classes, methodNames, lineNumbers));
   {
    jint i;
    i= 0;
    for (; i < count; i++)
    {
     java_lang_Class aclass;
     java_lang_String filename;
     jint lineNumber;
     jObject jcgo_rcvrL1;
     jObject jcgo_rcvrL2;
     jObject jcgo_rcvrL3;
     jObject jcgo_rcvrL4;
     jint jcgo_rcvrI1;
     jint jcgo_rcvrI2;
     aclass= ((java_lang_Class)JCGO_ARRAY_NZLACCESS(classes, i));
     lineNumber= JCGO_ARRAY_NZIACCESS(lineNumbers, i);
     filename= (java_lang_String)jnull;
     (jcgo_rcvrL1= (jObject)elements, jcgo_rcvrI1= i, jcgo_rcvrL2=
      (jObject)(jcgo_rcvrL3= (jObject)filename, jcgo_rcvrI2= lineNumber,
      jcgo_rcvrL4= (jObject)(aclass != jnull? (java_lang_VMThrowable__getClassName__Lc(
      aclass)) : jnull), java_lang_StackTraceElement__new__LsILsLsZ(
      (java_lang_String)jcgo_rcvrL3, (java_lang_String)jcgo_rcvrL4,
      ((java_lang_String)JCGO_ARRAY_NZLACCESS(methodNames, i)), jcgo_rcvrI2,
      (jboolean)(lineNumber == (-(jint)2)))), *(java_lang_StackTraceElement*)&JCGO_ARRAY_NZLACCESS((jObjectArr)jcgo_rcvrL1,
      jcgo_rcvrI1)= (java_lang_StackTraceElement)jcgo_rcvrL2);
    }
   }
  }
  return elements;
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__exit__I( jint status )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  if (status < 0 || status >= (jint)255)
  {
   status= (jint)255;
  }
  (java_lang_VMThrowable__exit0__I(
   status));
 }
}

JCGO_NOSEP_STATIC java_lang_Object CFASTCALL
java_lang_VMThrowable__createInstantiationException0X__Lc( java_lang_Class
 aclass )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  return (java_lang_Object)(java_lang_InstantiationException__new__Ls(
   aclass != jnull? (java_lang_String__concat__Ls(
   JCGO_STRREF_OF(jcgo_string2_VMThrwbl), (java_lang_VMThrowable__getClassName__Lc(
   aclass)))) : jnull));
 }
}

JCGO_NOSEP_STATIC java_lang_Object CFASTCALL
java_lang_VMThrowable__createNoClassDefFoundError0X__LsI( java_lang_String
 name, jint isErroneousState )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  java_lang_NoClassDefFoundError error;
  error= (java_lang_NoClassDefFoundError__new__Ls(
   name));
  if (isErroneousState != 0)
  {
   (java_lang_Throwable__initCause__Lt(
    (java_lang_Throwable)error, (java_lang_Throwable)java_lang_ExceptionInInitializerError__new__()));
  }
  return (java_lang_Object)error;
 }
}

JCGO_NOSEP_STATIC java_lang_Object CFASTCALL
java_lang_VMThrowable__createNoSuchFieldError0X__LcLsLsI( java_lang_Class
 aclass, java_lang_String name, java_lang_String sig, jint isStatic
 )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  return (java_lang_Object)(java_lang_NoSuchFieldError__new__Ls(
   aclass != jnull && name != jnull? (java_lang_String__concat__Ls(
   (java_lang_String__concat__Ls(
   (java_lang_VMThrowable__getClassName__Lc(
   aclass)), JCGO_STRREF_OF(jcgo_string3_VMThrwbl))), name)) : jnull));
 }
}

JCGO_NOSEP_STATIC java_lang_Object CFASTCALL
java_lang_VMThrowable__createNoSuchMethodError0X__LcLsLsI( java_lang_Class
 aclass, java_lang_String name, java_lang_String sig, jint isStatic
 )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  jObject jcgo_rcvrL1;
  return (java_lang_Object)(java_lang_NoSuchMethodError__new__Ls(
   aclass != jnull && name != jnull? (jcgo_rcvrL1= (jObject)(java_lang_String__concat__Ls(
   (java_lang_String__concat__Ls(
   (java_lang_VMThrowable__getClassName__Lc(
   aclass)), JCGO_STRREF_OF(jcgo_string3_VMThrwbl))), name)), java_lang_String__concat__Ls(
   (java_lang_String)jcgo_rcvrL1, sig != jnull && (java_lang_String__length__(
   sig)) > 0? ((java_lang_String__startsWith__Ls(
   sig, JCGO_STRREF_OF(jcgo_string478_Mdclnt)))? sig : (java_lang_String__concat__Ls(
   JCGO_STRREF_OF(jcgo_string327_Mdclnt), sig))) : JCGO_STRREF_OF(jcgo_string3_String6D))) :
   jnull));
 }
}

JCGO_NOSEP_STATIC java_lang_Object CFASTCALL
java_lang_VMThrowable__createNullPointerException0X__( void )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  return (java_lang_Object)java_lang_NullPointerException__new__();
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__throwArithmeticException0X__( void )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  JCGO_THROW_EXC((java_lang_ArithmeticException__new__Ls(
   JCGO_STRREF_OF(jcgo_string4_VMThrwbl))));
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__throwArrayIndexOutOfBoundsException0X__( void
 )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  JCGO_THROW_EXC(java_lang_ArrayIndexOutOfBoundsException__new__());
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__throwArrayStoreException0X__( void )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  JCGO_THROW_EXC(java_lang_ArrayStoreException__new__());
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__throwClassCastException0X__( void )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  JCGO_THROW_EXC(java_lang_ClassCastException__new__());
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__throwNegativeArraySizeException0X__( void )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  JCGO_THROW_EXC(java_lang_NegativeArraySizeException__new__());
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__throwStringIndexOutOfBoundsException0X__( void
 )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  JCGO_THROW_EXC(java_lang_StringIndexOutOfBoundsException__new__());
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__throwOutOfMemoryError0X__( void )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  if (java_lang_VMThrowable__outOfMemoryError == jnull)
  {
   (java_lang_VMThrowable__exit0__I(
    (jint)255));
  }
  JCGO_THROW_EXC(java_lang_VMThrowable__outOfMemoryError);
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__throwUnsatisfiedLinkError0X__( void )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  JCGO_THROW_EXC((java_lang_UnsatisfiedLinkError__new__Ls(
   JCGO_STRREF_OF(jcgo_string5_VMThrwbl))));
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__throwExceptionInInitializer0X__LoLc( java_lang_Object
 throwableObj, java_lang_Class aclass )
{
 JCGO_CLINIT_TRIG(java_lang_VMThrowable__class);
 {
  JCGO_THROW_EXC(jcgo_instanceOf0(OBJT_java_lang_Error, MAXT_java_lang_Error,
   (jObject)throwableObj)? (java_lang_Error)throwableObj : (java_lang_Error)(java_lang_ExceptionInInitializerError__new__Lt(
   (java_lang_Throwable)JCGO_CAST_OBJECT0(OBJT_java_lang_Throwable,
   MAXT_java_lang_Throwable, throwableObj))));
 }
}

JCGO_NOSEP_STATIC java_lang_String CFASTCALL
java_lang_VMThrowable__getClassName__Lc( java_lang_Class aclass )
{
 {
  java_lang_String name;
  if ((name= JCGO_FIELD_ACCESS(java_lang_Class, aclass, name)) == jnull)
  {
   name= JCGO_STRREF_OF(jcgo_string3_Class);
  }
  return name;
 }
}

JCGO_NOSEP_STATIC void CFASTCALL
java_lang_VMThrowable__class__0( void )
{
 JCGO_CLINIT_BEGIN(java_lang_VMThrowable__class);
 java_lang_VMThrowable__outOfMemoryError= java_lang_OutOfMemoryError__new__();
 {
  (java_lang_VMThrowable__setNullException0__Lo(
   (java_lang_VMThrowable__createNullPointerException0X__())));
  if (java_lang_VMThrowable__outOfMemoryError == jnull)
  {
   (java_lang_VMThrowable__throwOutOfMemoryError0X__());
   (java_lang_VMThrowable__throwArithmeticException0X__());
   (java_lang_VMThrowable__throwArrayIndexOutOfBoundsException0X__());
   (java_lang_VMThrowable__throwArrayStoreException0X__());
   (java_lang_VMThrowable__throwClassCastException0X__());
   (java_lang_VMThrowable__throwNegativeArraySizeException0X__());
   (java_lang_VMThrowable__throwStringIndexOutOfBoundsException0X__());
   (java_lang_VMThrowable__throwUnsatisfiedLinkError0X__());
   (java_lang_VMThrowable__throwExceptionInInitializer0X__LoLc(
    (java_lang_Object)jnull, (java_lang_Class)jnull));
   (java_lang_VMThrowable__createInstantiationException0X__Lc(
    (java_lang_Class)jnull));
   (java_lang_VMThrowable__createNoClassDefFoundError0X__LsI(
    (java_lang_String)jnull, 0));
   (java_lang_VMThrowable__createNoSuchFieldError0X__LcLsLsI(
    (java_lang_Class)jnull, (java_lang_String)jnull, (java_lang_String)jnull,
    0));
   (java_lang_VMThrowable__createNoSuchMethodError0X__LcLsLsI(
    (java_lang_Class)jnull, (java_lang_String)jnull, (java_lang_String)jnull,
    0));
  }
 }
 JCGO_CLINIT_DONE(java_lang_VMThrowable__class);
}

JCGO_NOSEP_DATA CONST struct java_lang_VMThrowable_methods_s java_lang_VMThrowable_methods=
{
 JCGO_CLASSREF_OF(java_lang_VMThrowable__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_java_lang_VMThrowable,
 (JCGO_OBJSIZE_T)sizeof(struct java_lang_VMThrowable_s),
 NULL,
 JCGO_CLINIT_INIT(java_lang_VMThrowable__class__0)
 0,
 java_lang_Object__equals__Lo,
 java_lang_Object__hashCode__,
 java_lang_Object__toString__,
 java_lang_Object__finalize__
};

JCGO_NOSEP_DATA struct java_lang_VMThrowable_class_s java_lang_VMThrowable__class
 ATTRIBNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&java_lang_VMThrowable_methods),
  JCGO_STRREF_OF(jcgo_string1_VMThrwbl),
  JCGO_CLASSREF_OF(java_lang_Object__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x1d0
 }
};

JCGO_NOSEP_GCDATA java_lang_OutOfMemoryError java_lang_VMThrowable__outOfMemoryError
 ATTRIBGCBSS= jnull;

JCGO_NOSEP_DATA CONST jcgo_arrtype80_GmCnnctn jcgo_array6_VMThrwbl=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 21,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)103/*'g'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)86/*'V'*/, (jbyte)(jchar)77/*'M'*/,
   (jbyte)(jchar)84/*'T'*/, (jbyte)(jchar)104/*'h'*/, (jbyte)(jchar)114/*'r'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)119/*'w'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)98/*'b'*/, (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)101/*'e'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype27_Object jcgo_array7_VMThrwbl=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 26,
 {
  (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)116/*'t'*/,
   (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)58/*':'*/, (jbyte)(jchar)32/*' '*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype30_GameShll jcgo_array8_VMThrwbl=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 13,
 {
  (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)118/*'v'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)101/*'e'*/,
   (jbyte)(jchar)120/*'x'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)100/*'d'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)114/*'r'*/,
   (jbyte)(jchar)115/*'s'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype28_GameShll jcgo_array9_VMThrwbl=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 9,
 {
  (jbyte)(jchar)47/*'/'*/, (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)98/*'b'*/,
   (jbyte)(jchar)121/*'y'*/, (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)122/*'z'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)111/*'o'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype73_GmCnnctn jcgo_array10_VMThrwbl=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 31,
 {
  (jbyte)(jchar)77/*'M'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)32/*' '*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)118/*'v'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)32/*' '*/,
   (jbyte)(jchar)102/*'f'*/, (jbyte)(jchar)117/*'u'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)105/*'i'*/,
   (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)32/*' '*/,
   (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)108/*'l'*/,
   (jbyte)(jchar)108/*'l'*/, (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)100/*'d'*/,
   (jbyte)(jchar)33/*'!'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_VMThrwbl
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array6_VMThrwbl),
 0, 21, (jint)0x91ee295L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_VMThrwbl
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array7_VMThrwbl),
 0, 26, (jint)0x57734ccbL
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_VMThrwbl
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array8_VMThrwbl),
 4, 1, (jint)0x2eL
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_VMThrwbl
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array9_VMThrwbl),
 0, 9, (jint)0x454efde0L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string5_VMThrwbl
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array10_VMThrwbl),
 0, 31, (jint)0xd2a5040bL
};

#ifdef CHKALL_java_lang_VMThrowable
#include "jcgochke.h"
#endif

#endif
