/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

#define gnu_java_nio_charset_Windows1255__lookup ((jcharArr)JCGO_OBJREF_OF(jcgo_array2_Wndws136))

JCGO_NOSEP_STATIC gnu_java_nio_charset_Windows1255 CFASTCALL
gnu_java_nio_charset_Windows1255__this__( gnu_java_nio_charset_Windows1255
 This );
JCGO_NOSEP_INLINE gnu_java_nio_charset_Windows1255 CFASTCALL
gnu_java_nio_charset_Windows1255__new__( void );

struct gnu_java_nio_charset_Windows1255_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 gnu_java_nio_charset_Windows1255 (CFASTCALL *jcgo_thisRtn)( gnu_java_nio_charset_Windows1255
  This );
 jboolean (CFASTCALL *equals__Lo)( java_nio_charset_Charset This, java_lang_Object
  ob );
 jint (CFASTCALL *hashCode__)( java_nio_charset_Charset This );
 java_lang_String (CFASTCALL *toString__)( java_nio_charset_Charset
  This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
 java_nio_charset_CharsetDecoder (CFASTCALL *newDecoder__)( gnu_java_nio_charset_ByteCharset
  This );
 java_nio_charset_CharsetEncoder (CFASTCALL *newEncoder__)( gnu_java_nio_charset_ByteCharset
  This );
};

struct gnu_java_nio_charset_Windows1255_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct gnu_java_nio_charset_Windows1255_methods_s
 gnu_java_nio_charset_Windows1255_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct gnu_java_nio_charset_Windows1255_class_s
 gnu_java_nio_charset_Windows1255__class;

struct gnu_java_nio_charset_Windows1255_s
{
 CONST struct gnu_java_nio_charset_Windows1255_methods_s *JCGO_IMMFLD_CONST
  jcgo_methods;
 JCGO_MON_DEFN
 java_lang_String canonicalName;
 jObjectArr aliases;
 jcharArr lookupTable;
};

JCGO_SEP_EXTERN jcgo_arrtype39_CharData jcgo_array2_Wndws136;

JCGO_SEP_EXTERN CONST jcgo_arrtype9_Wndws1F6 jcgo_array9_Wndws136;

JCGO_SEP_EXTERN CONST jcgo_arrtype98_GmCnnctn jcgo_array10_Wndws136;

JCGO_SEP_EXTERN CONST jcgo_arrtype2_BZLib jcgo_array11_Wndws136;

JCGO_SEP_EXTERN CONST jcgo_arrtype24_Object jcgo_array12_Wndws136;

JCGO_SEP_EXTERN CONST jcgo_arrtype24_Object jcgo_array13_Wndws136;

JCGO_SEP_EXTERN CONST jcgo_arrtype28_Object jcgo_array14_Wndws136;

JCGO_SEP_EXTERN CONST jcgo_arrtype26_Object jcgo_array15_Wndws136;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Wndws136;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_Wndws136;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_Wndws136;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string5_Wndws136;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string6_Wndws136;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string7_Wndws136;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string8_Wndws136;

#endif
