/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_SEPARATED
#define JCGO_116
#include "jcgortl.h"
#include "Main.h"
#endif

#ifdef JCGO_116

#ifdef CHKALL_gnu_java_nio_charset_Windows1257
#include "jcgobchk.h"
#endif

JCGO_NOSEP_STATIC gnu_java_nio_charset_Windows1257 CFASTCALL
gnu_java_nio_charset_Windows1257__this__( gnu_java_nio_charset_Windows1257
 This )
{
 {
  (gnu_java_nio_charset_ByteCharset__this__LsLsA((gnu_java_nio_charset_ByteCharset)This,
   JCGO_STRREF_OF(jcgo_string17_EncdngHl), (jObjectArr)jcgo_arrayClone((jObject)JCGO_OBJREF_OF(jcgo_array9_Wndws1E1))));
  JCGO_FIELD_NZACCESS(This, lookupTable)= gnu_java_nio_charset_Windows1257__lookup;
 }
 return This;
}

JCGO_NOSEP_INLINE gnu_java_nio_charset_Windows1257 CFASTCALL
gnu_java_nio_charset_Windows1257__new__( void )
{
 return gnu_java_nio_charset_Windows1257__this__(
  (gnu_java_nio_charset_Windows1257)jcgo_newObject((jvtable)&gnu_java_nio_charset_Windows1257_methods));
}

JCGO_NOSEP_DATA CONST struct gnu_java_nio_charset_Windows1257_methods_s
 gnu_java_nio_charset_Windows1257_methods=
{
 JCGO_CLASSREF_OF(gnu_java_nio_charset_Windows1257__class),
 JCGO_GCJDESCR_ZEROINIT
 OBJT_gnu_java_nio_charset_Windows1257,
 (JCGO_OBJSIZE_T)sizeof(struct gnu_java_nio_charset_Windows1257_s),
 NULL,
 JCGO_CLINIT_INIT(0)
 gnu_java_nio_charset_Windows1257__this__,
 java_nio_charset_Charset__equals__Lo,
 java_nio_charset_Charset__hashCode__,
 java_nio_charset_Charset__toString__,
 java_lang_Object__finalize__,
 gnu_java_nio_charset_ByteCharset__newDecoder__,
 gnu_java_nio_charset_ByteCharset__newEncoder__
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct gnu_java_nio_charset_Windows1257_class_s
 gnu_java_nio_charset_Windows1257__class JCGO_THRD_ATTRNONGC=
{
 {
  &java_lang_Class_methods,
  JCGO_MON_INIT
  JCGO_OBJREF_OF(*(java_lang_Object)&gnu_java_nio_charset_Windows1257_methods),
  JCGO_STRREF_OF(jcgo_string1_Wndws1E1),
  JCGO_CLASSREF_OF(gnu_java_nio_charset_ByteCharset__class),
  ((jObjectArr)JCGO_OBJREF_OF(jcgo_array3_Object)),
  0x101
 }
};

JCGO_NOSEP_DATA jcgo_arrtype39_CharData jcgo_array2_Wndws1E1 ATTRIBNONGC=
{
 (jvtable)&jcharArr_methods,
 JCGO_MON_INIT
 256,
 {
  (jchar)0, (jchar)(jint)1, (jchar)(jint)2, (jchar)(jint)3, (jchar)(jint)4,
   (jchar)(jint)5, (jchar)(jint)6, (jchar)(jint)7, (jchar)(jint)8,
   (jchar)(jint)9, (jchar)(jint)10, (jchar)(jint)11, (jchar)(jint)12,
   (jchar)(jint)13, (jchar)(jint)14, (jchar)(jint)15, (jchar)(jint)16,
   (jchar)(jint)17, (jchar)(jint)18, (jchar)(jint)19, (jchar)(jint)20,
   (jchar)(jint)21, (jchar)(jint)22, (jchar)(jint)23, (jchar)(jint)24,
   (jchar)(jint)25, (jchar)(jint)26, (jchar)(jint)27, (jchar)(jint)28,
   (jchar)(jint)29, (jchar)(jint)30, (jchar)(jint)31, (jchar)(jint)32,
   (jchar)(jint)33, (jchar)(jint)34, (jchar)(jint)35, (jchar)(jint)36,
   (jchar)(jint)37, (jchar)(jint)38, (jchar)(jint)39, (jchar)(jint)40,
   (jchar)(jint)41, (jchar)(jint)42, (jchar)(jint)43, (jchar)(jint)44,
   (jchar)(jint)45, (jchar)(jint)46, (jchar)(jint)47, (jchar)(jint)48,
   (jchar)(jint)49, (jchar)(jint)50, (jchar)(jint)51, (jchar)(jint)52,
   (jchar)(jint)53, (jchar)(jint)54, (jchar)(jint)55, (jchar)(jint)56,
   (jchar)(jint)57, (jchar)(jint)58, (jchar)(jint)59, (jchar)(jint)60,
   (jchar)(jint)61, (jchar)(jint)62, (jchar)(jint)63, (jchar)(jint)64,
   (jchar)(jint)65, (jchar)(jint)66, (jchar)(jint)67, (jchar)(jint)68,
   (jchar)(jint)69, (jchar)(jint)70, (jchar)(jint)71, (jchar)(jint)72,
   (jchar)(jint)73, (jchar)(jint)74, (jchar)(jint)75, (jchar)(jint)76,
   (jchar)(jint)77, (jchar)(jint)78, (jchar)(jint)79, (jchar)(jint)80,
   (jchar)(jint)81, (jchar)(jint)82, (jchar)(jint)83, (jchar)(jint)84,
   (jchar)(jint)85, (jchar)(jint)86, (jchar)(jint)87, (jchar)(jint)88,
   (jchar)(jint)89, (jchar)(jint)90, (jchar)(jint)91, (jchar)(jint)92,
   (jchar)(jint)93, (jchar)(jint)94, (jchar)(jint)95, (jchar)(jint)96,
   (jchar)(jint)97, (jchar)(jint)98, (jchar)(jint)99, (jchar)(jint)100,
   (jchar)(jint)101, (jchar)(jint)102, (jchar)(jint)103, (jchar)(jint)104,
   (jchar)(jint)105, (jchar)(jint)106, (jchar)(jint)107, (jchar)(jint)108,
   (jchar)(jint)109, (jchar)(jint)110, (jchar)(jint)111, (jchar)(jint)112,
   (jchar)(jint)113, (jchar)(jint)114, (jchar)(jint)115, (jchar)(jint)116,
   (jchar)(jint)117, (jchar)(jint)118, (jchar)(jint)119, (jchar)(jint)120,
   (jchar)(jint)121, (jchar)(jint)122, (jchar)(jint)123, (jchar)(jint)124,
   (jchar)(jint)125, (jchar)(jint)126, (jchar)(jint)127, (jchar)(jint)8364,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)8218, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)8222, (jchar)(jint)8230, (jchar)(jint)8224, (jchar)(jint)8225,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)8240, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)8249, gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)168,
   (jchar)(jint)711, (jchar)(jint)184, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)8216, (jchar)(jint)8217, (jchar)(jint)8220, (jchar)(jint)8221,
   (jchar)(jint)8226, (jchar)(jint)8211, (jchar)(jint)8212, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)8482, gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)8250,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)175, (jchar)(jint)731,
   gnu_java_nio_charset_ByteCharset__NONE, (jchar)(jint)160, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)162, (jchar)(jint)163, (jchar)(jint)164, gnu_java_nio_charset_ByteCharset__NONE,
   (jchar)(jint)166, (jchar)(jint)167, (jchar)(jint)216, (jchar)(jint)169,
   (jchar)(jint)342, (jchar)(jint)171, (jchar)(jint)172, (jchar)(jint)173,
   (jchar)(jint)174, (jchar)(jint)198, (jchar)(jint)176, (jchar)(jint)177,
   (jchar)(jint)178, (jchar)(jint)179, (jchar)(jint)180, (jchar)(jint)181,
   (jchar)(jint)182, (jchar)(jint)183, (jchar)(jint)248, (jchar)(jint)185,
   (jchar)(jint)343, (jchar)(jint)187, (jchar)(jint)188, (jchar)(jint)189,
   (jchar)(jint)190, (jchar)(jint)230, (jchar)(jint)260, (jchar)(jint)302,
   (jchar)(jint)256, (jchar)(jint)262, (jchar)(jint)196, (jchar)(jint)197,
   (jchar)(jint)280, (jchar)(jint)274, (jchar)(jint)268, (jchar)(jint)201,
   (jchar)(jint)377, (jchar)(jint)278, (jchar)(jint)290, (jchar)(jint)310,
   (jchar)(jint)298, (jchar)(jint)315, (jchar)(jint)352, (jchar)(jint)323,
   (jchar)(jint)325, (jchar)(jint)211, (jchar)(jint)332, (jchar)(jint)213,
   (jchar)(jint)214, (jchar)(jint)215, (jchar)(jint)370, (jchar)(jint)321,
   (jchar)(jint)346, (jchar)(jint)362, (jchar)(jint)220, (jchar)(jint)379,
   (jchar)(jint)381, (jchar)(jint)223, (jchar)(jint)261, (jchar)(jint)303,
   (jchar)(jint)257, (jchar)(jint)263, (jchar)(jint)228, (jchar)(jint)229,
   (jchar)(jint)281, (jchar)(jint)275, (jchar)(jint)269, (jchar)(jint)233,
   (jchar)(jint)378, (jchar)(jint)279, (jchar)(jint)291, (jchar)(jint)311,
   (jchar)(jint)299, (jchar)(jint)316, (jchar)(jint)353, (jchar)(jint)324,
   (jchar)(jint)326, (jchar)(jint)243, (jchar)(jint)333, (jchar)(jint)245,
   (jchar)(jint)246, (jchar)(jint)247, (jchar)(jint)371, (jchar)(jint)322,
   (jchar)(jint)347, (jchar)(jint)363, (jchar)(jint)252, (jchar)(jint)380,
   (jchar)(jint)382, (jchar)(jint)729
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype9_Wndws1F6 jcgo_array9_Wndws1E1=
{
 (jvtable)&jObjectArr_methods,
 JCGO_MON_INIT
 6,
 JCGO_CLASSREF_OF(java_lang_String__class),
 {
  (jObject)JCGO_STRREF_OF(jcgo_string3_Wndws1E1), (jObject)JCGO_STRREF_OF(jcgo_string4_Wndws1E1),
   (jObject)JCGO_STRREF_OF(jcgo_string5_Wndws1E1), (jObject)JCGO_STRREF_OF(jcgo_string6_Wndws1E1),
   (jObject)JCGO_STRREF_OF(jcgo_string7_Wndws1E1), (jObject)JCGO_STRREF_OF(jcgo_string8_Wndws1E1)
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype98_GmCnnctn jcgo_array10_Wndws1E1=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 32,
 {
  (jbyte)(jchar)103/*'g'*/, (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)117/*'u'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)106/*'j'*/, (jbyte)(jchar)97/*'a'*/,
   (jbyte)(jchar)118/*'v'*/, (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)110/*'n'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)111/*'o'*/,
   (jbyte)(jchar)46/*'.'*/, (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)104/*'h'*/,
   (jbyte)(jchar)97/*'a'*/, (jbyte)(jchar)114/*'r'*/, (jbyte)(jchar)115/*'s'*/,
   (jbyte)(jchar)101/*'e'*/, (jbyte)(jchar)116/*'t'*/, (jbyte)(jchar)46/*'.'*/,
   (jbyte)(jchar)87/*'W'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)100/*'d'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)119/*'w'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)49/*'1'*/, (jbyte)(jchar)50/*'2'*/,
   (jbyte)(jchar)53/*'5'*/, (jbyte)(jchar)55/*'7'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype2_BZLib jcgo_array11_Wndws1E1=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 6,
 {
  (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)49/*'1'*/,
   (jbyte)(jchar)50/*'2'*/, (jbyte)(jchar)53/*'5'*/, (jbyte)(jchar)55/*'7'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype24_Object jcgo_array12_Wndws1E1=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 7,
 {
  (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)45/*'-'*/,
   (jbyte)(jchar)49/*'1'*/, (jbyte)(jchar)50/*'2'*/, (jbyte)(jchar)53/*'5'*/,
   (jbyte)(jchar)55/*'7'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype24_Object jcgo_array13_Wndws1E1=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 7,
 {
  (jbyte)(jchar)99/*'c'*/, (jbyte)(jchar)112/*'p'*/, (jbyte)(jchar)95/*'_'*/,
   (jbyte)(jchar)49/*'1'*/, (jbyte)(jchar)50/*'2'*/, (jbyte)(jchar)53/*'5'*/,
   (jbyte)(jchar)55/*'7'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype28_Object jcgo_array14_Wndws1E1=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 11,
 {
  (jbyte)(jchar)119/*'w'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)100/*'d'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)119/*'w'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)49/*'1'*/, (jbyte)(jchar)50/*'2'*/,
   (jbyte)(jchar)53/*'5'*/, (jbyte)(jchar)55/*'7'*/
 }
};

JCGO_NOSEP_DATA CONST jcgo_arrtype26_Object jcgo_array15_Wndws1E1=
{
 (jvtable)&jbyteArr_methods,
 JCGO_MON_INIT
 12,
 {
  (jbyte)(jchar)119/*'w'*/, (jbyte)(jchar)105/*'i'*/, (jbyte)(jchar)110/*'n'*/,
   (jbyte)(jchar)100/*'d'*/, (jbyte)(jchar)111/*'o'*/, (jbyte)(jchar)119/*'w'*/,
   (jbyte)(jchar)115/*'s'*/, (jbyte)(jchar)95/*'_'*/, (jbyte)(jchar)49/*'1'*/,
   (jbyte)(jchar)50/*'2'*/, (jbyte)(jchar)53/*'5'*/, (jbyte)(jchar)55/*'7'*/
 }
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_Wndws1E1
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array10_Wndws1E1),
 0, 32, (jint)0x7aa60a9eL
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_Wndws1E1
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array10_Wndws1E1),
 21, 11, (jint)0xd6855966L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_Wndws1E1
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array11_Wndws1E1),
 0, 6, (jint)0xaf311670L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string5_Wndws1E1
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array12_Wndws1E1),
 0, 7, (jint)0x36b8d9e3L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string6_Wndws1E1
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array13_Wndws1E1),
 0, 7, (jint)0x39797115L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string7_Wndws1E1
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array14_Wndws1E1),
 0, 11, (jint)0x731bb186L
};

JCGO_NOSEP_DATA JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string8_Wndws1E1
 JCGO_THRD_ATTRNONGC=
{
 &java_lang_String_methods,
 JCGO_MON_INIT
 (java_lang_Object)JCGO_OBJREF_OF(jcgo_array15_Wndws1E1),
 0, 12, (jint)0xf2e238bfL
};

#ifdef CHKALL_gnu_java_nio_charset_Windows1257
#include "jcgochke.h"
#endif

#endif
