/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__loadBad__L2xrui( package_Buffer buffer );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__loadHost__L2xrui( package_Buffer buffer );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__loadFragments__L2xrui( package_Buffer buffer );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__loadTld__L2xrui( package_Buffer buffer );

JCGO_NOSEP_INLINE jboolean CFASTCALL
package_WordFilter__isLetter__C( jchar c );

JCGO_NOSEP_INLINE jboolean CFASTCALL
package_WordFilter__isDigit__C( jchar c );

JCGO_NOSEP_INLINE jboolean CFASTCALL
package_WordFilter__isSpecial__C( jchar c );

JCGO_NOSEP_INLINE jboolean CFASTCALL
package_WordFilter__compareCharIds__BAABB( jObjectArr charIdData,
 jbyte prevCharId, jbyte curCharId );

JCGO_NOSEP_INLINE jint CFASTCALL
package_WordFilter__word2hash__CA( jcharArr word );

JCGO_NOSEP_INLINE jboolean CFASTCALL
package_WordFilter__containsFragmentHashes__CA( jcharArr input );

JCGO_NOSEP_INLINE jint CFASTCALL
package_WordFilter__getAsteriskCount__CACAI( jcharArr input, jcharArr
 input1, jint len );

JCGO_NOSEP_INLINE jint CFASTCALL
package_WordFilter__getAsteriskCount2__CACAI( jcharArr input, jcharArr
 input1, jint len );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__applyTldFilter__CACACACAI( jcharArr input, jcharArr
 input1, jcharArr input2, jcharArr tld, jint type );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__applyDotSlashFilter__CA( jcharArr input );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__applyBadwordFilter__CA( jcharArr input );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__applyHostFilter__CA( jcharArr input );

JCGO_NOSEP_INLINE jint CFASTCALL
package_WordFilter__indexOfDigit__CAI( jcharArr input, jint fromIndex
 );

JCGO_NOSEP_INLINE jint CFASTCALL
package_WordFilter__indexOfNonDigit__CAI( jcharArr input, jint fromIndex
 );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__heywhathteufck__CA( jcharArr input );

JCGO_NOSEP_INLINE jboolean CFASTCALL
package_WordFilter__isUppercase__C( jchar c );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__stripLowercase__CACA( jcharArr input, jcharArr
 output );

JCGO_NOSEP_INLINE jboolean CFASTCALL
package_WordFilter__isLowercase__C( jchar c );

JCGO_NOSEP_INLINE void CFASTCALL
package_WordFilter__toLowercase__CA( jcharArr input );

JCGO_NOSEP_FRWINL void CFASTCALL
package_WordFilter__loadFilters__L2xruiL2xruiL2xruiL2xrui( package_Buffer
 fragments, package_Buffer bad, package_Buffer host, package_Buffer
 tld );

JCGO_NOSEP_STATIC void CFASTCALL
package_WordFilter__readBuffer__L2xruiCAABAAA( package_Buffer buffer,
 jObjectArr wordList, jObjectArr charIds );

JCGO_NOSEP_FRWINL java_lang_String CFASTCALL
package_WordFilter__filter__Ls( java_lang_String input );
JCGO_NOSEP_STATIC java_lang_String CFASTCALL
package_WordFilter__filter__LsX( java_lang_String input, java_lang_String
 jcgo_stackparam );

JCGO_NOSEP_STATIC void CFASTCALL
package_WordFilter__applyWordFilter__CACABAA( jcharArr input, jcharArr
 wordlist, jObjectArr charIds );

JCGO_NOSEP_STATIC jint CFASTCALL
package_WordFilter__compareLettersNumbers__CCC( jchar filterChar,
 jchar currentChar, jchar nextChar );

JCGO_NOSEP_STATIC jint CFASTCALL
package_WordFilter__compareLettersSymbols__CCC( jchar filterChar,
 jchar currentChar, jchar nextChar );

JCGO_NOSEP_STATIC jbyte CFASTCALL
package_WordFilter__getCharId__C( jchar c );

JCGO_NOSEP_STATIC jboolean CFASTCALL
package_WordFilter__isNotLowercase__C( jchar c );

JCGO_NOSEP_STATIC package_WordFilter CFASTCALL
package_WordFilter__this__( package_WordFilter This );

struct package_WordFilter_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 package_WordFilter (CFASTCALL *jcgo_thisRtn)( package_WordFilter This
  );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct package_WordFilter_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct package_WordFilter_methods_s package_WordFilter_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct package_WordFilter_class_s
 package_WordFilter__class;

JCGO_SEP_GCEXTERN jintArr package_WordFilter__hashFragments;
JCGO_SEP_GCEXTERN jObjectArr package_WordFilter__badList;
JCGO_SEP_GCEXTERN jObjectArr package_WordFilter__badCharIds;
JCGO_SEP_GCEXTERN jObjectArr package_WordFilter__hostList;
JCGO_SEP_GCEXTERN jObjectArr package_WordFilter__hostCharIds;
JCGO_SEP_GCEXTERN jObjectArr package_WordFilter__tldList;
JCGO_SEP_GCEXTERN jintArr package_WordFilter__tldType;
JCGO_SEP_EXTERN CONST jObjectArr package_WordFilter__ignoreList;
JCGO_SEP_EXTERN CONST jboolean package_WordFilter__forceLowercase;

struct package_WordFilter_s
{
 CONST struct package_WordFilter_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
};

JCGO_SEP_EXTERN CONST jcgo_arrtype12_WordFltr jcgo_array9_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype10_WordFltr jcgo_array10_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype69_Mdclnt jcgo_array21_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype32_GameShll jcgo_array22_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype23_Object jcgo_array23_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype43_GameShll jcgo_array24_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype28_GameShll jcgo_array25_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype24_Object jcgo_array26_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype30_GameShll jcgo_array27_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype22_Object jcgo_array28_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype43_GameShll jcgo_array29_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype24_Object jcgo_array30_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype30_Object jcgo_array31_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype2_BZLib jcgo_array32_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype30_Object jcgo_array33_WordFltr;

JCGO_SEP_EXTERN CONST jcgo_arrtype30_Object jcgo_array34_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string5_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string6_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string7_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string8_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string11_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string13_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string14_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string15_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string16_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string17_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string18_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string19_WordFltr;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string20_WordFltr;

#endif
