/* DO NOT EDIT THIS FILE - it is machine generated (JCGO_116) */

#ifdef JCGO_116

#define package_World__colourTransparent (jint)12345678L

JCGO_NOSEP_INLINE void CFASTCALL
package_World__void( package_World This );

JCGO_NOSEP_INLINE void CFASTCALL
package_World__reset__( package_World This );

JCGO_NOSEP_INLINE void CFASTCALL
package_World__setObjectAdjacency__III( package_World This, jint i,
 jint j, jint k );

JCGO_NOSEP_INLINE void CFASTCALL
package_World__method407__III( package_World This, jint i, jint j,
 jint k );

JCGO_NOSEP_INLINE jint CFASTCALL
package_World__getTerrainColour__II( package_World This, jint x, jint
 y );

JCGO_NOSEP_INLINE package_World CFASTCALL
package_World__this__L03ibmL0s0x4( package_World This, package_Scene
 scene, package_Surface surface );
JCGO_NOSEP_FRWINL package_World CFASTCALL
package_World__new__L03ibmL0s0x4( package_Scene scene, package_Surface
 surface );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getWallEastwest__II( package_World This, jint x, jint
 y );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__setTerrainAmbience__IIIII( package_World This, jint
 x, jint y, jint x2, jint y2, jint ambience );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getWallRoof__II( package_World This, jint x, jint y
 );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getElevation__II( package_World This, jint x, jint
 y );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getWallDiagonal__II( package_World This, jint x, jint
 y );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__removeObject2__III( package_World This, jint x, jint
 y, jint id );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__removeWallObject__IIII( package_World This, jint x,
 jint y, jint k, jint id );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__method402__IIIII( package_World This, jint i, jint
 j, jint k, jint l, jint i1 );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__loadSection__IIII( package_World This, jint x, jint
 y, jint plane, jint chunk );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__method404__IIII( package_World This, jint x, jint y,
 jint k, jint l );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getObjectAdjacency__II( package_World This, jint x,
 jint y );

JCGO_NOSEP_STATIC jboolean CFASTCALL
package_World__hasRoof__II( package_World This, jint x, jint y );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__setTiles__( package_World This );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getWallNorthsouth__II( package_World This, jint x,
 jint y );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getTileDirection__II( package_World This, jint x, jint
 y );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getTileDecoration__IIII( package_World This, jint x,
 jint y, jint unused, jint def );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getTileDecoration__III( package_World This, jint x,
 jint y, jint unused );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__setTileDecoration__III( package_World This, jint x,
 jint y, jint v );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__route__IIIIIIIAIAZ( package_World This, jintArr routeX,
 jintArr routeY, jint startX, jint startY, jint endX1, jint endY1,
 jint endX2, jint endY2, jboolean objects );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__setObjectAdjacency__IIII( package_World This, jint
 x, jint y, jint dir, jint id );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__loadSection__IIIZ( package_World This, jint x, jint
 y, jint plane, jboolean flag );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getTileType__III( package_World This, jint i, jint
 j, jint k );

JCGO_NOSEP_FRWINL void CFASTCALL
package_World__addModels__L98u34A( package_World This, jObjectArr
 aclass5 );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__method422__L98u34IIIII( package_World This, package_GameModel
 gameModel, jint i, jint j, jint k, jint l, jint i1 );

JCGO_NOSEP_STATIC jint CFASTCALL
package_World__getTerrainHeight__II( package_World This, jint x, jint
 y );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__loadSection__III( package_World This, jint x, jint
 y, jint plane );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__method425__III( package_World This, jint i, jint j,
 jint k );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__removeObject__III( package_World This, jint x, jint
 y, jint id );

JCGO_NOSEP_STATIC jboolean CFASTCALL
package_World__method427__II( package_World This, jint i, jint j );

JCGO_NOSEP_STATIC void CFASTCALL
package_World__method428__IIIII( package_World This, jint i, jint
 j, jint k, jint l, jint i1 );

struct package_World_methods_s
{
 java_lang_Class jcgo_class;
 JCGO_GCJDESCR_DEFN
 JCGO_TYPEID_T jcgo_typeid;
 JCGO_OBJSIZE_T jcgo_objsize;
 CONST struct jcgo_reflect_s *jcgo_reflect;
 JCGO_CLINIT_DEFN
 package_World (CFASTCALL *jcgo_thisRtn)( package_World This );
 jboolean (CFASTCALL *equals__Lo)( java_lang_Object This, java_lang_Object
  obj );
 jint (CFASTCALL *hashCode__)( java_lang_Object This );
 java_lang_String (CFASTCALL *toString__)( java_lang_Object This );
 void (CFASTCALL *finalize__)( java_lang_Object This );
};

struct package_World_class_s
{
 struct java_lang_Class_s jcgo_class;
};

JCGO_SEP_EXTERN CONST struct package_World_methods_s package_World_methods;
JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct package_World_class_s package_World__class;

struct package_World_s
{
 CONST struct package_World_methods_s *JCGO_IMMFLD_CONST jcgo_methods;
 JCGO_MON_DEFN
 jObjectArr objectAdjacency;
 jObjectArr tileDirection;
 jObjectArr wallModels;
 jintArr terrainColours;
 jObjectArr wallsNorthsouth;
 package_GameModel parentModel;
 jObjectArr wallsRoof;
 jObjectArr terrainHeight;
 jObjectArr roofModels;
 jObjectArr terrainColour;
 jintArr localY;
 jObjectArr tileDecoration;
 jObjectArr routeVia;
 jObjectArr wallsDiagonal;
 jObjectArr wallsEastwest;
 jObjectArr terrainHeightLocal;
 jbyteArr landscapePack;
 jbyteArr mapPack;
 package_Surface surface;
 package_Scene scene;
 jObjectArr terrainModels;
 jintArr localX;
 jbyteArr memberLandscapePack;
 jbyteArr memberMapPack;
 jint regionWidth;
 jint regionHeight;
 jint anInt585;
 jint baseMediaSprite;
 jboolean worldInitialised;
 jboolean aBoolean592;
 jboolean playerAlive;
};

JCGO_SEP_EXTERN CONST jcgo_arrtype30_Object jcgo_array8_World;

JCGO_SEP_EXTERN CONST jcgo_arrtype4_IntAddrs jcgo_array9_World;

JCGO_SEP_EXTERN CONST jcgo_arrtype4_IntAddrs jcgo_array10_World;

JCGO_SEP_EXTERN CONST jcgo_arrtype640_Mdclnt jcgo_array11_World;

JCGO_SEP_EXTERN CONST jcgo_arrtype32_GameShll jcgo_array12_World;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string1_World;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string2_World;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string3_World;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string4_World;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string5_World;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string6_World;

JCGO_SEP_EXTERN JCGO_NOTHR_CONST struct java_lang_String_s jcgo_string7_World;

#endif
